// Generated by esj-generator from the code list snapshots
// of the rule pack en16931 1.3.16: untdid-5189 of 2026-09-19.
// Do not edit.
package de.bsnsoft.esj.invoice.code;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Reason for an allowance, on the document or on a line.
 *
 * <p>UNTDID 5189 allowance or charge identification code, as admitted by EN 16931. UN/CEFACT
 * (UNTDID), listed for EN 16931 by the European Commission, snapshot of 2026-09-19, 19 codes.
 *
 * <p>The registry names this list at BT-98, BT-140.
 *
 * <p>A code the snapshot does not carry is representable: {@code AllowanceReason.custom(code)}
 * yields a {@link CustomCode}, and {@code resolve(code)} yields the constant where there is one and
 * a {@code CustomCode} where there is none. Whether a code is admissible is decided by the rule
 * pack and not here.
 */
public enum AllowanceReason implements Coded {

    /** {@code 41}, Bonus for works ahead of schedule. */
    BONUS_FOR_WORKS_AHEAD_OF_SCHEDULE("41", "Bonus for works ahead of schedule", "untdid-5189"),
    /** {@code 42}, Other bonus. */
    OTHER_BONUS("42", "Other bonus", "untdid-5189"),
    /** {@code 60}, Manufacturer’s consumer discount. */
    MANUFACTURER_S_CONSUMER_DISCOUNT("60", "Manufacturer’s consumer discount", "untdid-5189"),
    /** {@code 62}, Due to military status. */
    DUE_TO_MILITARY_STATUS("62", "Due to military status", "untdid-5189"),
    /** {@code 63}, Due to work accident. */
    DUE_TO_WORK_ACCIDENT("63", "Due to work accident", "untdid-5189"),
    /** {@code 64}, Special agreement. */
    SPECIAL_AGREEMENT("64", "Special agreement", "untdid-5189"),
    /** {@code 65}, Production error discount. */
    PRODUCTION_ERROR_DISCOUNT("65", "Production error discount", "untdid-5189"),
    /** {@code 66}, New outlet discount. */
    NEW_OUTLET_DISCOUNT("66", "New outlet discount", "untdid-5189"),
    /** {@code 67}, Sample discount. */
    SAMPLE_DISCOUNT("67", "Sample discount", "untdid-5189"),
    /** {@code 68}, End-of-range discount. */
    END_OF_RANGE_DISCOUNT("68", "End-of-range discount", "untdid-5189"),
    /** {@code 70}, Incoterm discount. */
    INCOTERM_DISCOUNT("70", "Incoterm discount", "untdid-5189"),
    /** {@code 71}, Point of sales threshold allowance. */
    POINT_OF_SALES_THRESHOLD_ALLOWANCE("71", "Point of sales threshold allowance", "untdid-5189"),
    /** {@code 88}, Material surcharge/deduction. */
    MATERIAL_SURCHARGE_DEDUCTION("88", "Material surcharge/deduction", "untdid-5189"),
    /** {@code 95}, Discount. */
    DISCOUNT("95", "Discount", "untdid-5189"),
    /** {@code 100}, Special rebate. */
    SPECIAL_REBATE("100", "Special rebate", "untdid-5189"),
    /** {@code 102}, Fixed long term. */
    FIXED_LONG_TERM("102", "Fixed long term", "untdid-5189"),
    /** {@code 103}, Temporary. */
    TEMPORARY("103", "Temporary", "untdid-5189"),
    /** {@code 104}, Standard. */
    STANDARD("104", "Standard", "untdid-5189"),
    /** {@code 105}, Yearly turnover. */
    YEARLY_TURNOVER("105", "Yearly turnover", "untdid-5189");

    private static final Map<String, AllowanceReason> BY_CODE = byCode();

    private final String code;

    private final String publishedName;

    private final String listId;

    AllowanceReason(String code, String publishedName, String listId) {
        this.code = code;
        this.publishedName = publishedName;
        this.listId = listId;
    }

    /**
     * Returns the constant carrying a code.
     *
     * <p>The comparison is exact, code point by code point: a code list is a list of
     * codes and not of their spellings.
     *
     * @param code the code
     * @return the constant
     * @throws IllegalArgumentException if the snapshot does not carry the code
     * @throws NullPointerException     if {@code code} is {@code null}
     */
    public static AllowanceReason of(String code) {
        AllowanceReason value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        if (value == null) {
            throw new IllegalArgumentException("the snapshot of AllowanceReason does not carry the code "
                    + code + "; AllowanceReason.custom(code) represents a code it does not have");
        }
        return value;
    }

    /**
     * Returns the constant carrying a code, or a custom code where there is none.
     *
     * @param code the code as a document carries it
     * @return the constant or a {@link CustomCode}
     * @throws NullPointerException     if {@code code} is {@code null}
     * @throws IllegalArgumentException if the code is blank
     */
    public static Coded resolve(String code) {
        AllowanceReason value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        return value != null ? value : new CustomCode("AllowanceReason", code);
    }

    /**
     * Returns a code the snapshot does not carry.
     *
     * @param code the code
     * @return the custom code
     * @throws IllegalArgumentException if the snapshot carries the code, which has a
     *                                  constant and must not have a second representation,
     *                                  or if the code is blank
     * @throws NullPointerException     if {@code code} is {@code null}
     */
    public static Coded custom(String code) {
        AllowanceReason value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        if (value != null) {
            throw new IllegalArgumentException("the snapshot of AllowanceReason carries the code "
                    + code + " as " + value.name());
        }
        return new CustomCode("AllowanceReason", code);
    }

    /**
     * Returns the code as it is written into the document.
     *
     * @return the code
     */
    @Override
    public String code() {
        return code;
    }

    /**
     * Returns the name the publisher of the list gives the code.
     *
     * @return the name, empty where the publisher gives none
     */
    @Override
    public String publishedName() {
        return publishedName;
    }

    /**
     * Returns the identifier of the code list the constant came from.
     *
     * @return the list identifier, for example {@code untdid-5189}
     */
    @Override
    public String listId() {
        return listId;
    }

    private static Map<String, AllowanceReason> byCode() {
        Map<String, AllowanceReason> byCode = new LinkedHashMap<>();
        for (AllowanceReason value : values()) {
            byCode.put(value.code, value);
        }
        return Map.copyOf(byCode);
    }
}
