// Generated by esj-generator from the code list snapshots
// of the rule pack en16931 1.3.16: iso-3166-1 of 2026-09-19.
// Do not edit.
package de.bsnsoft.esj.invoice.code;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Country of an address or of the origin of an item.
 *
 * <p>ISO 3166-1 alpha-2 country codes, as admitted by EN 16931. ISO, listed for EN 16931 by the
 * European Commission, snapshot of 2026-09-19, 251 codes.
 *
 * <p>The registry names this list at BT-40, BT-55, BT-69, BT-80, BT-159.
 *
 * <p>A code the snapshot does not carry is representable: {@code Country.custom(code)} yields a
 * {@link CustomCode}, and {@code resolve(code)} yields the constant where there is one and a {@code
 * CustomCode} where there is none. Whether a code is admissible is decided by the rule pack and not
 * here.
 */
public enum Country implements Coded {

    /** {@code AD}, Andorra. */
    AD("AD", "Andorra", "iso-3166-1"),
    /** {@code AE}, United Arab Emirates (the). */
    AE("AE", "United Arab Emirates (the)", "iso-3166-1"),
    /** {@code AF}, Afghanistan. */
    AF("AF", "Afghanistan", "iso-3166-1"),
    /** {@code AG}, Antigua and Barbuda. */
    AG("AG", "Antigua and Barbuda", "iso-3166-1"),
    /** {@code AI}, Anguilla. */
    AI("AI", "Anguilla", "iso-3166-1"),
    /** {@code AL}, Albania. */
    AL("AL", "Albania", "iso-3166-1"),
    /** {@code AM}, Armenia. */
    AM("AM", "Armenia", "iso-3166-1"),
    /** {@code AO}, Angola. */
    AO("AO", "Angola", "iso-3166-1"),
    /** {@code AQ}, Antarctica. */
    AQ("AQ", "Antarctica", "iso-3166-1"),
    /** {@code AR}, Argentina. */
    AR("AR", "Argentina", "iso-3166-1"),
    /** {@code AS}, American Samoa. */
    AS("AS", "American Samoa", "iso-3166-1"),
    /** {@code AT}, Austria. */
    AT("AT", "Austria", "iso-3166-1"),
    /** {@code AU}, Australia. */
    AU("AU", "Australia", "iso-3166-1"),
    /** {@code AW}, Aruba. */
    AW("AW", "Aruba", "iso-3166-1"),
    /** {@code AX}, Åland Islands. */
    AX("AX", "Åland Islands", "iso-3166-1"),
    /** {@code AZ}, Azerbaijan. */
    AZ("AZ", "Azerbaijan", "iso-3166-1"),
    /** {@code BA}, Bosnia and Herzegovina. */
    BA("BA", "Bosnia and Herzegovina", "iso-3166-1"),
    /** {@code BB}, Barbados. */
    BB("BB", "Barbados", "iso-3166-1"),
    /** {@code BD}, Bangladesh. */
    BD("BD", "Bangladesh", "iso-3166-1"),
    /** {@code BE}, Belgium. */
    BE("BE", "Belgium", "iso-3166-1"),
    /** {@code BF}, Burkina Faso. */
    BF("BF", "Burkina Faso", "iso-3166-1"),
    /** {@code BG}, Bulgaria. */
    BG("BG", "Bulgaria", "iso-3166-1"),
    /** {@code BH}, Bahrain. */
    BH("BH", "Bahrain", "iso-3166-1"),
    /** {@code BI}, Burundi. */
    BI("BI", "Burundi", "iso-3166-1"),
    /** {@code BJ}, Benin. */
    BJ("BJ", "Benin", "iso-3166-1"),
    /** {@code BL}, Saint Barthélemy. */
    BL("BL", "Saint Barthélemy", "iso-3166-1"),
    /** {@code BM}, Bermuda. */
    BM("BM", "Bermuda", "iso-3166-1"),
    /** {@code BN}, Brunei Darussalam. */
    BN("BN", "Brunei Darussalam", "iso-3166-1"),
    /** {@code BO}, Bolivia (Plurinational State of). */
    BO("BO", "Bolivia (Plurinational State of)", "iso-3166-1"),
    /** {@code BQ}, Bonaire, Sint Eustatius and Saba. */
    BQ("BQ", "Bonaire, Sint Eustatius and Saba", "iso-3166-1"),
    /** {@code BR}, Brazil. */
    BR("BR", "Brazil", "iso-3166-1"),
    /** {@code BS}, Bahamas (The). */
    BS("BS", "Bahamas (The)", "iso-3166-1"),
    /** {@code BT}, Bhutan. */
    BT("BT", "Bhutan", "iso-3166-1"),
    /** {@code BV}, Bouvet Island. */
    BV("BV", "Bouvet Island", "iso-3166-1"),
    /** {@code BW}, Botswana. */
    BW("BW", "Botswana", "iso-3166-1"),
    /** {@code BY}, Belarus. */
    BY("BY", "Belarus", "iso-3166-1"),
    /** {@code BZ}, Belize. */
    BZ("BZ", "Belize", "iso-3166-1"),
    /** {@code CA}, Canada. */
    CA("CA", "Canada", "iso-3166-1"),
    /** {@code CC}, Cocos (Keeling) Islands (the). */
    CC("CC", "Cocos (Keeling) Islands (the)", "iso-3166-1"),
    /** {@code CD}, Congo (the Democratic Republic of the). */
    CD("CD", "Congo (the Democratic Republic of the)", "iso-3166-1"),
    /** {@code CF}, Central African Republic (the). */
    CF("CF", "Central African Republic (the)", "iso-3166-1"),
    /** {@code CG}, Congo (the). */
    CG("CG", "Congo (the)", "iso-3166-1"),
    /** {@code CH}, Switzerland. */
    CH("CH", "Switzerland", "iso-3166-1"),
    /** {@code CI}, Côte d'Ivoire. */
    CI("CI", "Côte d'Ivoire", "iso-3166-1"),
    /** {@code CK}, Cook Islands (the). */
    CK("CK", "Cook Islands (the)", "iso-3166-1"),
    /** {@code CL}, Chile. */
    CL("CL", "Chile", "iso-3166-1"),
    /** {@code CM}, Cameroon. */
    CM("CM", "Cameroon", "iso-3166-1"),
    /** {@code CN}, China. */
    CN("CN", "China", "iso-3166-1"),
    /** {@code CO}, Colombia. */
    CO("CO", "Colombia", "iso-3166-1"),
    /** {@code CR}, Costa Rica. */
    CR("CR", "Costa Rica", "iso-3166-1"),
    /** {@code CU}, Cuba. */
    CU("CU", "Cuba", "iso-3166-1"),
    /** {@code CV}, Cabo Verde. */
    CV("CV", "Cabo Verde", "iso-3166-1"),
    /** {@code CW}, Curaçao. */
    CW("CW", "Curaçao", "iso-3166-1"),
    /** {@code CX}, Christmas Island. */
    CX("CX", "Christmas Island", "iso-3166-1"),
    /** {@code CY}, Cyprus. */
    CY("CY", "Cyprus", "iso-3166-1"),
    /** {@code CZ}, Czechia. */
    CZ("CZ", "Czechia", "iso-3166-1"),
    /** {@code DE}, Germany. */
    DE("DE", "Germany", "iso-3166-1"),
    /** {@code DJ}, Djibouti. */
    DJ("DJ", "Djibouti", "iso-3166-1"),
    /** {@code DK}, Denmark. */
    DK("DK", "Denmark", "iso-3166-1"),
    /** {@code DM}, Dominica. */
    DM("DM", "Dominica", "iso-3166-1"),
    /** {@code DO}, Dominican Republic (the). */
    DO("DO", "Dominican Republic (the)", "iso-3166-1"),
    /** {@code DZ}, Algeria. */
    DZ("DZ", "Algeria", "iso-3166-1"),
    /** {@code EC}, Ecuador. */
    EC("EC", "Ecuador", "iso-3166-1"),
    /** {@code EE}, Estonia. */
    EE("EE", "Estonia", "iso-3166-1"),
    /** {@code EG}, Egypt. */
    EG("EG", "Egypt", "iso-3166-1"),
    /** {@code EH}, Western Sahara*. */
    EH("EH", "Western Sahara*", "iso-3166-1"),
    /** {@code ER}, Eritrea. */
    ER("ER", "Eritrea", "iso-3166-1"),
    /** {@code ES}, Spain. */
    ES("ES", "Spain", "iso-3166-1"),
    /** {@code ET}, Ethiopia. */
    ET("ET", "Ethiopia", "iso-3166-1"),
    /** {@code FI}, Finland. */
    FI("FI", "Finland", "iso-3166-1"),
    /** {@code FJ}, Fiji. */
    FJ("FJ", "Fiji", "iso-3166-1"),
    /** {@code FK}, Falkland Islands (the) [Malvinas]. */
    FK("FK", "Falkland Islands (the) [Malvinas]", "iso-3166-1"),
    /** {@code FM}, Micronesia (Federated States of). */
    FM("FM", "Micronesia (Federated States of)", "iso-3166-1"),
    /** {@code FO}, Faroe Islands (the). */
    FO("FO", "Faroe Islands (the)", "iso-3166-1"),
    /** {@code FR}, France. */
    FR("FR", "France", "iso-3166-1"),
    /** {@code GA}, Gabon. */
    GA("GA", "Gabon", "iso-3166-1"),
    /** {@code GB}, United Kingdom of Great Britain and Northern Ireland (the). */
    GB("GB", "United Kingdom of Great Britain and Northern Ireland (the)", "iso-3166-1"),
    /** {@code GD}, Grenada. */
    GD("GD", "Grenada", "iso-3166-1"),
    /** {@code GE}, Georgia. */
    GE("GE", "Georgia", "iso-3166-1"),
    /** {@code GF}, French Guiana. */
    GF("GF", "French Guiana", "iso-3166-1"),
    /** {@code GG}, Guernsey. */
    GG("GG", "Guernsey", "iso-3166-1"),
    /** {@code GH}, Ghana. */
    GH("GH", "Ghana", "iso-3166-1"),
    /** {@code GI}, Gibraltar. */
    GI("GI", "Gibraltar", "iso-3166-1"),
    /** {@code GL}, Greenland. */
    GL("GL", "Greenland", "iso-3166-1"),
    /** {@code GM}, Gambia (the). */
    GM("GM", "Gambia (the)", "iso-3166-1"),
    /** {@code GN}, Guinea. */
    GN("GN", "Guinea", "iso-3166-1"),
    /** {@code GP}, Guadeloupe. */
    GP("GP", "Guadeloupe", "iso-3166-1"),
    /** {@code GQ}, Equatorial Guinea. */
    GQ("GQ", "Equatorial Guinea", "iso-3166-1"),
    /** {@code GR}, Greece. */
    GR("GR", "Greece", "iso-3166-1"),
    /** {@code GS}, South Georgia and the South Sandwich Islands. */
    GS("GS", "South Georgia and the South Sandwich Islands", "iso-3166-1"),
    /** {@code GT}, Guatemala. */
    GT("GT", "Guatemala", "iso-3166-1"),
    /** {@code GU}, Guam. */
    GU("GU", "Guam", "iso-3166-1"),
    /** {@code GW}, Guinea-Bissau. */
    GW("GW", "Guinea-Bissau", "iso-3166-1"),
    /** {@code GY}, Guyana. */
    GY("GY", "Guyana", "iso-3166-1"),
    /** {@code HK}, Hong Kong. */
    HK("HK", "Hong Kong", "iso-3166-1"),
    /** {@code HM}, Heard Island and McDonald Islands. */
    HM("HM", "Heard Island and McDonald Islands", "iso-3166-1"),
    /** {@code HN}, Honduras. */
    HN("HN", "Honduras", "iso-3166-1"),
    /** {@code HR}, Croatia. */
    HR("HR", "Croatia", "iso-3166-1"),
    /** {@code HT}, Haiti. */
    HT("HT", "Haiti", "iso-3166-1"),
    /** {@code HU}, Hungary. */
    HU("HU", "Hungary", "iso-3166-1"),
    /** {@code ID}, Indonesia. */
    ID("ID", "Indonesia", "iso-3166-1"),
    /** {@code IE}, Ireland. */
    IE("IE", "Ireland", "iso-3166-1"),
    /** {@code IL}, Israel. */
    IL("IL", "Israel", "iso-3166-1"),
    /** {@code IM}, Isle of Man. */
    IM("IM", "Isle of Man", "iso-3166-1"),
    /** {@code IN}, India. */
    IN("IN", "India", "iso-3166-1"),
    /** {@code IO}, British Indian Ocean Territory (the). */
    IO("IO", "British Indian Ocean Territory (the)", "iso-3166-1"),
    /** {@code IQ}, Iraq. */
    IQ("IQ", "Iraq", "iso-3166-1"),
    /** {@code IR}, Iran (Islamic Republic of). */
    IR("IR", "Iran (Islamic Republic of)", "iso-3166-1"),
    /** {@code IS}, Iceland. */
    IS("IS", "Iceland", "iso-3166-1"),
    /** {@code IT}, Italy. */
    IT("IT", "Italy", "iso-3166-1"),
    /** {@code JE}, Jersey. */
    JE("JE", "Jersey", "iso-3166-1"),
    /** {@code JM}, Jamaica. */
    JM("JM", "Jamaica", "iso-3166-1"),
    /** {@code JO}, Jordan. */
    JO("JO", "Jordan", "iso-3166-1"),
    /** {@code JP}, Japan. */
    JP("JP", "Japan", "iso-3166-1"),
    /** {@code KE}, Kenya. */
    KE("KE", "Kenya", "iso-3166-1"),
    /** {@code KG}, Kyrgyzstan. */
    KG("KG", "Kyrgyzstan", "iso-3166-1"),
    /** {@code KH}, Cambodia. */
    KH("KH", "Cambodia", "iso-3166-1"),
    /** {@code KI}, Kiribati. */
    KI("KI", "Kiribati", "iso-3166-1"),
    /** {@code KM}, Comoros (the). */
    KM("KM", "Comoros (the)", "iso-3166-1"),
    /** {@code KN}, Saint Kitts and Nevis. */
    KN("KN", "Saint Kitts and Nevis", "iso-3166-1"),
    /** {@code KP}, Korea (the Democratic People's Republic of). */
    KP("KP", "Korea (the Democratic People's Republic of)", "iso-3166-1"),
    /** {@code KR}, Korea (the Republic of). */
    KR("KR", "Korea (the Republic of)", "iso-3166-1"),
    /** {@code KW}, Kuwait. */
    KW("KW", "Kuwait", "iso-3166-1"),
    /** {@code KY}, Cayman Islands (the). */
    KY("KY", "Cayman Islands (the)", "iso-3166-1"),
    /** {@code KZ}, Kazakhstan. */
    KZ("KZ", "Kazakhstan", "iso-3166-1"),
    /** {@code LA}, Lao People's Democratic Republic (the). */
    LA("LA", "Lao People's Democratic Republic (the)", "iso-3166-1"),
    /** {@code LB}, Lebanon. */
    LB("LB", "Lebanon", "iso-3166-1"),
    /** {@code LC}, Saint Lucia. */
    LC("LC", "Saint Lucia", "iso-3166-1"),
    /** {@code LI}, Liechtenstein. */
    LI("LI", "Liechtenstein", "iso-3166-1"),
    /** {@code LK}, Sri Lanka. */
    LK("LK", "Sri Lanka", "iso-3166-1"),
    /** {@code LR}, Liberia. */
    LR("LR", "Liberia", "iso-3166-1"),
    /** {@code LS}, Lesotho. */
    LS("LS", "Lesotho", "iso-3166-1"),
    /** {@code LT}, Lithuania. */
    LT("LT", "Lithuania", "iso-3166-1"),
    /** {@code LU}, Luxembourg. */
    LU("LU", "Luxembourg", "iso-3166-1"),
    /** {@code LV}, Latvia. */
    LV("LV", "Latvia", "iso-3166-1"),
    /** {@code LY}, Libya. */
    LY("LY", "Libya", "iso-3166-1"),
    /** {@code MA}, Morocco. */
    MA("MA", "Morocco", "iso-3166-1"),
    /** {@code MC}, Monaco. */
    MC("MC", "Monaco", "iso-3166-1"),
    /** {@code MD}, Moldova (the Republic of). */
    MD("MD", "Moldova (the Republic of)", "iso-3166-1"),
    /** {@code ME}, Montenegro. */
    ME("ME", "Montenegro", "iso-3166-1"),
    /** {@code MF}, Saint Martin (French part). */
    MF("MF", "Saint Martin (French part)", "iso-3166-1"),
    /** {@code MG}, Madagascar. */
    MG("MG", "Madagascar", "iso-3166-1"),
    /** {@code MH}, Marshall Islands (the). */
    MH("MH", "Marshall Islands (the)", "iso-3166-1"),
    /** {@code MK}, North Macedonia. */
    MK("MK", "North Macedonia", "iso-3166-1"),
    /** {@code ML}, Mali. */
    ML("ML", "Mali", "iso-3166-1"),
    /** {@code MM}, Myanmar. */
    MM("MM", "Myanmar", "iso-3166-1"),
    /** {@code MN}, Mongolia. */
    MN("MN", "Mongolia", "iso-3166-1"),
    /** {@code MO}, Macao. */
    MO("MO", "Macao", "iso-3166-1"),
    /** {@code MP}, Northern Mariana Islands (the). */
    MP("MP", "Northern Mariana Islands (the)", "iso-3166-1"),
    /** {@code MQ}, Martinique. */
    MQ("MQ", "Martinique", "iso-3166-1"),
    /** {@code MR}, Mauritania. */
    MR("MR", "Mauritania", "iso-3166-1"),
    /** {@code MS}, Montserrat. */
    MS("MS", "Montserrat", "iso-3166-1"),
    /** {@code MT}, Malta. */
    MT("MT", "Malta", "iso-3166-1"),
    /** {@code MU}, Mauritius. */
    MU("MU", "Mauritius", "iso-3166-1"),
    /** {@code MV}, Maldives. */
    MV("MV", "Maldives", "iso-3166-1"),
    /** {@code MW}, Malawi. */
    MW("MW", "Malawi", "iso-3166-1"),
    /** {@code MX}, Mexico. */
    MX("MX", "Mexico", "iso-3166-1"),
    /** {@code MY}, Malaysia. */
    MY("MY", "Malaysia", "iso-3166-1"),
    /** {@code MZ}, Mozambique. */
    MZ("MZ", "Mozambique", "iso-3166-1"),
    /** {@code NA}, Namibia. */
    NA("NA", "Namibia", "iso-3166-1"),
    /** {@code NC}, New Caledonia. */
    NC("NC", "New Caledonia", "iso-3166-1"),
    /** {@code NE}, Niger (the). */
    NE("NE", "Niger (the)", "iso-3166-1"),
    /** {@code NF}, Norfolk Island. */
    NF("NF", "Norfolk Island", "iso-3166-1"),
    /** {@code NG}, Nigeria. */
    NG("NG", "Nigeria", "iso-3166-1"),
    /** {@code NI}, Nicaragua. */
    NI("NI", "Nicaragua", "iso-3166-1"),
    /** {@code NL}, Netherlands (the). */
    NL("NL", "Netherlands (the)", "iso-3166-1"),
    /** {@code NO}, Norway. */
    NO("NO", "Norway", "iso-3166-1"),
    /** {@code NP}, Nepal. */
    NP("NP", "Nepal", "iso-3166-1"),
    /** {@code NR}, Nauru. */
    NR("NR", "Nauru", "iso-3166-1"),
    /** {@code NU}, Niue. */
    NU("NU", "Niue", "iso-3166-1"),
    /** {@code NZ}, New Zealand. */
    NZ("NZ", "New Zealand", "iso-3166-1"),
    /** {@code OM}, Oman. */
    OM("OM", "Oman", "iso-3166-1"),
    /** {@code PA}, Panama. */
    PA("PA", "Panama", "iso-3166-1"),
    /** {@code PE}, Peru. */
    PE("PE", "Peru", "iso-3166-1"),
    /** {@code PF}, French Polynesia. */
    PF("PF", "French Polynesia", "iso-3166-1"),
    /** {@code PG}, Papua New Guinea. */
    PG("PG", "Papua New Guinea", "iso-3166-1"),
    /** {@code PH}, Philippines (the). */
    PH("PH", "Philippines (the)", "iso-3166-1"),
    /** {@code PK}, Pakistan. */
    PK("PK", "Pakistan", "iso-3166-1"),
    /** {@code PL}, Poland. */
    PL("PL", "Poland", "iso-3166-1"),
    /** {@code PM}, Saint Pierre and Miquelon. */
    PM("PM", "Saint Pierre and Miquelon", "iso-3166-1"),
    /** {@code PN}, Pitcairn. */
    PN("PN", "Pitcairn", "iso-3166-1"),
    /** {@code PR}, Puerto Rico. */
    PR("PR", "Puerto Rico", "iso-3166-1"),
    /** {@code PS}, Palestine, State of. */
    PS("PS", "Palestine, State of", "iso-3166-1"),
    /** {@code PT}, Portugal. */
    PT("PT", "Portugal", "iso-3166-1"),
    /** {@code PW}, Palau. */
    PW("PW", "Palau", "iso-3166-1"),
    /** {@code PY}, Paraguay. */
    PY("PY", "Paraguay", "iso-3166-1"),
    /** {@code QA}, Qatar. */
    QA("QA", "Qatar", "iso-3166-1"),
    /** {@code RE}, Réunion. */
    RE("RE", "Réunion", "iso-3166-1"),
    /** {@code RO}, Romania. */
    RO("RO", "Romania", "iso-3166-1"),
    /** {@code RS}, Serbia. */
    RS("RS", "Serbia", "iso-3166-1"),
    /** {@code RU}, Russian Federation (the). */
    RU("RU", "Russian Federation (the)", "iso-3166-1"),
    /** {@code RW}, Rwanda. */
    RW("RW", "Rwanda", "iso-3166-1"),
    /** {@code SA}, Saudi Arabia. */
    SA("SA", "Saudi Arabia", "iso-3166-1"),
    /** {@code SB}, Solomon Islands. */
    SB("SB", "Solomon Islands", "iso-3166-1"),
    /** {@code SC}, Seychelles. */
    SC("SC", "Seychelles", "iso-3166-1"),
    /** {@code SD}, Sudan (the). */
    SD("SD", "Sudan (the)", "iso-3166-1"),
    /** {@code SE}, Sweden. */
    SE("SE", "Sweden", "iso-3166-1"),
    /** {@code SG}, Singapore. */
    SG("SG", "Singapore", "iso-3166-1"),
    /** {@code SH}, Saint Helena, Ascension and Tristan da Cunha. */
    SH("SH", "Saint Helena, Ascension and Tristan da Cunha", "iso-3166-1"),
    /** {@code SI}, Slovenia. */
    SI("SI", "Slovenia", "iso-3166-1"),
    /** {@code SJ}, Svalbard and Jan Mayen. */
    SJ("SJ", "Svalbard and Jan Mayen", "iso-3166-1"),
    /** {@code SK}, Slovakia. */
    SK("SK", "Slovakia", "iso-3166-1"),
    /** {@code SL}, Sierra Leone. */
    SL("SL", "Sierra Leone", "iso-3166-1"),
    /** {@code SM}, San Marino. */
    SM("SM", "San Marino", "iso-3166-1"),
    /** {@code SN}, Senegal. */
    SN("SN", "Senegal", "iso-3166-1"),
    /** {@code SO}, Somalia. */
    SO("SO", "Somalia", "iso-3166-1"),
    /** {@code SR}, Suriname. */
    SR("SR", "Suriname", "iso-3166-1"),
    /** {@code SS}, South Sudan. */
    SS("SS", "South Sudan", "iso-3166-1"),
    /** {@code ST}, Sao Tome and Principe. */
    ST("ST", "Sao Tome and Principe", "iso-3166-1"),
    /** {@code SV}, El Salvador. */
    SV("SV", "El Salvador", "iso-3166-1"),
    /** {@code SX}, Sint Maarten (Dutch part). */
    SX("SX", "Sint Maarten (Dutch part)", "iso-3166-1"),
    /** {@code SY}, Syrian Arab Republic (the). */
    SY("SY", "Syrian Arab Republic (the)", "iso-3166-1"),
    /** {@code SZ}, Eswatini. */
    SZ("SZ", "Eswatini", "iso-3166-1"),
    /** {@code TC}, Turks and Caicos Islands (the). */
    TC("TC", "Turks and Caicos Islands (the)", "iso-3166-1"),
    /** {@code TD}, Chad. */
    TD("TD", "Chad", "iso-3166-1"),
    /** {@code TF}, French Southern Territories (the). */
    TF("TF", "French Southern Territories (the)", "iso-3166-1"),
    /** {@code TG}, Togo. */
    TG("TG", "Togo", "iso-3166-1"),
    /** {@code TH}, Thailand. */
    TH("TH", "Thailand", "iso-3166-1"),
    /** {@code TJ}, Tajikistan. */
    TJ("TJ", "Tajikistan", "iso-3166-1"),
    /** {@code TK}, Tokelau. */
    TK("TK", "Tokelau", "iso-3166-1"),
    /** {@code TL}, Timor-Leste. */
    TL("TL", "Timor-Leste", "iso-3166-1"),
    /** {@code TM}, Turkmenistan. */
    TM("TM", "Turkmenistan", "iso-3166-1"),
    /** {@code TN}, Tunisia. */
    TN("TN", "Tunisia", "iso-3166-1"),
    /** {@code TO}, Tonga. */
    TO("TO", "Tonga", "iso-3166-1"),
    /** {@code TR}, Türkiye. */
    TR("TR", "Türkiye", "iso-3166-1"),
    /** {@code TT}, Trinidad and Tobago. */
    TT("TT", "Trinidad and Tobago", "iso-3166-1"),
    /** {@code TV}, Tuvalu. */
    TV("TV", "Tuvalu", "iso-3166-1"),
    /** {@code TW}, Taiwan (Province of China). */
    TW("TW", "Taiwan (Province of China)", "iso-3166-1"),
    /** {@code TZ}, Tanzania, the United Republic of. */
    TZ("TZ", "Tanzania, the United Republic of", "iso-3166-1"),
    /** {@code UA}, Ukraine. */
    UA("UA", "Ukraine", "iso-3166-1"),
    /** {@code UG}, Uganda. */
    UG("UG", "Uganda", "iso-3166-1"),
    /** {@code UM}, United States Minor Outlying Islands (the). */
    UM("UM", "United States Minor Outlying Islands (the)", "iso-3166-1"),
    /** {@code US}, United States of America (the). */
    US("US", "United States of America (the)", "iso-3166-1"),
    /** {@code UY}, Uruguay. */
    UY("UY", "Uruguay", "iso-3166-1"),
    /** {@code UZ}, Uzbekistan. */
    UZ("UZ", "Uzbekistan", "iso-3166-1"),
    /** {@code VA}, Holy See (the). */
    VA("VA", "Holy See (the)", "iso-3166-1"),
    /** {@code VC}, Saint Vincent and the Grenadines. */
    VC("VC", "Saint Vincent and the Grenadines", "iso-3166-1"),
    /** {@code VE}, Venezuela (Bolivarian Republic of). */
    VE("VE", "Venezuela (Bolivarian Republic of)", "iso-3166-1"),
    /** {@code VG}, Virgin Islands (British). */
    VG("VG", "Virgin Islands (British)", "iso-3166-1"),
    /** {@code VI}, Virgin Islands (U.S.). */
    VI("VI", "Virgin Islands (U.S.)", "iso-3166-1"),
    /** {@code VN}, Viet Nam. */
    VN("VN", "Viet Nam", "iso-3166-1"),
    /** {@code VU}, Vanuatu. */
    VU("VU", "Vanuatu", "iso-3166-1"),
    /** {@code WF}, Wallis and Futuna. */
    WF("WF", "Wallis and Futuna", "iso-3166-1"),
    /** {@code WS}, Samoa. */
    WS("WS", "Samoa", "iso-3166-1"),
    /** {@code YE}, Yemen. */
    YE("YE", "Yemen", "iso-3166-1"),
    /** {@code YT}, Mayotte. */
    YT("YT", "Mayotte", "iso-3166-1"),
    /** {@code ZA}, South Africa. */
    ZA("ZA", "South Africa", "iso-3166-1"),
    /** {@code ZM}, Zambia. */
    ZM("ZM", "Zambia", "iso-3166-1"),
    /** {@code ZW}, Zimbabwe. */
    ZW("ZW", "Zimbabwe", "iso-3166-1"),
    /** {@code 1A}, Kosovo. */
    C_1A("1A", "Kosovo", "iso-3166-1"),
    /** {@code XI}, United Kingdom (Northern Ireland). */
    XI("XI", "United Kingdom (Northern Ireland)", "iso-3166-1");

    private static final Map<String, Country> BY_CODE = byCode();

    private final String code;

    private final String publishedName;

    private final String listId;

    Country(String code, String publishedName, String listId) {
        this.code = code;
        this.publishedName = publishedName;
        this.listId = listId;
    }

    /**
     * Returns the constant carrying a code.
     *
     * <p>The comparison is exact, code point by code point: a code list is a list of
     * codes and not of their spellings.
     *
     * @param code the code
     * @return the constant
     * @throws IllegalArgumentException if the snapshot does not carry the code
     * @throws NullPointerException     if {@code code} is {@code null}
     */
    public static Country of(String code) {
        Country value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        if (value == null) {
            throw new IllegalArgumentException("the snapshot of Country does not carry the code "
                    + code + "; Country.custom(code) represents a code it does not have");
        }
        return value;
    }

    /**
     * Returns the constant carrying a code, or a custom code where there is none.
     *
     * @param code the code as a document carries it
     * @return the constant or a {@link CustomCode}
     * @throws NullPointerException     if {@code code} is {@code null}
     * @throws IllegalArgumentException if the code is blank
     */
    public static Coded resolve(String code) {
        Country value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        return value != null ? value : new CustomCode("Country", code);
    }

    /**
     * Returns a code the snapshot does not carry.
     *
     * @param code the code
     * @return the custom code
     * @throws IllegalArgumentException if the snapshot carries the code, which has a
     *                                  constant and must not have a second representation,
     *                                  or if the code is blank
     * @throws NullPointerException     if {@code code} is {@code null}
     */
    public static Coded custom(String code) {
        Country value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        if (value != null) {
            throw new IllegalArgumentException("the snapshot of Country carries the code "
                    + code + " as " + value.name());
        }
        return new CustomCode("Country", code);
    }

    /**
     * Returns the code as it is written into the document.
     *
     * @return the code
     */
    @Override
    public String code() {
        return code;
    }

    /**
     * Returns the name the publisher of the list gives the code.
     *
     * @return the name, empty where the publisher gives none
     */
    @Override
    public String publishedName() {
        return publishedName;
    }

    /**
     * Returns the identifier of the code list the constant came from.
     *
     * @return the list identifier, for example {@code iso-3166-1}
     */
    @Override
    public String listId() {
        return listId;
    }

    private static Map<String, Country> byCode() {
        Map<String, Country> byCode = new LinkedHashMap<>();
        for (Country value : values()) {
            byCode.put(value.code, value);
        }
        return Map.copyOf(byCode);
    }
}
