// Generated by esj-generator from the code list snapshots
// of the rule pack en16931 1.3.16: iso-4217 of 2026-09-19.
// Do not edit.
package de.bsnsoft.esj.invoice.code;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Currency of the amounts of the invoice.
 *
 * <p>ISO 4217 alpha-3 currency codes. ISO, maintenance agency SIX Group, snapshot of 2026-09-19,
 * 178 codes.
 *
 * <p>The registry names this list at BT-5, BT-6.
 *
 * <p>A code the snapshot does not carry is representable: {@code CurrencyCode.custom(code)} yields
 * a {@link CustomCode}, and {@code resolve(code)} yields the constant where there is one and a
 * {@code CustomCode} where there is none. Whether a code is admissible is decided by the rule pack
 * and not here.
 */
public enum CurrencyCode implements Coded {

    /** {@code AFN}, Afghani. */
    AFN("AFN", "Afghani", "iso-4217"),
    /** {@code EUR}, Euro. */
    EUR("EUR", "Euro", "iso-4217"),
    /** {@code ALL}, Lek. */
    ALL("ALL", "Lek", "iso-4217"),
    /** {@code DZD}, Algerian Dinar. */
    DZD("DZD", "Algerian Dinar", "iso-4217"),
    /** {@code USD}, US Dollar. */
    USD("USD", "US Dollar", "iso-4217"),
    /** {@code AOA}, Kwanza. */
    AOA("AOA", "Kwanza", "iso-4217"),
    /** {@code XCD}, East Caribbean Dollar. */
    XCD("XCD", "East Caribbean Dollar", "iso-4217"),
    /** {@code XAD}, Arab Accounting Dinar. */
    XAD("XAD", "Arab Accounting Dinar", "iso-4217"),
    /** {@code ARS}, Argentine Peso. */
    ARS("ARS", "Argentine Peso", "iso-4217"),
    /** {@code AMD}, Armenian Dram. */
    AMD("AMD", "Armenian Dram", "iso-4217"),
    /** {@code AWG}, Aruban Florin. */
    AWG("AWG", "Aruban Florin", "iso-4217"),
    /** {@code AUD}, Australian Dollar. */
    AUD("AUD", "Australian Dollar", "iso-4217"),
    /** {@code AZN}, Azerbaijan Manat. */
    AZN("AZN", "Azerbaijan Manat", "iso-4217"),
    /** {@code BSD}, Bahamian Dollar. */
    BSD("BSD", "Bahamian Dollar", "iso-4217"),
    /** {@code BHD}, Bahraini Dinar. */
    BHD("BHD", "Bahraini Dinar", "iso-4217"),
    /** {@code BDT}, Taka. */
    BDT("BDT", "Taka", "iso-4217"),
    /** {@code BBD}, Barbados Dollar. */
    BBD("BBD", "Barbados Dollar", "iso-4217"),
    /** {@code BYN}, Belarusian Ruble. */
    BYN("BYN", "Belarusian Ruble", "iso-4217"),
    /** {@code BZD}, Belize Dollar. */
    BZD("BZD", "Belize Dollar", "iso-4217"),
    /** {@code XOF}, CFA Franc BCEAO. */
    XOF("XOF", "CFA Franc BCEAO", "iso-4217"),
    /** {@code BMD}, Bermudian Dollar. */
    BMD("BMD", "Bermudian Dollar", "iso-4217"),
    /** {@code INR}, Indian Rupee. */
    INR("INR", "Indian Rupee", "iso-4217"),
    /** {@code BTN}, Ngultrum. */
    BTN("BTN", "Ngultrum", "iso-4217"),
    /** {@code BOB}, Boliviano. */
    BOB("BOB", "Boliviano", "iso-4217"),
    /** {@code BOV}, Mvdol. */
    BOV("BOV", "Mvdol", "iso-4217"),
    /** {@code BAM}, Convertible Mark. */
    BAM("BAM", "Convertible Mark", "iso-4217"),
    /** {@code BWP}, Pula. */
    BWP("BWP", "Pula", "iso-4217"),
    /** {@code NOK}, Norwegian Krone. */
    NOK("NOK", "Norwegian Krone", "iso-4217"),
    /** {@code BRL}, Brazilian Real. */
    BRL("BRL", "Brazilian Real", "iso-4217"),
    /** {@code BND}, Brunei Dollar. */
    BND("BND", "Brunei Dollar", "iso-4217"),
    /** {@code BIF}, Burundi Franc. */
    BIF("BIF", "Burundi Franc", "iso-4217"),
    /** {@code CVE}, Cabo Verde Escudo. */
    CVE("CVE", "Cabo Verde Escudo", "iso-4217"),
    /** {@code KHR}, Riel. */
    KHR("KHR", "Riel", "iso-4217"),
    /** {@code XAF}, CFA Franc BEAC. */
    XAF("XAF", "CFA Franc BEAC", "iso-4217"),
    /** {@code CAD}, Canadian Dollar. */
    CAD("CAD", "Canadian Dollar", "iso-4217"),
    /** {@code KYD}, Cayman Islands Dollar. */
    KYD("KYD", "Cayman Islands Dollar", "iso-4217"),
    /** {@code CLP}, Chilean Peso. */
    CLP("CLP", "Chilean Peso", "iso-4217"),
    /** {@code CLF}, Unidad de Fomento. */
    CLF("CLF", "Unidad de Fomento", "iso-4217"),
    /** {@code CNY}, Yuan Renminbi. */
    CNY("CNY", "Yuan Renminbi", "iso-4217"),
    /** {@code COP}, Colombian Peso. */
    COP("COP", "Colombian Peso", "iso-4217"),
    /** {@code COU}, Unidad de Valor Real. */
    COU("COU", "Unidad de Valor Real", "iso-4217"),
    /** {@code KMF}, Comorian Franc. */
    KMF("KMF", "Comorian Franc", "iso-4217"),
    /** {@code CDF}, Congolese Franc. */
    CDF("CDF", "Congolese Franc", "iso-4217"),
    /** {@code NZD}, New Zealand Dollar. */
    NZD("NZD", "New Zealand Dollar", "iso-4217"),
    /** {@code CRC}, Costa Rican Colon. */
    CRC("CRC", "Costa Rican Colon", "iso-4217"),
    /** {@code CUP}, Cuban Peso. */
    CUP("CUP", "Cuban Peso", "iso-4217"),
    /** {@code XCG}, Caribbean Guilder. */
    XCG("XCG", "Caribbean Guilder", "iso-4217"),
    /** {@code CZK}, Czech Koruna. */
    CZK("CZK", "Czech Koruna", "iso-4217"),
    /** {@code DKK}, Danish Krone. */
    DKK("DKK", "Danish Krone", "iso-4217"),
    /** {@code DJF}, Djibouti Franc. */
    DJF("DJF", "Djibouti Franc", "iso-4217"),
    /** {@code DOP}, Dominican Peso. */
    DOP("DOP", "Dominican Peso", "iso-4217"),
    /** {@code EGP}, Egyptian Pound. */
    EGP("EGP", "Egyptian Pound", "iso-4217"),
    /** {@code SVC}, El Salvador Colon. */
    SVC("SVC", "El Salvador Colon", "iso-4217"),
    /** {@code ERN}, Nakfa. */
    ERN("ERN", "Nakfa", "iso-4217"),
    /** {@code SZL}, Lilangeni. */
    SZL("SZL", "Lilangeni", "iso-4217"),
    /** {@code ETB}, Ethiopian Birr. */
    ETB("ETB", "Ethiopian Birr", "iso-4217"),
    /** {@code FKP}, Falkland Islands Pound. */
    FKP("FKP", "Falkland Islands Pound", "iso-4217"),
    /** {@code FJD}, Fiji Dollar. */
    FJD("FJD", "Fiji Dollar", "iso-4217"),
    /** {@code XPF}, CFP Franc. */
    XPF("XPF", "CFP Franc", "iso-4217"),
    /** {@code GMD}, Dalasi. */
    GMD("GMD", "Dalasi", "iso-4217"),
    /** {@code GEL}, Lari. */
    GEL("GEL", "Lari", "iso-4217"),
    /** {@code GHS}, Ghana Cedi. */
    GHS("GHS", "Ghana Cedi", "iso-4217"),
    /** {@code GIP}, Gibraltar Pound. */
    GIP("GIP", "Gibraltar Pound", "iso-4217"),
    /** {@code GTQ}, Quetzal. */
    GTQ("GTQ", "Quetzal", "iso-4217"),
    /** {@code GBP}, Pound Sterling. */
    GBP("GBP", "Pound Sterling", "iso-4217"),
    /** {@code GNF}, Guinean Franc. */
    GNF("GNF", "Guinean Franc", "iso-4217"),
    /** {@code GYD}, Guyana Dollar. */
    GYD("GYD", "Guyana Dollar", "iso-4217"),
    /** {@code HTG}, Gourde. */
    HTG("HTG", "Gourde", "iso-4217"),
    /** {@code HNL}, Lempira. */
    HNL("HNL", "Lempira", "iso-4217"),
    /** {@code HKD}, Hong Kong Dollar. */
    HKD("HKD", "Hong Kong Dollar", "iso-4217"),
    /** {@code HUF}, Forint. */
    HUF("HUF", "Forint", "iso-4217"),
    /** {@code ISK}, Iceland Krona. */
    ISK("ISK", "Iceland Krona", "iso-4217"),
    /** {@code IDR}, Rupiah. */
    IDR("IDR", "Rupiah", "iso-4217"),
    /** {@code XDR}, SDR (Special Drawing Right). */
    XDR("XDR", "SDR (Special Drawing Right)", "iso-4217"),
    /** {@code IRR}, Iranian Rial. */
    IRR("IRR", "Iranian Rial", "iso-4217"),
    /** {@code IQD}, Iraqi Dinar. */
    IQD("IQD", "Iraqi Dinar", "iso-4217"),
    /** {@code ILS}, New Israeli Sheqel. */
    ILS("ILS", "New Israeli Sheqel", "iso-4217"),
    /** {@code JMD}, Jamaican Dollar. */
    JMD("JMD", "Jamaican Dollar", "iso-4217"),
    /** {@code JPY}, Yen. */
    JPY("JPY", "Yen", "iso-4217"),
    /** {@code JOD}, Jordanian Dinar. */
    JOD("JOD", "Jordanian Dinar", "iso-4217"),
    /** {@code KZT}, Tenge. */
    KZT("KZT", "Tenge", "iso-4217"),
    /** {@code KES}, Kenyan Shilling. */
    KES("KES", "Kenyan Shilling", "iso-4217"),
    /** {@code KPW}, North Korean Won. */
    KPW("KPW", "North Korean Won", "iso-4217"),
    /** {@code KRW}, Won. */
    KRW("KRW", "Won", "iso-4217"),
    /** {@code KWD}, Kuwaiti Dinar. */
    KWD("KWD", "Kuwaiti Dinar", "iso-4217"),
    /** {@code KGS}, Som. */
    KGS("KGS", "Som", "iso-4217"),
    /** {@code LAK}, Lao Kip. */
    LAK("LAK", "Lao Kip", "iso-4217"),
    /** {@code LBP}, Lebanese Pound. */
    LBP("LBP", "Lebanese Pound", "iso-4217"),
    /** {@code LSL}, Loti. */
    LSL("LSL", "Loti", "iso-4217"),
    /** {@code ZAR}, Rand. */
    ZAR("ZAR", "Rand", "iso-4217"),
    /** {@code LRD}, Liberian Dollar. */
    LRD("LRD", "Liberian Dollar", "iso-4217"),
    /** {@code LYD}, Libyan Dinar. */
    LYD("LYD", "Libyan Dinar", "iso-4217"),
    /** {@code CHF}, Swiss Franc. */
    CHF("CHF", "Swiss Franc", "iso-4217"),
    /** {@code MOP}, Pataca. */
    MOP("MOP", "Pataca", "iso-4217"),
    /** {@code MKD}, Denar. */
    MKD("MKD", "Denar", "iso-4217"),
    /** {@code MGA}, Malagasy Ariary. */
    MGA("MGA", "Malagasy Ariary", "iso-4217"),
    /** {@code MWK}, Malawi Kwacha. */
    MWK("MWK", "Malawi Kwacha", "iso-4217"),
    /** {@code MYR}, Malaysian Ringgit. */
    MYR("MYR", "Malaysian Ringgit", "iso-4217"),
    /** {@code MVR}, Rufiyaa. */
    MVR("MVR", "Rufiyaa", "iso-4217"),
    /** {@code MRU}, Ouguiya. */
    MRU("MRU", "Ouguiya", "iso-4217"),
    /** {@code MUR}, Mauritius Rupee. */
    MUR("MUR", "Mauritius Rupee", "iso-4217"),
    /** {@code XUA}, ADB Unit of Account. */
    XUA("XUA", "ADB Unit of Account", "iso-4217"),
    /** {@code MXN}, Mexican Peso. */
    MXN("MXN", "Mexican Peso", "iso-4217"),
    /** {@code MXV}, Mexican Unidad de Inversion (UDI). */
    MXV("MXV", "Mexican Unidad de Inversion (UDI)", "iso-4217"),
    /** {@code MDL}, Moldovan Leu. */
    MDL("MDL", "Moldovan Leu", "iso-4217"),
    /** {@code MNT}, Tugrik. */
    MNT("MNT", "Tugrik", "iso-4217"),
    /** {@code MAD}, Moroccan Dirham. */
    MAD("MAD", "Moroccan Dirham", "iso-4217"),
    /** {@code MZN}, Mozambique Metical. */
    MZN("MZN", "Mozambique Metical", "iso-4217"),
    /** {@code MMK}, Kyat. */
    MMK("MMK", "Kyat", "iso-4217"),
    /** {@code NAD}, Namibia Dollar. */
    NAD("NAD", "Namibia Dollar", "iso-4217"),
    /** {@code NPR}, Nepalese Rupee. */
    NPR("NPR", "Nepalese Rupee", "iso-4217"),
    /** {@code NIO}, Cordoba Oro. */
    NIO("NIO", "Cordoba Oro", "iso-4217"),
    /** {@code NGN}, Naira. */
    NGN("NGN", "Naira", "iso-4217"),
    /** {@code OMR}, Rial Omani. */
    OMR("OMR", "Rial Omani", "iso-4217"),
    /** {@code PKR}, Pakistan Rupee. */
    PKR("PKR", "Pakistan Rupee", "iso-4217"),
    /** {@code PAB}, Balboa. */
    PAB("PAB", "Balboa", "iso-4217"),
    /** {@code PGK}, Kina. */
    PGK("PGK", "Kina", "iso-4217"),
    /** {@code PYG}, Guarani. */
    PYG("PYG", "Guarani", "iso-4217"),
    /** {@code PEN}, Sol. */
    PEN("PEN", "Sol", "iso-4217"),
    /** {@code PHP}, Philippine Peso. */
    PHP("PHP", "Philippine Peso", "iso-4217"),
    /** {@code PLN}, Zloty. */
    PLN("PLN", "Zloty", "iso-4217"),
    /** {@code QAR}, Qatari Rial. */
    QAR("QAR", "Qatari Rial", "iso-4217"),
    /** {@code RON}, Romanian Leu. */
    RON("RON", "Romanian Leu", "iso-4217"),
    /** {@code RUB}, Russian Ruble. */
    RUB("RUB", "Russian Ruble", "iso-4217"),
    /** {@code RWF}, Rwanda Franc. */
    RWF("RWF", "Rwanda Franc", "iso-4217"),
    /** {@code SHP}, Saint Helena Pound. */
    SHP("SHP", "Saint Helena Pound", "iso-4217"),
    /** {@code WST}, Tala. */
    WST("WST", "Tala", "iso-4217"),
    /** {@code STN}, Dobra. */
    STN("STN", "Dobra", "iso-4217"),
    /** {@code SAR}, Saudi Riyal. */
    SAR("SAR", "Saudi Riyal", "iso-4217"),
    /** {@code RSD}, Serbian Dinar. */
    RSD("RSD", "Serbian Dinar", "iso-4217"),
    /** {@code SCR}, Seychelles Rupee. */
    SCR("SCR", "Seychelles Rupee", "iso-4217"),
    /** {@code SLE}, Leone. */
    SLE("SLE", "Leone", "iso-4217"),
    /** {@code SGD}, Singapore Dollar. */
    SGD("SGD", "Singapore Dollar", "iso-4217"),
    /** {@code XSU}, Sucre. */
    XSU("XSU", "Sucre", "iso-4217"),
    /** {@code SBD}, Solomon Islands Dollar. */
    SBD("SBD", "Solomon Islands Dollar", "iso-4217"),
    /** {@code SOS}, Somali Shilling. */
    SOS("SOS", "Somali Shilling", "iso-4217"),
    /** {@code SSP}, South Sudanese Pound. */
    SSP("SSP", "South Sudanese Pound", "iso-4217"),
    /** {@code LKR}, Sri Lanka Rupee. */
    LKR("LKR", "Sri Lanka Rupee", "iso-4217"),
    /** {@code SDG}, Sudanese Pound. */
    SDG("SDG", "Sudanese Pound", "iso-4217"),
    /** {@code SRD}, Surinam Dollar. */
    SRD("SRD", "Surinam Dollar", "iso-4217"),
    /** {@code SEK}, Swedish Krona. */
    SEK("SEK", "Swedish Krona", "iso-4217"),
    /** {@code CHE}, WIR Euro. */
    CHE("CHE", "WIR Euro", "iso-4217"),
    /** {@code CHW}, WIR Franc. */
    CHW("CHW", "WIR Franc", "iso-4217"),
    /** {@code SYP}, Syrian Pound. */
    SYP("SYP", "Syrian Pound", "iso-4217"),
    /** {@code TWD}, New Taiwan Dollar. */
    TWD("TWD", "New Taiwan Dollar", "iso-4217"),
    /** {@code TJS}, Somoni. */
    TJS("TJS", "Somoni", "iso-4217"),
    /** {@code TZS}, Tanzanian Shilling. */
    TZS("TZS", "Tanzanian Shilling", "iso-4217"),
    /** {@code THB}, Baht. */
    THB("THB", "Baht", "iso-4217"),
    /** {@code TOP}, Pa’anga. */
    TOP("TOP", "Pa’anga", "iso-4217"),
    /** {@code TTD}, Trinidad and Tobago Dollar. */
    TTD("TTD", "Trinidad and Tobago Dollar", "iso-4217"),
    /** {@code TND}, Tunisian Dinar. */
    TND("TND", "Tunisian Dinar", "iso-4217"),
    /** {@code TRY}, Turkish Lira. */
    TRY("TRY", "Turkish Lira", "iso-4217"),
    /** {@code TMT}, Turkmenistan New Manat. */
    TMT("TMT", "Turkmenistan New Manat", "iso-4217"),
    /** {@code UGX}, Uganda Shilling. */
    UGX("UGX", "Uganda Shilling", "iso-4217"),
    /** {@code UAH}, Hryvnia. */
    UAH("UAH", "Hryvnia", "iso-4217"),
    /** {@code AED}, UAE Dirham. */
    AED("AED", "UAE Dirham", "iso-4217"),
    /** {@code USN}, US Dollar (Next day). */
    USN("USN", "US Dollar (Next day)", "iso-4217"),
    /** {@code UYU}, Peso Uruguayo. */
    UYU("UYU", "Peso Uruguayo", "iso-4217"),
    /** {@code UYI}, Uruguay Peso en Unidades Indexadas (UI). */
    UYI("UYI", "Uruguay Peso en Unidades Indexadas (UI)", "iso-4217"),
    /** {@code UYW}, Unidad Previsional. */
    UYW("UYW", "Unidad Previsional", "iso-4217"),
    /** {@code UZS}, Uzbekistan Sum. */
    UZS("UZS", "Uzbekistan Sum", "iso-4217"),
    /** {@code VUV}, Vatu. */
    VUV("VUV", "Vatu", "iso-4217"),
    /** {@code VES}, Bolívar Soberano. */
    VES("VES", "Bolívar Soberano", "iso-4217"),
    /** {@code VED}, Bolívar Soberano. */
    VED("VED", "Bolívar Soberano", "iso-4217"),
    /** {@code VND}, Dong. */
    VND("VND", "Dong", "iso-4217"),
    /** {@code YER}, Yemeni Rial. */
    YER("YER", "Yemeni Rial", "iso-4217"),
    /** {@code ZMW}, Zambian Kwacha. */
    ZMW("ZMW", "Zambian Kwacha", "iso-4217"),
    /** {@code ZWG}, Zimbabwe Gold. */
    ZWG("ZWG", "Zimbabwe Gold", "iso-4217"),
    /** {@code XBA}, Bond Markets Unit European Composite Unit (EURCO). */
    XBA("XBA", "Bond Markets Unit European Composite Unit (EURCO)", "iso-4217"),
    /** {@code XBB}, Bond Markets Unit European Monetary Unit (E.M.U.-6). */
    XBB("XBB", "Bond Markets Unit European Monetary Unit (E.M.U.-6)", "iso-4217"),
    /** {@code XBC}, Bond Markets Unit European Unit of Account 9 (E.U.A.-9). */
    XBC("XBC", "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", "iso-4217"),
    /** {@code XBD}, Bond Markets Unit European Unit of Account 17 (E.U.A.-17). */
    XBD("XBD", "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", "iso-4217"),
    /** {@code XTS}, Codes specifically reserved for testing purposes. */
    XTS("XTS", "Codes specifically reserved for testing purposes", "iso-4217"),
    /** {@code XXX}, The codes assigned for transactions where no currency is involved. */
    XXX("XXX", "The codes assigned for transactions where no currency is involved", "iso-4217"),
    /** {@code XAU}, Gold. */
    XAU("XAU", "Gold", "iso-4217"),
    /** {@code XPD}, Palladium. */
    XPD("XPD", "Palladium", "iso-4217"),
    /** {@code XPT}, Platinum. */
    XPT("XPT", "Platinum", "iso-4217"),
    /** {@code XAG}, Silver. */
    XAG("XAG", "Silver", "iso-4217");

    private static final Map<String, CurrencyCode> BY_CODE = byCode();

    private final String code;

    private final String publishedName;

    private final String listId;

    CurrencyCode(String code, String publishedName, String listId) {
        this.code = code;
        this.publishedName = publishedName;
        this.listId = listId;
    }

    /**
     * Returns the constant carrying a code.
     *
     * <p>The comparison is exact, code point by code point: a code list is a list of
     * codes and not of their spellings.
     *
     * @param code the code
     * @return the constant
     * @throws IllegalArgumentException if the snapshot does not carry the code
     * @throws NullPointerException     if {@code code} is {@code null}
     */
    public static CurrencyCode of(String code) {
        CurrencyCode value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        if (value == null) {
            throw new IllegalArgumentException("the snapshot of CurrencyCode does not carry the code "
                    + code + "; CurrencyCode.custom(code) represents a code it does not have");
        }
        return value;
    }

    /**
     * Returns the constant carrying a code, or a custom code where there is none.
     *
     * @param code the code as a document carries it
     * @return the constant or a {@link CustomCode}
     * @throws NullPointerException     if {@code code} is {@code null}
     * @throws IllegalArgumentException if the code is blank
     */
    public static Coded resolve(String code) {
        CurrencyCode value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        return value != null ? value : new CustomCode("CurrencyCode", code);
    }

    /**
     * Returns a code the snapshot does not carry.
     *
     * @param code the code
     * @return the custom code
     * @throws IllegalArgumentException if the snapshot carries the code, which has a
     *                                  constant and must not have a second representation,
     *                                  or if the code is blank
     * @throws NullPointerException     if {@code code} is {@code null}
     */
    public static Coded custom(String code) {
        CurrencyCode value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        if (value != null) {
            throw new IllegalArgumentException("the snapshot of CurrencyCode carries the code "
                    + code + " as " + value.name());
        }
        return new CustomCode("CurrencyCode", code);
    }

    /**
     * Returns the code as it is written into the document.
     *
     * @return the code
     */
    @Override
    public String code() {
        return code;
    }

    /**
     * Returns the name the publisher of the list gives the code.
     *
     * @return the name, empty where the publisher gives none
     */
    @Override
    public String publishedName() {
        return publishedName;
    }

    /**
     * Returns the identifier of the code list the constant came from.
     *
     * @return the list identifier, for example {@code iso-4217}
     */
    @Override
    public String listId() {
        return listId;
    }

    private static Map<String, CurrencyCode> byCode() {
        Map<String, CurrencyCode> byCode = new LinkedHashMap<>();
        for (CurrencyCode value : values()) {
            byCode.put(value.code, value);
        }
        return Map.copyOf(byCode);
    }
}
