// Generated by esj-generator from the code list snapshots
// of the rule pack en16931 1.3.16: untdid-1001 of 2026-09-19.
// Do not edit.
package de.bsnsoft.esj.invoice.code;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Functional type of the document.
 *
 * <p>UNTDID 1001 document name code, as admitted by EN 16931. UN/CEFACT (UNTDID), listed for EN
 * 16931 by the European Commission, snapshot of 2026-09-19, 62 codes.
 *
 * <p>The registry names this list at BT-3.
 *
 * <p>A code the snapshot does not carry is representable: {@code InvoiceType.custom(code)} yields a
 * {@link CustomCode}, and {@code resolve(code)} yields the constant where there is one and a {@code
 * CustomCode} where there is none. Whether a code is admissible is decided by the rule pack and not
 * here.
 */
public enum InvoiceType implements Coded {

    /** {@code 71}, Request for payment. */
    REQUEST_FOR_PAYMENT("71", "Request for payment", "untdid-1001"),
    /** {@code 80}, Debit note related to goods or services. */
    DEBIT_NOTE_RELATED_TO_GOODS_OR_SERVICES("80", "Debit note related to goods or services", "untdid-1001"),
    /** {@code 81}, Credit note related to goods or services. */
    CREDIT_NOTE_RELATED_TO_GOODS_OR_SERVICES("81", "Credit note related to goods or services", "untdid-1001"),
    /** {@code 82}, Metered services invoice. */
    METERED_SERVICES_INVOICE("82", "Metered services invoice", "untdid-1001"),
    /** {@code 83}, Credit note related to financial adjustments. */
    CREDIT_NOTE_RELATED_TO_FINANCIAL_ADJUSTMENTS("83", "Credit note related to financial adjustments", "untdid-1001"),
    /** {@code 84}, Debit note related to financial adjustments. */
    DEBIT_NOTE_RELATED_TO_FINANCIAL_ADJUSTMENTS("84", "Debit note related to financial adjustments", "untdid-1001"),
    /** {@code 102}, Tax notification. */
    TAX_NOTIFICATION("102", "Tax notification", "untdid-1001"),
    /** {@code 130}, Invoicing data sheet. */
    INVOICING_DATA_SHEET("130", "Invoicing data sheet", "untdid-1001"),
    /** {@code 202}, Direct payment valuation. */
    DIRECT_PAYMENT_VALUATION("202", "Direct payment valuation", "untdid-1001"),
    /** {@code 203}, Provisional payment valuation. */
    PROVISIONAL_PAYMENT_VALUATION("203", "Provisional payment valuation", "untdid-1001"),
    /** {@code 204}, Payment valuation. */
    PAYMENT_VALUATION("204", "Payment valuation", "untdid-1001"),
    /** {@code 211}, Interim application for payment. */
    INTERIM_APPLICATION_FOR_PAYMENT("211", "Interim application for payment", "untdid-1001"),
    /** {@code 218}, Final payment request based on completion of work. */
    FINAL_PAYMENT_REQUEST_BASED_ON_COMPLETION_OF_WORK("218", "Final payment request based on completion of work", "untdid-1001"),
    /** {@code 219}, Payment request for completed units. */
    PAYMENT_REQUEST_FOR_COMPLETED_UNITS("219", "Payment request for completed units", "untdid-1001"),
    /** {@code 261}, Self billed credit note. */
    SELF_BILLED_CREDIT_NOTE("261", "Self billed credit note", "untdid-1001"),
    /** {@code 262}, Consolidated credit note - goods and services. */
    CONSOLIDATED_CREDIT_NOTE_GOODS_AND_SERVICES("262", "Consolidated credit note - goods and services", "untdid-1001"),
    /** {@code 295}, Price variation invoice. */
    PRICE_VARIATION_INVOICE("295", "Price variation invoice", "untdid-1001"),
    /** {@code 296}, Credit note for price variation. */
    CREDIT_NOTE_FOR_PRICE_VARIATION("296", "Credit note for price variation", "untdid-1001"),
    /** {@code 308}, Delcredere credit note. */
    DELCREDERE_CREDIT_NOTE("308", "Delcredere credit note", "untdid-1001"),
    /** {@code 325}, Proforma invoice. */
    PROFORMA_INVOICE("325", "Proforma invoice", "untdid-1001"),
    /** {@code 326}, Partial invoice. */
    PARTIAL_INVOICE("326", "Partial invoice", "untdid-1001"),
    /** {@code 331}, Commercial invoice which includes a packing list. */
    COMMERCIAL_INVOICE_WHICH_INCLUDES_A_PACKING_LIST("331", "Commercial invoice which includes a packing list", "untdid-1001"),
    /** {@code 380}, Commercial invoice. */
    COMMERCIAL_INVOICE("380", "Commercial invoice", "untdid-1001"),
    /** {@code 381}, Credit note. */
    CREDIT_NOTE("381", "Credit note", "untdid-1001"),
    /** {@code 382}, Commission note. */
    COMMISSION_NOTE("382", "Commission note", "untdid-1001"),
    /** {@code 383}, Debit note. */
    DEBIT_NOTE("383", "Debit note", "untdid-1001"),
    /** {@code 384}, Corrected invoice. */
    CORRECTED_INVOICE("384", "Corrected invoice", "untdid-1001"),
    /** {@code 385}, Consolidated invoice. */
    CONSOLIDATED_INVOICE("385", "Consolidated invoice", "untdid-1001"),
    /** {@code 386}, Prepayment invoice. */
    PREPAYMENT_INVOICE("386", "Prepayment invoice", "untdid-1001"),
    /** {@code 387}, Hire invoice. */
    HIRE_INVOICE("387", "Hire invoice", "untdid-1001"),
    /** {@code 388}, Tax invoice. */
    TAX_INVOICE("388", "Tax invoice", "untdid-1001"),
    /** {@code 389}, Self-billed invoice. */
    SELF_BILLED_INVOICE("389", "Self-billed invoice", "untdid-1001"),
    /** {@code 390}, Delcredere invoice. */
    DELCREDERE_INVOICE("390", "Delcredere invoice", "untdid-1001"),
    /** {@code 393}, Factored invoice. */
    FACTORED_INVOICE("393", "Factored invoice", "untdid-1001"),
    /** {@code 394}, Lease invoice. */
    LEASE_INVOICE("394", "Lease invoice", "untdid-1001"),
    /** {@code 395}, Consignment invoice. */
    CONSIGNMENT_INVOICE("395", "Consignment invoice", "untdid-1001"),
    /** {@code 396}, Factored credit note. */
    FACTORED_CREDIT_NOTE("396", "Factored credit note", "untdid-1001"),
    /** {@code 420}, Optical Character Reading (OCR) payment credit note. */
    OPTICAL_CHARACTER_READING_OCR_PAYMENT_CREDIT_NOTE("420", "Optical Character Reading (OCR) payment credit note", "untdid-1001"),
    /** {@code 456}, Debit advice. */
    DEBIT_ADVICE("456", "Debit advice", "untdid-1001"),
    /** {@code 457}, Reversal of debit. */
    REVERSAL_OF_DEBIT("457", "Reversal of debit", "untdid-1001"),
    /** {@code 458}, Reversal of credit. */
    REVERSAL_OF_CREDIT("458", "Reversal of credit", "untdid-1001"),
    /** {@code 471}, Self-billed corrective invoice, invoice type, Corrected. */
    SELF_BILLED_CORRECTIVE_INVOICE_INVOICE_TYPE_CORRECTED("471", "Self-billed corrective invoice, invoice type, Corrected", "untdid-1001"),
    /** {@code 472}, Factored Corrective Invoice, invoice type, Corrected. */
    FACTORED_CORRECTIVE_INVOICE_INVOICE_TYPE_CORRECTED("472", "Factored Corrective Invoice, invoice type, Corrected", "untdid-1001"),
    /** {@code 473}, Self billed Factored corrective invoice, invoice type, Corrected. */
    SELF_BILLED_FACTORED_CORRECTIVE_INVOICE_INVOICE_TYPE("473", "Self billed Factored corrective invoice, invoice type, Corrected", "untdid-1001"),
    /** {@code 500}, Self Prepayment invoice, invoice type, Original. */
    SELF_PREPAYMENT_INVOICE_INVOICE_TYPE_ORIGINAL("500", "Self Prepayment invoice, invoice type, Original", "untdid-1001"),
    /** {@code 501}, Self billed factored invoice, invoice type, Original. */
    SELF_BILLED_FACTORED_INVOICE_INVOICE_TYPE_ORIGINAL("501", "Self billed factored invoice, invoice type, Original", "untdid-1001"),
    /** {@code 502}, Self billet factored Credit Note, Credit note type, Corrected. */
    SELF_BILLET_FACTORED_CREDIT_NOTE_CREDIT_NOTE_TYPE_CORRECTED("502", "Self billet factored Credit Note, Credit note type, Corrected", "untdid-1001"),
    /** {@code 503}, Prepayment credit note, credit note type, Corrected. */
    PREPAYMENT_CREDIT_NOTE_CREDIT_NOTE_TYPE_CORRECTED("503", "Prepayment credit note, credit note type, Corrected", "untdid-1001"),
    /** {@code 527}, Self billed debit note. */
    SELF_BILLED_DEBIT_NOTE("527", "Self billed debit note", "untdid-1001"),
    /** {@code 532}, Forwarder's credit note. */
    FORWARDER_S_CREDIT_NOTE("532", "Forwarder's credit note", "untdid-1001"),
    /** {@code 553}, Forwarder's invoice discrepancy report. */
    FORWARDER_S_INVOICE_DISCREPANCY_REPORT("553", "Forwarder's invoice discrepancy report", "untdid-1001"),
    /** {@code 575}, Insurer's invoice. */
    INSURER_S_INVOICE("575", "Insurer's invoice", "untdid-1001"),
    /** {@code 623}, Forwarder's invoice. */
    FORWARDER_S_INVOICE("623", "Forwarder's invoice", "untdid-1001"),
    /** {@code 633}, Port charges documents. */
    PORT_CHARGES_DOCUMENTS("633", "Port charges documents", "untdid-1001"),
    /** {@code 751}, Invoice information for accounting purposes. */
    INVOICE_INFORMATION_FOR_ACCOUNTING_PURPOSES("751", "Invoice information for accounting purposes", "untdid-1001"),
    /** {@code 780}, Freight invoice. */
    FREIGHT_INVOICE("780", "Freight invoice", "untdid-1001"),
    /** {@code 817}, Claim notification. */
    CLAIM_NOTIFICATION("817", "Claim notification", "untdid-1001"),
    /** {@code 870}, Consular invoice. */
    CONSULAR_INVOICE("870", "Consular invoice", "untdid-1001"),
    /** {@code 875}, Partial construction invoice. */
    PARTIAL_CONSTRUCTION_INVOICE("875", "Partial construction invoice", "untdid-1001"),
    /** {@code 876}, Partial final construction invoice. */
    PARTIAL_FINAL_CONSTRUCTION_INVOICE("876", "Partial final construction invoice", "untdid-1001"),
    /** {@code 877}, Final construction invoice. */
    FINAL_CONSTRUCTION_INVOICE("877", "Final construction invoice", "untdid-1001"),
    /** {@code 935}, Customs invoice. */
    CUSTOMS_INVOICE("935", "Customs invoice", "untdid-1001");

    private static final Map<String, InvoiceType> BY_CODE = byCode();

    private final String code;

    private final String publishedName;

    private final String listId;

    InvoiceType(String code, String publishedName, String listId) {
        this.code = code;
        this.publishedName = publishedName;
        this.listId = listId;
    }

    /**
     * Returns the constant carrying a code.
     *
     * <p>The comparison is exact, code point by code point: a code list is a list of
     * codes and not of their spellings.
     *
     * @param code the code
     * @return the constant
     * @throws IllegalArgumentException if the snapshot does not carry the code
     * @throws NullPointerException     if {@code code} is {@code null}
     */
    public static InvoiceType of(String code) {
        InvoiceType value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        if (value == null) {
            throw new IllegalArgumentException("the snapshot of InvoiceType does not carry the code "
                    + code + "; InvoiceType.custom(code) represents a code it does not have");
        }
        return value;
    }

    /**
     * Returns the constant carrying a code, or a custom code where there is none.
     *
     * @param code the code as a document carries it
     * @return the constant or a {@link CustomCode}
     * @throws NullPointerException     if {@code code} is {@code null}
     * @throws IllegalArgumentException if the code is blank
     */
    public static Coded resolve(String code) {
        InvoiceType value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        return value != null ? value : new CustomCode("InvoiceType", code);
    }

    /**
     * Returns a code the snapshot does not carry.
     *
     * @param code the code
     * @return the custom code
     * @throws IllegalArgumentException if the snapshot carries the code, which has a
     *                                  constant and must not have a second representation,
     *                                  or if the code is blank
     * @throws NullPointerException     if {@code code} is {@code null}
     */
    public static Coded custom(String code) {
        InvoiceType value = BY_CODE.get(Objects.requireNonNull(code, "code"));
        if (value != null) {
            throw new IllegalArgumentException("the snapshot of InvoiceType carries the code "
                    + code + " as " + value.name());
        }
        return new CustomCode("InvoiceType", code);
    }

    /**
     * Returns the code as it is written into the document.
     *
     * @return the code
     */
    @Override
    public String code() {
        return code;
    }

    /**
     * Returns the name the publisher of the list gives the code.
     *
     * @return the name, empty where the publisher gives none
     */
    @Override
    public String publishedName() {
        return publishedName;
    }

    /**
     * Returns the identifier of the code list the constant came from.
     *
     * @return the list identifier, for example {@code untdid-1001}
     */
    @Override
    public String listId() {
        return listId;
    }

    private static Map<String, InvoiceType> byCode() {
        Map<String, InvoiceType> byCode = new LinkedHashMap<>();
        for (InvoiceType value : values()) {
            byCode.put(value.code, value);
        }
        return Map.copyOf(byCode);
    }
}
