// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020 with ESJ-B2C 0.1, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.b2c;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.model.Registry;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

/**
 * Reads the terms of ESJ-B2C 0.1 that lie at the root of a document.
 *
 * <p>An overlay over the same document the typed view of the core model reads, carrying the terms
 * of the extension and nothing else. Nothing is copied and nothing is resolved before it is asked
 * for.
 */
public interface B2cInvoice {

    /**
     * Returns the document this overlay reads.
     *
     * @return the document the overlay was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the root of the document, which has no segments.
     *
     * @return the path every value of this overlay lies under
     */
    SemanticPath path();

    /**
     * Returns the registry of the core model with this extension loaded, so that a caller holding
     * an overlay has what a structural validator needs to check the paths of the extension.
     *
     * @return the combined registry, the one {@link B2c#registry()} hands over
     */
    default Registry registry() {
        return B2c.registry();
    }

    /**
     * The way down to the terms of ESJ-B2C 0.1 that lie inside BG-25 INVOICE LINE, a business group
     * of the core model this overlay shows nothing else of.
     *
     * <p>Declared cardinality 1..n. The core terms of the group are read and written through the
     * typed view of the core model, at the same path.
     *
     * @return one overlay per instance of BG-25 at the root of the document, in the order of their
     *     occurrence indices and aligned with the instances the typed view of the core model shows,
     *     empty where the document has none
     */
    List<B2cInvoiceLine> lines();

    /**
     * BT-B2C-010 Displayed invoice gross total. The total of the invoice with VAT included, as it
     * was shown to or agreed with the customer; the term is present only where such a figure was
     * part of the price statement, and this registry defines no arithmetic relation between it and
     * any other term.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount. A term of ESJ-B2C 0.1, which is no
     * part of EN 16931-1.
     *
     * @return the value of BT-B2C-010 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> displayedGrossTotal();
}
