// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020 with ESJ-B2C 0.1, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.b2c;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;

/** Writes {@link B2cInvoiceEditor} into a document builder. */
final class B2cInvoiceEdit implements B2cInvoiceEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    B2cInvoiceEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public List<B2cInvoiceLineEditor> lines() {
        return Overlays.editors(builder, path, "BG-25", B2cInvoiceLineEdit::new);
    }

    @Override
    public B2cInvoiceEditor line(int index, Consumer<B2cInvoiceLineEditor> block) {
        Objects.requireNonNull(block, "block").accept(Overlays.at(lines(), index, "BG-25"));
        return this;
    }

    @Override
    public B2cInvoiceEditor displayedGrossTotal(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-B2C-010"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public String toString() {
        return "B2cInvoiceEditor[" + path + "]";
    }
}
