// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020 with ESJ-B2C 0.1, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.b2c;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.math.BigDecimal;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link B2cInvoiceLine} from a semantic document. */
final class B2cInvoiceLineView implements B2cInvoiceLine {

    private final SemanticDocument document;
    private final SemanticPath path;

    B2cInvoiceLineView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public Optional<BigDecimal> displayedGrossUnitPrice() {
        return Views.optional(document, TermPaths.value(path, "BT-B2C-001"), Values.UNIT_PRICE_AMOUNT);
    }

    @Override
    public Optional<BigDecimal> displayedGrossLineTotal() {
        return Views.optional(document, TermPaths.value(path, "BT-B2C-002"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> displayedLineVatAmount() {
        return Views.optional(document, TermPaths.value(path, "BT-B2C-003"), Values.AMOUNT);
    }

    @Override
    public String toString() {
        return "B2cInvoiceLine[" + path + "]";
    }
}
