// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020 with ESJ-B2C 0.1, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.b2c;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.util.Objects;

/** Writes {@link B2cInvoiceLineEditor} into a document builder. */
final class B2cInvoiceLineEdit implements B2cInvoiceLineEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    B2cInvoiceLineEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public B2cInvoiceLineEditor displayedGrossUnitPrice(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-B2C-001"), value, Writers.UNIT_PRICE_AMOUNT);
        return this;
    }

    @Override
    public B2cInvoiceLineEditor displayedGrossLineTotal(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-B2C-002"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public B2cInvoiceLineEditor displayedLineVatAmount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-B2C-003"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public String toString() {
        return "B2cInvoiceLineEditor[" + path + "]";
    }
}
