// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020 with ESJ-B2C 0.1, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.b2c;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.model.Registry;
import java.math.BigDecimal;
import java.util.List;
import java.util.function.Consumer;

/**
 * Writes the terms of ESJ-B2C 0.1 that lie at the root of a document.
 *
 * <p>An overlay over the same document builder the typed editor of the core model writes into,
 * carrying the terms of the extension and nothing else. Setting null or an empty string removes the
 * value, exactly as in the core editor. A group comes into being when a value is written into it
 * (specification, section 4.5); this overlay appends no instance of a core group and removes none.
 */
public interface B2cInvoiceEditor {

    /**
     * Returns the builder this overlay writes into, which is the builder the typed editor of the
     * core model writes into as well.
     *
     * @return the builder the overlay was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the root of the document, which has no segments.
     *
     * @return the path every value of this overlay lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this overlay and into every other
     *     editor of the same builder, in canonical path order
     */
    SemanticDocument document();

    /**
     * Returns the registry of the core model with this extension loaded, so that a caller holding
     * an overlay has what a structural validator needs to check the paths of the extension.
     *
     * @return the combined registry, the one {@link B2c#registry()} hands over
     */
    default Registry registry() {
        return B2c.registry();
    }

    /**
     * The way down to the terms of ESJ-B2C 0.1 that lie inside BG-25 INVOICE LINE, a business group
     * of the core model this overlay shows nothing else of.
     *
     * <p>Declared cardinality 1..n. The core terms of the group are read and written through the
     * typed view of the core model, at the same path.
     *
     * <p>The overlay writes into the instances of BG-25 the document already carries and appends
     * none: how many there are is decided by the core model, and the typed editor of the core model
     * is what appends one.
     *
     * @return one editor per instance of BG-25 at the root of the document, in the order of their
     *     occurrence indices, empty where the document carries none
     */
    List<B2cInvoiceLineEditor> lines();

    /**
     * The way down to the terms of ESJ-B2C 0.1 that lie inside BG-25 INVOICE LINE, a business group
     * of the core model this overlay shows nothing else of.
     *
     * <p>Declared cardinality 1..n. The core terms of the group are read and written through the
     * typed view of the core model, at the same path.
     *
     * <p>The overlay writes into the instances of BG-25 the document already carries and appends
     * none: how many there are is decided by the core model, and the typed editor of the core model
     * is what appends one.
     *
     * @param index the zero-based occurrence index of the instance of BG-25 to write into
     * @param block what to write into that instance
     * @return this editor
     * @throws IndexOutOfBoundsException if the document carries no instance of BG-25 at that index
     * @throws NullPointerException if {@code block} is {@code null}
     */
    B2cInvoiceEditor line(int index, Consumer<B2cInvoiceLineEditor> block);

    /**
     * BT-B2C-010 Displayed invoice gross total. The total of the invoice with VAT included, as it
     * was shown to or agreed with the customer; the term is present only where such a figure was
     * part of the price statement, and this registry defines no arithmetic relation between it and
     * any other term.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount. A term of ESJ-B2C 0.1, which is no
     * part of EN 16931-1.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    B2cInvoiceEditor displayedGrossTotal(BigDecimal value);
}
