/**
 * The overlay of the B2C extension: a view and an editor that show the four terms of
 * {@code model/b2c/0.1.json} — the gross unit price, the gross line total, the line VAT
 * amount and the gross invoice total a consumer was shown or agreed to — and nothing else.
 *
 * <p>The typed view of {@code de.bsnsoft.esj.typed} is generated from the core
 * registry alone and stays that way: adopting this extension does not change the API of the
 * core model. An overlay is the other half of that decision. It is a second, small API over
 * the same document, and every one of its accessors lies on a path the core model already
 * defines, so {@link de.bsnsoft.esj.b2c.B2c#of} and
 * {@code En16931.view} read one document side by side and
 * {@link de.bsnsoft.esj.b2c.B2c#edit} and {@code En16931.newInvoice} write into
 * one builder.
 *
 * <p>{@link de.bsnsoft.esj.b2c.B2cInvoice#lines} hands over one overlay per
 * invoice line the document carries, in the order of the occurrence indices, so the overlay
 * of a line and the typed view of the same line stand at the same position of both lists.
 * The overlay appends no invoice line and removes none: how many lines an invoice has is
 * decided by the core model.
 *
 * <p>The extension states facts and no arithmetic. A term of it records that a figure was
 * part of the price statement a customer saw or agreed to; its absence records that nothing
 * was shown at that level. The registry declares no relation between one of these figures
 * and another, and none between one of them and a business term of EN 16931-1, whose terms
 * keep their meaning — BT-114 among them, which stays the invoice rounding amount. Deriving
 * one figure from another is the business of a policy that says what it assumes and reports
 * what it did, not of this overlay, which reads and writes what it is given.
 *
 * <p>Those policies are the second half of this package, and they are hand-written.
 * {@link de.bsnsoft.esj.b2c.Gross} writes the figures and runs one of the three
 * of {@link de.bsnsoft.esj.b2c.GrossAuthoring} over them; each derives the net
 * core terms, runs the derivation of EN 16931-1 for the line amounts, the VAT breakdown and
 * the totals, sets the invoice rounding amount where the invoice states a gross total that
 * was agreed, and hands back an {@link de.bsnsoft.esj.b2c.AuthoringReport}.
 * {@link de.bsnsoft.esj.b2c.B2cConsistency} checks afterwards that the guarantee
 * of the named policy holds, and {@link de.bsnsoft.esj.b2c.GrossInvoice} is the
 * same thing in the words of the domain API. A policy writes no term of the extension: what
 * was shown to the customer is the caller's statement, not a computation.
 *
 * <p>Neither the view nor the editor validates.
 * {@link de.bsnsoft.esj.b2c.B2c#registry()} hands over the core registry with
 * this extension loaded, which is what
 * {@code de.bsnsoft.esj.validate.StructuralValidator} has to be given for the
 * paths of the extension to be checked instead of reported as not checked (specification,
 * section 5.6).
 *
 * <p>The types of this package are generated by {@code esj-generator} from
 * {@code model/b2c/0.1.json} and are checked in. The two package-private classes that carry
 * them out are not generated.
 */
package de.bsnsoft.esj.b2c;
