// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.BinaryObject;
import de.bsnsoft.esj.typed.MissingValueException;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.util.Optional;

/**
 * BG-24 ADDITIONAL SUPPORTING DOCUMENTS. Group referencing a supporting document that backs the
 * claims made in the invoice.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface AdditionalSupportingDocument {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-122 Supporting document reference. Reference that identifies the supporting document.
     *
     * <p>Declared cardinality 1..1, semantic data type DocumentReference.
     *
     * @return the value of BT-122 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String reference();

    /**
     * BT-123 Supporting document description. Textual description of the supporting document.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-123 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> description();

    /**
     * BT-124 External document location. Internet address where the external supporting document
     * can be retrieved.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-124 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> externalLocation();

    /**
     * BT-125 Attached document. Supporting document embedded in the invoice as a binary object,
     * with mime code and file name.
     *
     * <p>Declared cardinality 0..1, semantic data type BinaryObject.
     *
     * @return the value of BT-125 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BinaryObject> attachment();
}
