// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.Objects;

/** Writes {@link BuyerPostalAddressEditor} into a document builder. */
final class BuyerPostalAddressEdit implements BuyerPostalAddressEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    BuyerPostalAddressEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public BuyerPostalAddressEditor addressLine1(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-50"), value, Writers.TEXT);
        return this;
    }

    @Override
    public BuyerPostalAddressEditor addressLine2(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-51"), value, Writers.TEXT);
        return this;
    }

    @Override
    public BuyerPostalAddressEditor addressLine3(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-163"), value, Writers.TEXT);
        return this;
    }

    @Override
    public BuyerPostalAddressEditor city(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-52"), value, Writers.TEXT);
        return this;
    }

    @Override
    public BuyerPostalAddressEditor postCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-53"), value, Writers.TEXT);
        return this;
    }

    @Override
    public BuyerPostalAddressEditor countrySubdivision(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-54"), value, Writers.TEXT);
        return this;
    }

    @Override
    public BuyerPostalAddressEditor countryCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-55"), value, Writers.CODE);
        return this;
    }

    @Override
    public String toString() {
        return "BuyerPostalAddressEditor[" + path + "]";
    }
}
