// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link BuyerContact} from a semantic document. */
final class BuyerContactView implements BuyerContact {

    private final SemanticDocument document;
    private final SemanticPath path;

    BuyerContactView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public Optional<String> name() {
        return Views.optional(document, TermPaths.value(path, "BT-56"), Values.TEXT);
    }

    @Override
    public Optional<String> telephone() {
        return Views.optional(document, TermPaths.value(path, "BT-57"), Values.TEXT);
    }

    @Override
    public Optional<String> email() {
        return Views.optional(document, TermPaths.value(path, "BT-58"), Values.TEXT);
    }

    @Override
    public String toString() {
        return "BuyerContact[" + path + "]";
    }
}
