// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;

/**
 * BG-28 INVOICE LINE CHARGES AND TAXES. Group for charges and non-VAT taxes that apply to a single
 * invoice line.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code ChargeEditor} checks a value against the grammar of its semantic data type
 * and nothing else.
 */
public interface ChargeEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-141 Invoice line charge or tax amount. Amount of a charge or non-VAT tax on the invoice
     * line, without VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    ChargeEditor amount(BigDecimal value);

    /**
     * BT-142 Invoice line charge or tax base amount. Base amount the invoice line charge or tax
     * percentage is applied to.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    ChargeEditor baseAmount(BigDecimal value);

    /**
     * BT-143 Invoice line charge or tax percentage. The percentage that the base amount of BG-28 is
     * multiplied by to reach its charge or tax amount.
     *
     * <p>Declared cardinality 0..1, semantic data type Percentage.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    ChargeEditor percentage(BigDecimal value);

    /**
     * BT-144 Invoice line charge or tax reason. Reason for the invoice line charge or tax, as text.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    ChargeEditor reason(String value);

    /**
     * BT-145 Invoice line charge reason code. Coded reason for the invoice line charge, from UNTDID
     * 7161.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    ChargeEditor reasonCode(String value);

    /**
     * BT-193 Invoice line-level non-VAT tax type code. Code naming which non-VAT tax is levied on
     * the invoice line.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    ChargeEditor nonVatTaxTypeCode(String value);
}
