// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.MissingValueException;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.util.Optional;

/**
 * BG-15 DELIVER TO ADDRESS. Group carrying the address the goods or services are delivered to.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface DeliveryAddress {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-75 Deliver to address line 1. First line of the deliver-to address.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-75 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> addressLine1();

    /**
     * BT-76 Deliver to address line 2. Second line of the deliver-to address.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-76 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> addressLine2();

    /**
     * BT-165 Deliver to address line 3. Third line of the deliver-to address.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-165 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> addressLine3();

    /**
     * BT-77 Deliver to city. Town or city of the deliver-to address.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-77 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> city();

    /**
     * BT-78 Deliver to post code. Postal code of the deliver-to address.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-78 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> postCode();

    /**
     * BT-79 Deliver to country subdivision. Country subdivision of the deliver-to address.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-79 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> countrySubdivision();

    /**
     * BT-80 Deliver to country code. Country code of the deliver-to address, from ISO 3166-1
     * alpha-2.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @return the value of BT-80 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String countryCode();
}
