// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.time.LocalDate;
import java.util.function.Consumer;

/**
 * BG-13 DELIVERY INFORMATION. Group saying where and when the invoiced goods or services were
 * delivered.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code DeliveryEditor} checks a value against the grammar of its semantic data
 * type and nothing else.
 */
public interface DeliveryEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-70 Deliver to party name. Name of the party the goods or services are delivered to, where
     * different from the buyer.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    DeliveryEditor partyName(String value);

    /**
     * BT-71 Deliver to location identifier. Identifier of the delivery location, with an
     * identification scheme identifier.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value
     * @param scheme the identification scheme, a code of the ISO 6523 ICD list
     * @return this editor
     */
    DeliveryEditor locationIdentifier(String value, String scheme);

    /**
     * BT-71 Deliver to location identifier. Identifier of the delivery location, with an
     * identification scheme identifier.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value. The registry declares the
     *     scheme of BT-71 mandatory, and this overload writes the identifier as it stands: one that
     *     carries no scheme is written and reported at validation layer L2, not refused here
     * @return this editor
     */
    DeliveryEditor locationIdentifier(Identifier value);

    /**
     * BT-72 Actual delivery date. Date on which the goods or services were actually delivered or
     * completed.
     *
     * <p>Declared cardinality 0..1, semantic data type Date.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DeliveryEditor actualDeliveryDate(LocalDate value);

    /**
     * BG-14 INVOICING PERIOD. Group giving the period the invoice as a whole relates to.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the editor of the instance of BG-14 in this group instance; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    InvoicingPeriodEditor invoicingPeriod();

    /**
     * BG-14 INVOICING PERIOD. Group giving the period the invoice as a whole relates to.
     *
     * <p>Declared cardinality 0..1.
     *
     * @param block what to write into the instance of BG-14
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    DeliveryEditor invoicingPeriod(Consumer<InvoicingPeriodEditor> block);

    /**
     * BG-15 DELIVER TO ADDRESS. Group carrying the address the goods or services are delivered to.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the editor of the instance of BG-15 in this group instance; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    DeliveryAddressEditor address();

    /**
     * BG-15 DELIVER TO ADDRESS. Group carrying the address the goods or services are delivered to.
     *
     * <p>Declared cardinality 0..1.
     *
     * @param block what to write into the instance of BG-15
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    DeliveryEditor address(Consumer<DeliveryAddressEditor> block);
}
