// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.Objects;

/** Writes {@link DirectDebitEditor} into a document builder. */
final class DirectDebitEdit implements DirectDebitEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    DirectDebitEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public DirectDebitEditor mandateReferenceIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-89"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public DirectDebitEditor mandateReferenceIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-89"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public DirectDebitEditor bankAssignedCreditorIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-90"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public DirectDebitEditor bankAssignedCreditorIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-90"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public DirectDebitEditor debitedAccountIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-91"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public DirectDebitEditor debitedAccountIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-91"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public DirectDebitEditor accountName(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-216"), value, Writers.TEXT);
        return this;
    }

    @Override
    public DirectDebitEditor serviceProviderIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-215"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public DirectDebitEditor serviceProviderIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-215"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public String toString() {
        return "DirectDebitEditor[" + path + "]";
    }
}
