// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link DirectDebit} from a semantic document. */
final class DirectDebitView implements DirectDebit {

    private final SemanticDocument document;
    private final SemanticPath path;

    DirectDebitView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public Optional<Identifier> mandateReferenceIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-89"), Values.IDENTIFIER);
    }

    @Override
    public Optional<Identifier> bankAssignedCreditorIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-90"), Values.IDENTIFIER);
    }

    @Override
    public Optional<Identifier> debitedAccountIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-91"), Values.IDENTIFIER);
    }

    @Override
    public Optional<String> accountName() {
        return Views.optional(document, TermPaths.value(path, "BT-216"), Values.TEXT);
    }

    @Override
    public Optional<Identifier> serviceProviderIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-215"), Values.IDENTIFIER);
    }

    @Override
    public String toString() {
        return "DirectDebit[" + path + "]";
    }
}
