// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.util.Objects;

/** Writes {@link DocumentLevelChargeEditor} into a document builder. */
final class DocumentLevelChargeEdit implements DocumentLevelChargeEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    DocumentLevelChargeEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public DocumentLevelChargeEditor amount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-99"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentLevelChargeEditor baseAmount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-100"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentLevelChargeEditor percentage(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-101"), value, Writers.PERCENTAGE);
        return this;
    }

    @Override
    public DocumentLevelChargeEditor vatCategoryCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-102"), value, Writers.CODE);
        return this;
    }

    @Override
    public DocumentLevelChargeEditor vatRate(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-103"), value, Writers.PERCENTAGE);
        return this;
    }

    @Override
    public DocumentLevelChargeEditor exemptionReasonText(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-175"), value, Writers.TEXT);
        return this;
    }

    @Override
    public DocumentLevelChargeEditor exemptionReasonCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-176"), value, Writers.CODE);
        return this;
    }

    @Override
    public DocumentLevelChargeEditor reason(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-104"), value, Writers.TEXT);
        return this;
    }

    @Override
    public DocumentLevelChargeEditor reasonCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-105"), value, Writers.CODE);
        return this;
    }

    @Override
    public DocumentLevelChargeEditor nonVatTaxTypeCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-177"), value, Writers.CODE);
        return this;
    }

    @Override
    public DocumentLevelChargeEditor goodsServicesCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-214"), value, Writers.CODE);
        return this;
    }

    @Override
    public String toString() {
        return "DocumentLevelChargeEditor[" + path + "]";
    }
}
