// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;

/**
 * BG-20 DOCUMENT LEVEL ALLOWANCES. Group carrying an allowance that applies to the invoice as a
 * whole.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code DocumentLevelAllowanceEditor} checks a value against the grammar of its
 * semantic data type and nothing else.
 */
public interface DocumentLevelAllowanceEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-92 Document level allowance amount. Amount of the document level allowance, without VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentLevelAllowanceEditor amount(BigDecimal value);

    /**
     * BT-93 Document level allowance base amount. Base amount the document level allowance
     * percentage is applied to.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentLevelAllowanceEditor baseAmount(BigDecimal value);

    /**
     * BT-94 Document level allowance percentage. Percentage applied to the base amount to derive
     * the document level allowance amount.
     *
     * <p>Declared cardinality 0..1, semantic data type Percentage.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentLevelAllowanceEditor percentage(BigDecimal value);

    /**
     * BT-95 Document level allowance VAT category code. VAT category code that applies to the
     * document level allowance.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    DocumentLevelAllowanceEditor vatCategoryCode(String value);

    /**
     * BT-96 Document level allowance VAT rate. VAT rate that applies to the document level
     * allowance, as a percentage.
     *
     * <p>Declared cardinality 0..1, semantic data type Percentage.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentLevelAllowanceEditor vatRate(BigDecimal value);

    /**
     * BT-173 Document level allowance exemption reason text. Reason, as text, why the document
     * level allowance carries no VAT.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    DocumentLevelAllowanceEditor exemptionReasonText(String value);

    /**
     * BT-174 Document level allowance VAT exemption reason and specification code. Coded reason why
     * the document level allowance carries no VAT.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    DocumentLevelAllowanceEditor exemptionReasonCode(String value);

    /**
     * BT-97 Document level allowance reason. Textual reason for the document level allowance.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    DocumentLevelAllowanceEditor reason(String value);

    /**
     * BT-98 Document level allowance reason code. Coded reason for the document level allowance,
     * from UNTDID 5189.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    DocumentLevelAllowanceEditor reasonCode(String value);

    /**
     * BT-213 Document level allowance goods/services code. Code stating whether the document level
     * allowance concerns goods, services or both.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    DocumentLevelAllowanceEditor goodsServicesCode(String value);
}
