// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link DocumentTotals} from a semantic document. */
final class DocumentTotalsView implements DocumentTotals {

    private final SemanticDocument document;
    private final SemanticPath path;

    DocumentTotalsView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public BigDecimal sumOfLineNetAmounts() {
        return Views.required(document, TermPaths.value(path, "BT-106"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> sumOfAllowances() {
        return Views.optional(document, TermPaths.value(path, "BT-107"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> sumOfCharges() {
        return Views.optional(document, TermPaths.value(path, "BT-108"), Values.AMOUNT);
    }

    @Override
    public BigDecimal totalWithoutVat() {
        return Views.required(document, TermPaths.value(path, "BT-109"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> totalVatAmount() {
        return Views.optional(document, TermPaths.value(path, "BT-110"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> totalVatAmountInAccountingCurrency() {
        return Views.optional(document, TermPaths.value(path, "BT-111"), Values.AMOUNT);
    }

    @Override
    public BigDecimal totalWithVat() {
        return Views.required(document, TermPaths.value(path, "BT-112"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> paidAmount() {
        return Views.optional(document, TermPaths.value(path, "BT-113"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> roundingAmount() {
        return Views.optional(document, TermPaths.value(path, "BT-114"), Values.AMOUNT);
    }

    @Override
    public BigDecimal amountDueForPayment() {
        return Views.required(document, TermPaths.value(path, "BT-115"), Values.AMOUNT);
    }

    @Override
    public List<ThirdPartyCharge> thirdPartyCharges() {
        return Views.groups(document, path, "BG-34", ThirdPartyChargeView::new);
    }

    @Override
    public String toString() {
        return "DocumentTotals[" + path + "]";
    }
}
