// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.MissingValueException;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.math.BigDecimal;
import java.util.Optional;

/**
 * BG-20 DOCUMENT LEVEL ALLOWANCES. Group carrying an allowance that applies to the invoice as a
 * whole.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface DocumentLevelAllowance {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-92 Document level allowance amount. Amount of the document level allowance, without VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @return the value of BT-92 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal amount();

    /**
     * BT-93 Document level allowance base amount. Base amount the document level allowance
     * percentage is applied to.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @return the value of BT-93 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> baseAmount();

    /**
     * BT-94 Document level allowance percentage. Percentage applied to the base amount to derive
     * the document level allowance amount.
     *
     * <p>Declared cardinality 0..1, semantic data type Percentage.
     *
     * @return the value of BT-94 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> percentage();

    /**
     * BT-95 Document level allowance VAT category code. VAT category code that applies to the
     * document level allowance.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @return the value of BT-95 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String vatCategoryCode();

    /**
     * BT-96 Document level allowance VAT rate. VAT rate that applies to the document level
     * allowance, as a percentage.
     *
     * <p>Declared cardinality 0..1, semantic data type Percentage.
     *
     * @return the value of BT-96 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> vatRate();

    /**
     * BT-173 Document level allowance exemption reason text. Reason, as text, why the document
     * level allowance carries no VAT.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-173 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> exemptionReasonText();

    /**
     * BT-174 Document level allowance VAT exemption reason and specification code. Coded reason why
     * the document level allowance carries no VAT.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-174 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> exemptionReasonCode();

    /**
     * BT-97 Document level allowance reason. Textual reason for the document level allowance.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-97 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> reason();

    /**
     * BT-98 Document level allowance reason code. Coded reason for the document level allowance,
     * from UNTDID 5189.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-98 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> reasonCode();

    /**
     * BT-213 Document level allowance goods/services code. Code stating whether the document level
     * allowance concerns goods, services or both.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-213 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> goodsServicesCode();
}
