// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.math.BigDecimal;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link DocumentLevelCharge} from a semantic document. */
final class DocumentLevelChargeView implements DocumentLevelCharge {

    private final SemanticDocument document;
    private final SemanticPath path;

    DocumentLevelChargeView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public BigDecimal amount() {
        return Views.required(document, TermPaths.value(path, "BT-99"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> baseAmount() {
        return Views.optional(document, TermPaths.value(path, "BT-100"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> percentage() {
        return Views.optional(document, TermPaths.value(path, "BT-101"), Values.PERCENTAGE);
    }

    @Override
    public String vatCategoryCode() {
        return Views.required(document, TermPaths.value(path, "BT-102"), Values.CODE);
    }

    @Override
    public Optional<BigDecimal> vatRate() {
        return Views.optional(document, TermPaths.value(path, "BT-103"), Values.PERCENTAGE);
    }

    @Override
    public Optional<String> exemptionReasonText() {
        return Views.optional(document, TermPaths.value(path, "BT-175"), Values.TEXT);
    }

    @Override
    public Optional<String> exemptionReasonCode() {
        return Views.optional(document, TermPaths.value(path, "BT-176"), Values.CODE);
    }

    @Override
    public Optional<String> reason() {
        return Views.optional(document, TermPaths.value(path, "BT-104"), Values.TEXT);
    }

    @Override
    public Optional<String> reasonCode() {
        return Views.optional(document, TermPaths.value(path, "BT-105"), Values.CODE);
    }

    @Override
    public Optional<String> nonVatTaxTypeCode() {
        return Views.optional(document, TermPaths.value(path, "BT-177"), Values.CODE);
    }

    @Override
    public Optional<String> goodsServicesCode() {
        return Views.optional(document, TermPaths.value(path, "BT-214"), Values.CODE);
    }

    @Override
    public String toString() {
        return "DocumentLevelCharge[" + path + "]";
    }
}
