// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.util.Objects;

/** Writes {@link DocumentLevelAllowanceEditor} into a document builder. */
final class DocumentLevelAllowanceEdit implements DocumentLevelAllowanceEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    DocumentLevelAllowanceEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public DocumentLevelAllowanceEditor amount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-92"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentLevelAllowanceEditor baseAmount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-93"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentLevelAllowanceEditor percentage(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-94"), value, Writers.PERCENTAGE);
        return this;
    }

    @Override
    public DocumentLevelAllowanceEditor vatCategoryCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-95"), value, Writers.CODE);
        return this;
    }

    @Override
    public DocumentLevelAllowanceEditor vatRate(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-96"), value, Writers.PERCENTAGE);
        return this;
    }

    @Override
    public DocumentLevelAllowanceEditor exemptionReasonText(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-173"), value, Writers.TEXT);
        return this;
    }

    @Override
    public DocumentLevelAllowanceEditor exemptionReasonCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-174"), value, Writers.CODE);
        return this;
    }

    @Override
    public DocumentLevelAllowanceEditor reason(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-97"), value, Writers.TEXT);
        return this;
    }

    @Override
    public DocumentLevelAllowanceEditor reasonCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-98"), value, Writers.CODE);
        return this;
    }

    @Override
    public DocumentLevelAllowanceEditor goodsServicesCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-213"), value, Writers.CODE);
        return this;
    }

    @Override
    public String toString() {
        return "DocumentLevelAllowanceEditor[" + path + "]";
    }
}
