// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.EditorList;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.util.Objects;
import java.util.function.Consumer;

/** Writes {@link InvoiceLineEditor} into a document builder. */
final class InvoiceLineEdit implements InvoiceLineEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    InvoiceLineEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public InvoiceLineEditor identifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-126"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceLineEditor identifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-126"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceLineEditor note(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-127"), value, Writers.TEXT);
        return this;
    }

    @Override
    public InvoiceLineEditor objectIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-128"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceLineEditor objectIdentifier(String value, String scheme) {
        Editors.set(builder, TermPaths.value(path, "BT-128"),
                Editors.identifier(value, scheme, null), Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceLineEditor objectIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-128"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceLineEditor quantity(BigDecimal value, String unitCode) {
        Editors.set(builder, TermPaths.value(path, "BT-129"), value, Writers.QUANTITY);
        Editors.set(builder, TermPaths.value(path, "BT-130"), unitCode, Writers.CODE);
        return this;
    }

    @Override
    public InvoiceLineEditor quantity(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-129"), value, Writers.QUANTITY);
        return this;
    }

    @Override
    public InvoiceLineEditor quantityUnitCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-130"), value, Writers.CODE);
        return this;
    }

    @Override
    public InvoiceLineEditor netAmount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-131"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public InvoiceLineEditor purchaseOrderReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-188"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLineEditor purchaseOrderLineReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-132"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLineEditor salesOrderReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-200"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLineEditor salesOrderLineReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-201"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLineEditor despatchAdviceReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-189"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLineEditor despatchAdviceLineReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-190"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLineEditor receivingAdviceReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-191"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLineEditor receivingAdviceLineReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-192"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLineEditor deliveryNoteReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-198"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLineEditor deliveryNoteLineReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-199"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLineEditor buyerAccountingReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-133"), value, Writers.TEXT);
        return this;
    }

    @Override
    public EditorList<InvoiceLinePrecedingInvoiceReferenceEditor> precedingInvoiceReferences() {
        return Editors.groups(builder, path, "BG-39", InvoiceLinePrecedingInvoiceReferenceEdit::new);
    }

    @Override
    public InvoiceLineEditor precedingInvoiceReference(Consumer<InvoiceLinePrecedingInvoiceReferenceEditor> block) {
        precedingInvoiceReferences().add(block);
        return this;
    }

    @Override
    public InvoiceLineDeliveryEditor delivery() {
        return new InvoiceLineDeliveryEdit(builder, TermPaths.group(path, "BG-37"));
    }

    @Override
    public InvoiceLineEditor delivery(Consumer<InvoiceLineDeliveryEditor> block) {
        Objects.requireNonNull(block, "block").accept(delivery());
        return this;
    }

    @Override
    public EditorList<AllowanceEditor> allowances() {
        return Editors.groups(builder, path, "BG-27", AllowanceEdit::new);
    }

    @Override
    public InvoiceLineEditor allowance(Consumer<AllowanceEditor> block) {
        allowances().add(block);
        return this;
    }

    @Override
    public EditorList<ChargeEditor> charges() {
        return Editors.groups(builder, path, "BG-28", ChargeEdit::new);
    }

    @Override
    public InvoiceLineEditor charge(Consumer<ChargeEditor> block) {
        charges().add(block);
        return this;
    }

    @Override
    public PriceEditor price() {
        return new PriceEdit(builder, TermPaths.group(path, "BG-29"));
    }

    @Override
    public InvoiceLineEditor price(Consumer<PriceEditor> block) {
        Objects.requireNonNull(block, "block").accept(price());
        return this;
    }

    @Override
    public VatEditor vat() {
        return new VatEdit(builder, TermPaths.group(path, "BG-30"));
    }

    @Override
    public InvoiceLineEditor vat(Consumer<VatEditor> block) {
        Objects.requireNonNull(block, "block").accept(vat());
        return this;
    }

    @Override
    public ItemEditor item() {
        return new ItemEdit(builder, TermPaths.group(path, "BG-31"));
    }

    @Override
    public InvoiceLineEditor item(Consumer<ItemEditor> block) {
        Objects.requireNonNull(block, "block").accept(item());
        return this;
    }

    @Override
    public String toString() {
        return "InvoiceLineEditor[" + path + "]";
    }
}
