// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.EditorList;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.util.function.Consumer;

/**
 * BG-25 INVOICE LINE. Group carrying one invoice line.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code InvoiceLineEditor} checks a value against the grammar of its semantic data
 * type and nothing else.
 */
public interface InvoiceLineEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-126 Invoice line identifier. Identifier of the invoice line, unique within the invoice.
     *
     * <p>Declared cardinality 1..1, semantic data type Identifier.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value; where
     *     the argument is the literal {@code null}, Java cannot choose between this overload and
     *     the one taking an {@code Identifier}, so write {@code (String) null} or the empty string
     *     instead
     * @return this editor
     */
    InvoiceLineEditor identifier(String value);

    /**
     * BT-126 Invoice line identifier. Identifier of the invoice line, unique within the invoice.
     *
     * <p>Declared cardinality 1..1, semantic data type Identifier.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value; where the argument is the
     *     literal {@code null}, Java cannot choose between this overload and the one taking a
     *     string, so write {@code (Identifier) null} or the empty string instead
     * @return this editor
     */
    InvoiceLineEditor identifier(Identifier value);

    /**
     * BT-127 Invoice line note. Free-text note about the invoice line.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor note(String value);

    /**
     * BT-128 Invoice line object identifier. Identifier of an object the invoice line is based on,
     * given by the seller.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the UNTDID 1153
     * list.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value; where
     *     the argument is the literal {@code null}, Java cannot choose between this overload and
     *     the one taking an {@code Identifier}, so write {@code (String) null} or the empty string
     *     instead
     * @return this editor
     */
    InvoiceLineEditor objectIdentifier(String value);

    /**
     * BT-128 Invoice line object identifier. Identifier of an object the invoice line is based on,
     * given by the seller.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the UNTDID 1153
     * list.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value
     * @param scheme the identification scheme, a code of the UNTDID 1153 list
     * @return this editor
     */
    InvoiceLineEditor objectIdentifier(String value, String scheme);

    /**
     * BT-128 Invoice line object identifier. Identifier of an object the invoice line is based on,
     * given by the seller.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the UNTDID 1153
     * list.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value; where the argument is the
     *     literal {@code null}, Java cannot choose between this overload and the one taking a
     *     string, so write {@code (Identifier) null} or the empty string instead
     * @return this editor
     */
    InvoiceLineEditor objectIdentifier(Identifier value);

    /**
     * BT-129 Invoiced quantity. Quantity of items invoiced on this line.
     *
     * <p>Declared cardinality 1..1, semantic data type Quantity.
     *
     * @param value the quantity, or {@code null} to remove it
     * @param unitCode the unit of measure of that quantity, written to BT-130, or {@code null} or
     *     the empty string to remove it
     * @return this editor
     */
    InvoiceLineEditor quantity(BigDecimal value, String unitCode);

    /**
     * BT-129 Invoiced quantity. Quantity of items invoiced on this line.
     *
     * <p>Declared cardinality 1..1, semantic data type Quantity.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    InvoiceLineEditor quantity(BigDecimal value);

    /**
     * BT-130 Invoiced quantity unit of measure code. Unit of measure code for the invoiced
     * quantity, from UN/ECE Recommendation 20 with the Recommendation 21 extension.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor quantityUnitCode(String value);

    /**
     * BT-131 Invoice line net amount. Net amount of the invoice line, after line allowances and
     * charges and excluding VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    InvoiceLineEditor netAmount(BigDecimal value);

    /**
     * BT-188 Invoice line purchase order reference. Identifier of a purchase order the invoice line
     * refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor purchaseOrderReference(String value);

    /**
     * BT-132 Invoice line purchase order line reference. Identifier of a line within a purchase
     * order the invoice line refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor purchaseOrderLineReference(String value);

    /**
     * BT-200 Invoice line sales order reference. Identifier of a sales order the invoice line
     * refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor salesOrderReference(String value);

    /**
     * BT-201 Invoice line sales order line reference. Identifier of a line within a sales order the
     * invoice line refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor salesOrderLineReference(String value);

    /**
     * BT-189 Invoice line despatch advice reference. Identifier of a despatch advice the invoice
     * line refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor despatchAdviceReference(String value);

    /**
     * BT-190 Invoice line despatch advice line reference. Identifier of a line within a despatch
     * advice the invoice line refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor despatchAdviceLineReference(String value);

    /**
     * BT-191 Invoice line receiving advice reference. Identifier of a receiving advice the invoice
     * line refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor receivingAdviceReference(String value);

    /**
     * BT-192 Invoice line receiving advice line reference. Identifier of a line within a receiving
     * advice the invoice line refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor receivingAdviceLineReference(String value);

    /**
     * BT-198 Invoice line delivery note reference. Identifier of a delivery note the invoice line
     * refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor deliveryNoteReference(String value);

    /**
     * BT-199 Invoice line delivery note line reference. Identifier of a line within a delivery note
     * the invoice line refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor deliveryNoteLineReference(String value);

    /**
     * BT-133 Invoice line Buyer accounting reference. Textual reference telling the buyer which
     * ledger account to book this invoice line to.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLineEditor buyerAccountingReference(String value);

    /**
     * BG-39 LINE-LEVEL PRECEDING INVOICE REFERENCE. Group referencing a preceding invoice from an
     * invoice line.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-39 in this group instance, which appends, reads,
     *     removes and empties them
     */
    EditorList<InvoiceLinePrecedingInvoiceReferenceEditor> precedingInvoiceReferences();

    /**
     * BG-39 LINE-LEVEL PRECEDING INVOICE REFERENCE. Group referencing a preceding invoice from an
     * invoice line.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-39
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceLineEditor precedingInvoiceReference(Consumer<InvoiceLinePrecedingInvoiceReferenceEditor> block);

    /**
     * BG-37 INVOICE LINE DELIVERY INFORMATION. Group carrying delivery information for a single
     * invoice line.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the editor of the instance of BG-37 in this group instance; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    InvoiceLineDeliveryEditor delivery();

    /**
     * BG-37 INVOICE LINE DELIVERY INFORMATION. Group carrying delivery information for a single
     * invoice line.
     *
     * <p>Declared cardinality 0..1.
     *
     * @param block what to write into the instance of BG-37
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceLineEditor delivery(Consumer<InvoiceLineDeliveryEditor> block);

    /**
     * BG-27 INVOICE LINE ALLOWANCES. Group carrying an allowance that applies to this invoice line.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-27 in this group instance, which appends, reads,
     *     removes and empties them
     */
    EditorList<AllowanceEditor> allowances();

    /**
     * BG-27 INVOICE LINE ALLOWANCES. Group carrying an allowance that applies to this invoice line.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-27
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceLineEditor allowance(Consumer<AllowanceEditor> block);

    /**
     * BG-28 INVOICE LINE CHARGES AND TAXES. Group for charges and non-VAT taxes that apply to a
     * single invoice line.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-28 in this group instance, which appends, reads,
     *     removes and empties them
     */
    EditorList<ChargeEditor> charges();

    /**
     * BG-28 INVOICE LINE CHARGES AND TAXES. Group for charges and non-VAT taxes that apply to a
     * single invoice line.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-28
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceLineEditor charge(Consumer<ChargeEditor> block);

    /**
     * BG-29 PRICE DETAILS. Group carrying the price information for the item on this invoice line.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the editor of the instance of BG-29 in this group instance; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    PriceEditor price();

    /**
     * BG-29 PRICE DETAILS. Group carrying the price information for the item on this invoice line.
     *
     * <p>Declared cardinality 1..1.
     *
     * @param block what to write into the instance of BG-29
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceLineEditor price(Consumer<PriceEditor> block);

    /**
     * BG-30 LINE VAT INFORMATION. Group carrying the VAT information that applies to the item on
     * this invoice line.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the editor of the instance of BG-30 in this group instance; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    VatEditor vat();

    /**
     * BG-30 LINE VAT INFORMATION. Group carrying the VAT information that applies to the item on
     * this invoice line.
     *
     * <p>Declared cardinality 1..1.
     *
     * @param block what to write into the instance of BG-30
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceLineEditor vat(Consumer<VatEditor> block);

    /**
     * BG-31 ITEM INFORMATION. Group describing the goods or services invoiced on this line.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the editor of the instance of BG-31 in this group instance; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    ItemEditor item();

    /**
     * BG-31 ITEM INFORMATION. Group describing the goods or services invoiced on this line.
     *
     * <p>Declared cardinality 1..1.
     *
     * @param block what to write into the instance of BG-31
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceLineEditor item(Consumer<ItemEditor> block);
}
