// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.time.LocalDate;
import java.util.Objects;

/** Writes {@link InvoicingPeriodEditor} into a document builder. */
final class InvoicingPeriodEdit implements InvoicingPeriodEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    InvoicingPeriodEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public InvoicingPeriodEditor startDate(LocalDate value) {
        Editors.set(builder, TermPaths.value(path, "BT-73"), value, Writers.DATE);
        return this;
    }

    @Override
    public InvoicingPeriodEditor endDate(LocalDate value) {
        Editors.set(builder, TermPaths.value(path, "BT-74"), value, Writers.DATE);
        return this;
    }

    @Override
    public String toString() {
        return "InvoicingPeriodEditor[" + path + "]";
    }
}
