// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.MissingValueException;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.util.Optional;

/**
 * BG-38 INVOICE LINE DELIVER TO ADDRESS. Group carrying the address the goods or services of this
 * line are delivered to.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface InvoiceLineDeliveryAddress {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-203 Invoice line deliver to address line 1. First line of the deliver to address of this
     * invoice line.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-203 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> addressLine1();

    /**
     * BT-204 Invoice line deliver to address line 2. Second line of the deliver to address of this
     * invoice line.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-204 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> addressLine2();

    /**
     * BT-205 Invoice line deliver to address line 3. Third line of the deliver to address of this
     * invoice line.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-205 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> addressLine3();

    /**
     * BT-206 Invoice line deliver to city. City of the deliver to address of this invoice line.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-206 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> city();

    /**
     * BT-207 Invoice line deliver to post code. Post code of the deliver to address of this invoice
     * line.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-207 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> postCode();

    /**
     * BT-208 Invoice line deliver to country subdivision. Country subdivision of the deliver to
     * address of this invoice line.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-208 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> countrySubdivision();

    /**
     * BT-209 Invoice line deliver to country code. Country of the deliver to address of this
     * invoice line.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @return the value of BT-209 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String countryCode();
}
