// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.time.LocalDate;
import java.util.Optional;

/**
 * BG-37 INVOICE LINE DELIVERY INFORMATION. Group carrying delivery information for a single invoice
 * line.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface InvoiceLineDelivery {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-185 Invoice line deliver to party name. Name of the party the goods or services of this
     * line are delivered to.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-185 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> partyName();

    /**
     * BT-186 Invoice line deliver to location identifier. Identifier of the place the goods or
     * services of this line are delivered to.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @return the value of BT-186 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<Identifier> locationIdentifier();

    /**
     * BT-187 Invoice line actual delivery date. Date on which the goods or services of this line
     * were delivered.
     *
     * <p>Declared cardinality 0..1, semantic data type Date.
     *
     * @return the value of BT-187 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<LocalDate> actualDeliveryDate();

    /**
     * BG-38 INVOICE LINE DELIVER TO ADDRESS. Group carrying the address the goods or services of
     * this line are delivered to.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the view over the instance of BG-38 in this group instance, or an empty optional
     *     where the document carries no value under it
     */
    Optional<InvoiceLineDeliveryAddress> address();

    /**
     * BG-26 INVOICE LINE PERIOD. Group giving the period this invoice line relates to.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the view over the instance of BG-26 in this group instance, or an empty optional
     *     where the document carries no value under it
     */
    Optional<Period> period();
}
