// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.time.LocalDate;

/**
 * BG-39 LINE-LEVEL PRECEDING INVOICE REFERENCE. Group referencing a preceding invoice from an
 * invoice line.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code InvoiceLinePrecedingInvoiceReferenceEditor} checks a value against the
 * grammar of its semantic data type and nothing else.
 */
public interface InvoiceLinePrecedingInvoiceReferenceEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-217 Line-level preceding invoice reference. Identifier of an invoice previously sent by
     * the seller, referenced from this line.
     *
     * <p>Declared cardinality 1..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLinePrecedingInvoiceReferenceEditor reference(String value);

    /**
     * BT-218 Line-level preceding invoice issue date. Issue date of the preceding invoice
     * referenced from this line.
     *
     * <p>Declared cardinality 0..1, semantic data type Date.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    InvoiceLinePrecedingInvoiceReferenceEditor issueDate(LocalDate value);

    /**
     * BT-219 Line-level preceding invoice type code. Code for the functional type of the preceding
     * invoice referenced from this line.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLinePrecedingInvoiceReferenceEditor typeCode(String value);

    /**
     * BT-220 Line-level preceding invoice line reference. Identifier of a line in the preceding
     * invoice referenced from this line.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceLinePrecedingInvoiceReferenceEditor lineReference(String value);
}
