// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.time.LocalDate;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link InvoiceLinePrecedingInvoiceReference} from a semantic document. */
final class InvoiceLinePrecedingInvoiceReferenceView implements InvoiceLinePrecedingInvoiceReference {

    private final SemanticDocument document;
    private final SemanticPath path;

    InvoiceLinePrecedingInvoiceReferenceView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public String reference() {
        return Views.required(document, TermPaths.value(path, "BT-217"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public Optional<LocalDate> issueDate() {
        return Views.optional(document, TermPaths.value(path, "BT-218"), Values.DATE);
    }

    @Override
    public Optional<String> typeCode() {
        return Views.optional(document, TermPaths.value(path, "BT-219"), Values.CODE);
    }

    @Override
    public Optional<String> lineReference() {
        return Views.optional(document, TermPaths.value(path, "BT-220"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public String toString() {
        return "InvoiceLinePrecedingInvoiceReference[" + path + "]";
    }
}
