// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.EditorList;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.IdentifierList;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetTime;
import java.util.function.Consumer;

/**
 * Writes the invoice as a whole: the business terms and business groups the semantic model places
 * at the root of a document.
 *
 * <p>An editor over a document builder. Every setter writes into that one builder and returns this
 * editor, so an invoice is written as one chain of names rather than as a list of paths.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code InvoiceEditor} checks a value against the grammar of its semantic data
 * type and nothing else.
 */
public interface InvoiceEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the root of the document, which has no segments.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-1 Invoice number. Unique identification of the invoice in the seller's systems; no
     * identification scheme is used.
     *
     * <p>Declared cardinality 1..1, semantic data type Identifier.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value; where
     *     the argument is the literal {@code null}, Java cannot choose between this overload and
     *     the one taking an {@code Identifier}, so write {@code (String) null} or the empty string
     *     instead
     * @return this editor
     */
    InvoiceEditor invoiceNumber(String value);

    /**
     * BT-1 Invoice number. Unique identification of the invoice in the seller's systems; no
     * identification scheme is used.
     *
     * <p>Declared cardinality 1..1, semantic data type Identifier.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value; where the argument is the
     *     literal {@code null}, Java cannot choose between this overload and the one taking a
     *     string, so write {@code (Identifier) null} or the empty string instead
     * @return this editor
     */
    InvoiceEditor invoiceNumber(Identifier value);

    /**
     * BT-2 Invoice issue date. Date on which the invoice was issued.
     *
     * <p>Declared cardinality 1..1, semantic data type Date.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    InvoiceEditor issueDate(LocalDate value);

    /**
     * BT-166 Invoice issue time. Time of day at which the invoice was issued.
     *
     * <p>Declared cardinality 0..1, semantic data type Time.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    InvoiceEditor issueTime(OffsetTime value);

    /**
     * BT-3 Invoice type code. Code for the functional type of the invoice, taken from UNTDID 1001.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor typeCode(String value);

    /**
     * BT-5 Invoice currency code. The currency of every amount in this invoice; BT-111 is the one
     * amount written in the accounting currency instead.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor currencyCode(String value);

    /**
     * BT-6 VAT accounting currency code. Currency used for VAT accounting and reporting in the
     * seller's country.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor vatAccountingCurrencyCode(String value);

    /**
     * BT-167 VAT accounting currency exchange rate. Value of one unit of the VAT accounting
     * currency expressed in the invoice currency.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    InvoiceEditor vatAccountingCurrencyExchangeRate(BigDecimal value);

    /**
     * BT-7 Value added tax point date. Date on which VAT becomes chargeable for seller and buyer
     * (tax point date).
     *
     * <p>Declared cardinality 0..1, semantic data type Date.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    InvoiceEditor taxPointDate(LocalDate value);

    /**
     * BT-8 Value added tax point date code. Code saying which event fixes the VAT tax point date.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor taxPointDateCode(String value);

    /**
     * BT-9 Payment due date. Date by which payment is due.
     *
     * <p>Declared cardinality 0..1, semantic data type Date.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    InvoiceEditor paymentDueDate(LocalDate value);

    /**
     * BT-10 Buyer reference. Reference supplied by the buyer that lets the buyer route the invoice
     * internally.
     *
     * <p>Declared cardinality 0..n, semantic data type Identifier, scheme from the UNTDID 1153
     * list.
     *
     * @return the handle of the occurrences of BT-10 at the root of the document, which appends,
     *     reads, removes and empties them
     */
    IdentifierList buyerReference();

    /**
     * BT-11 Project reference. Reference to the project the invoice relates to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor projectReference(String value);

    /**
     * BT-12 Contract reference. Reference to the contract the invoice relates to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor contractReference(String value);

    /**
     * BT-13 Purchase order reference. Reference to the buyer's purchase order.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor purchaseOrderReference(String value);

    /**
     * BT-14 Sales order reference. Reference to the seller's sales order.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor salesOrderReference(String value);

    /**
     * BT-15 Receiving advice reference. Reference to the receiving advice for the delivered goods
     * or services.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor receivingAdviceReference(String value);

    /**
     * BT-16 Despatch advice reference. Reference to the despatch advice for the delivered goods or
     * services.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor despatchAdviceReference(String value);

    /**
     * BT-197 Delivery note reference. Identifier of a delivery note the invoice refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor deliveryNoteReference(String value);

    /**
     * BT-17 Tender or lot reference. Names the tender, or the lot within it, that the contract
     * behind this invoice goes back to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor tenderOrLotReference(String value);

    /**
     * BT-18 Invoiced object identifier. Identifier of an object the invoice is based on, assigned
     * by the seller (e.g. a subscription, meter point or vehicle).
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the UNTDID 1153
     * list.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value; where
     *     the argument is the literal {@code null}, Java cannot choose between this overload and
     *     the one taking an {@code Identifier}, so write {@code (String) null} or the empty string
     *     instead
     * @return this editor
     */
    InvoiceEditor invoicedObjectIdentifier(String value);

    /**
     * BT-18 Invoiced object identifier. Identifier of an object the invoice is based on, assigned
     * by the seller (e.g. a subscription, meter point or vehicle).
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the UNTDID 1153
     * list.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value
     * @param scheme the identification scheme, a code of the UNTDID 1153 list
     * @return this editor
     */
    InvoiceEditor invoicedObjectIdentifier(String value, String scheme);

    /**
     * BT-18 Invoiced object identifier. Identifier of an object the invoice is based on, assigned
     * by the seller (e.g. a subscription, meter point or vehicle).
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the UNTDID 1153
     * list.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value; where the argument is the
     *     literal {@code null}, Java cannot choose between this overload and the one taking a
     *     string, so write {@code (Identifier) null} or the empty string instead
     * @return this editor
     */
    InvoiceEditor invoicedObjectIdentifier(Identifier value);

    /**
     * BT-19 Buyer accounting reference. Textual reference telling the buyer which ledger account to
     * book the invoice to.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    InvoiceEditor buyerAccountingReference(String value);

    /**
     * BG-33 PAYMENT TERMS. Group under which the payment conditions of the invoice stand.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-33 at the root of the document, which appends,
     *     reads, removes and empties them
     */
    EditorList<PaymentTermEditor> paymentTerms();

    /**
     * BG-33 PAYMENT TERMS. Group under which the payment conditions of the invoice stand.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-33
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor paymentTerm(Consumer<PaymentTermEditor> block);

    /**
     * BG-1 INVOICE NOTE. Group carrying free-text notes about the invoice as a whole, with an
     * optional subject code.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-1 at the root of the document, which appends,
     *     reads, removes and empties them
     */
    EditorList<NoteEditor> notes();

    /**
     * BG-1 INVOICE NOTE. Group carrying free-text notes about the invoice as a whole, with an
     * optional subject code.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-1
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor note(Consumer<NoteEditor> block);

    /**
     * BG-2 PROCESS CONTROL. Group carrying the identifiers that control how the invoice is
     * processed.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the editor of the instance of BG-2 at the root of the document; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    ProcessControlEditor processControl();

    /**
     * BG-2 PROCESS CONTROL. Group carrying the identifiers that control how the invoice is
     * processed.
     *
     * <p>Declared cardinality 1..1.
     *
     * @param block what to write into the instance of BG-2
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor processControl(Consumer<ProcessControlEditor> block);

    /**
     * BG-3 PRECEDING INVOICE REFERENCE. Group referencing an invoice that precedes this one, used
     * mainly in corrections and credit notes.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-3 at the root of the document, which appends,
     *     reads, removes and empties them
     */
    EditorList<PrecedingInvoiceReferenceEditor> precedingInvoiceReferences();

    /**
     * BG-3 PRECEDING INVOICE REFERENCE. Group referencing an invoice that precedes this one, used
     * mainly in corrections and credit notes.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-3
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor precedingInvoiceReference(Consumer<PrecedingInvoiceReferenceEditor> block);

    /**
     * BG-4 SELLER. Group carrying the information about the seller.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the editor of the instance of BG-4 at the root of the document; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    SellerEditor seller();

    /**
     * BG-4 SELLER. Group carrying the information about the seller.
     *
     * <p>Declared cardinality 1..1.
     *
     * @param block what to write into the instance of BG-4
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor seller(Consumer<SellerEditor> block);

    /**
     * BG-7 BUYER. Group carrying the information about the buyer.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the editor of the instance of BG-7 at the root of the document; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    BuyerEditor buyer();

    /**
     * BG-7 BUYER. Group carrying the information about the buyer.
     *
     * <p>Declared cardinality 1..1.
     *
     * @param block what to write into the instance of BG-7
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor buyer(Consumer<BuyerEditor> block);

    /**
     * BG-10 PAYEE. Group carrying the payee, used when the party receiving payment is not the
     * seller.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the editor of the instance of BG-10 at the root of the document; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    PayeeEditor payee();

    /**
     * BG-10 PAYEE. Group carrying the payee, used when the party receiving payment is not the
     * seller.
     *
     * <p>Declared cardinality 0..1.
     *
     * @param block what to write into the instance of BG-10
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor payee(Consumer<PayeeEditor> block);

    /**
     * BG-11 SELLER TAX REPRESENTATIVE PARTY. Group carrying the seller's tax representative, used
     * when the seller has one.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the editor of the instance of BG-11 at the root of the document; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    SellerTaxRepresentativeEditor sellerTaxRepresentative();

    /**
     * BG-11 SELLER TAX REPRESENTATIVE PARTY. Group carrying the seller's tax representative, used
     * when the seller has one.
     *
     * <p>Declared cardinality 0..1.
     *
     * @param block what to write into the instance of BG-11
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor sellerTaxRepresentative(Consumer<SellerTaxRepresentativeEditor> block);

    /**
     * BG-13 DELIVERY INFORMATION. Group saying where and when the invoiced goods or services were
     * delivered.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the editor of the instance of BG-13 at the root of the document; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    DeliveryEditor delivery();

    /**
     * BG-13 DELIVERY INFORMATION. Group saying where and when the invoiced goods or services were
     * delivered.
     *
     * <p>Declared cardinality 0..1.
     *
     * @param block what to write into the instance of BG-13
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor delivery(Consumer<DeliveryEditor> block);

    /**
     * BG-16 PAYMENT INSTRUCTIONS. Group saying how the payment is expected to be made.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the editor of the instance of BG-16 at the root of the document; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    PaymentInstructionsEditor paymentInstructions();

    /**
     * BG-16 PAYMENT INSTRUCTIONS. Group saying how the payment is expected to be made.
     *
     * <p>Declared cardinality 0..1.
     *
     * @param block what to write into the instance of BG-16
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor paymentInstructions(Consumer<PaymentInstructionsEditor> block);

    /**
     * BG-20 DOCUMENT LEVEL ALLOWANCES. Group carrying an allowance that applies to the invoice as a
     * whole.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-20 at the root of the document, which appends,
     *     reads, removes and empties them
     */
    EditorList<DocumentLevelAllowanceEditor> documentLevelAllowances();

    /**
     * BG-20 DOCUMENT LEVEL ALLOWANCES. Group carrying an allowance that applies to the invoice as a
     * whole.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-20
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor documentLevelAllowance(Consumer<DocumentLevelAllowanceEditor> block);

    /**
     * BG-21 DOCUMENT LEVEL CHARGES AND TAXES. Group for charges and non-VAT taxes that apply to the
     * invoice as a whole.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-21 at the root of the document, which appends,
     *     reads, removes and empties them
     */
    EditorList<DocumentLevelChargeEditor> documentLevelCharges();

    /**
     * BG-21 DOCUMENT LEVEL CHARGES AND TAXES. Group for charges and non-VAT taxes that apply to the
     * invoice as a whole.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-21
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor documentLevelCharge(Consumer<DocumentLevelChargeEditor> block);

    /**
     * BG-22 DOCUMENT TOTALS. Group carrying the monetary totals of the invoice.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the editor of the instance of BG-22 at the root of the document; the group comes into
     *     being when a value is written into it, so an editor that is not written into leaves
     *     nothing behind
     */
    DocumentTotalsEditor documentTotals();

    /**
     * BG-22 DOCUMENT TOTALS. Group carrying the monetary totals of the invoice.
     *
     * <p>Declared cardinality 1..1.
     *
     * @param block what to write into the instance of BG-22
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor documentTotals(Consumer<DocumentTotalsEditor> block);

    /**
     * BG-23 VAT BREAKDOWN. Group breaking the invoice down by VAT category, rate and exemption
     * reason.
     *
     * <p>Declared cardinality 1..n.
     *
     * @return the handle of the instances of BG-23 at the root of the document, which appends,
     *     reads, removes and empties them
     */
    EditorList<VatBreakdownEditor> vatBreakdowns();

    /**
     * BG-23 VAT BREAKDOWN. Group breaking the invoice down by VAT category, rate and exemption
     * reason.
     *
     * <p>Declared cardinality 1..n.
     *
     * @param block what to write into the appended instance of BG-23
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor vatBreakdown(Consumer<VatBreakdownEditor> block);

    /**
     * BG-24 ADDITIONAL SUPPORTING DOCUMENTS. Group referencing a supporting document that backs the
     * claims made in the invoice.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-24 at the root of the document, which appends,
     *     reads, removes and empties them
     */
    EditorList<AdditionalSupportingDocumentEditor> additionalSupportingDocuments();

    /**
     * BG-24 ADDITIONAL SUPPORTING DOCUMENTS. Group referencing a supporting document that backs the
     * claims made in the invoice.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-24
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor additionalSupportingDocument(Consumer<AdditionalSupportingDocumentEditor> block);

    /**
     * BG-25 INVOICE LINE. Group carrying one invoice line.
     *
     * <p>Declared cardinality 1..n.
     *
     * @return the handle of the instances of BG-25 at the root of the document, which appends,
     *     reads, removes and empties them
     */
    EditorList<InvoiceLineEditor> invoiceLines();

    /**
     * BG-25 INVOICE LINE. Group carrying one invoice line.
     *
     * <p>Declared cardinality 1..n.
     *
     * @param block what to write into the appended instance of BG-25
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    InvoiceEditor invoiceLine(Consumer<InvoiceLineEditor> block);
}
