// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.time.LocalDate;
import java.util.Objects;
import java.util.function.Consumer;

/** Writes {@link InvoiceLineDeliveryEditor} into a document builder. */
final class InvoiceLineDeliveryEdit implements InvoiceLineDeliveryEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    InvoiceLineDeliveryEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public InvoiceLineDeliveryEditor partyName(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-185"), value, Writers.TEXT);
        return this;
    }

    @Override
    public InvoiceLineDeliveryEditor locationIdentifier(String value, String scheme) {
        Editors.set(builder, TermPaths.value(path, "BT-186"),
                Editors.identifier(value, scheme, null), Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceLineDeliveryEditor locationIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-186"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceLineDeliveryEditor actualDeliveryDate(LocalDate value) {
        Editors.set(builder, TermPaths.value(path, "BT-187"), value, Writers.DATE);
        return this;
    }

    @Override
    public InvoiceLineDeliveryAddressEditor address() {
        return new InvoiceLineDeliveryAddressEdit(builder, TermPaths.group(path, "BG-38"));
    }

    @Override
    public InvoiceLineDeliveryEditor address(Consumer<InvoiceLineDeliveryAddressEditor> block) {
        Objects.requireNonNull(block, "block").accept(address());
        return this;
    }

    @Override
    public PeriodEditor period() {
        return new PeriodEdit(builder, TermPaths.group(path, "BG-26"));
    }

    @Override
    public InvoiceLineDeliveryEditor period(Consumer<PeriodEditor> block) {
        Objects.requireNonNull(block, "block").accept(period());
        return this;
    }

    @Override
    public String toString() {
        return "InvoiceLineDeliveryEditor[" + path + "]";
    }
}
