// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.Objects;

/** Writes {@link InvoiceLineDeliveryAddressEditor} into a document builder. */
final class InvoiceLineDeliveryAddressEdit implements InvoiceLineDeliveryAddressEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    InvoiceLineDeliveryAddressEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public InvoiceLineDeliveryAddressEditor addressLine1(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-203"), value, Writers.TEXT);
        return this;
    }

    @Override
    public InvoiceLineDeliveryAddressEditor addressLine2(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-204"), value, Writers.TEXT);
        return this;
    }

    @Override
    public InvoiceLineDeliveryAddressEditor addressLine3(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-205"), value, Writers.TEXT);
        return this;
    }

    @Override
    public InvoiceLineDeliveryAddressEditor city(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-206"), value, Writers.TEXT);
        return this;
    }

    @Override
    public InvoiceLineDeliveryAddressEditor postCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-207"), value, Writers.TEXT);
        return this;
    }

    @Override
    public InvoiceLineDeliveryAddressEditor countrySubdivision(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-208"), value, Writers.TEXT);
        return this;
    }

    @Override
    public InvoiceLineDeliveryAddressEditor countryCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-209"), value, Writers.CODE);
        return this;
    }

    @Override
    public String toString() {
        return "InvoiceLineDeliveryAddressEditor[" + path + "]";
    }
}
