// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.time.LocalDate;
import java.util.Objects;

/** Writes {@link InvoiceLinePrecedingInvoiceReferenceEditor} into a document builder. */
final class InvoiceLinePrecedingInvoiceReferenceEdit implements InvoiceLinePrecedingInvoiceReferenceEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    InvoiceLinePrecedingInvoiceReferenceEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public InvoiceLinePrecedingInvoiceReferenceEditor reference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-217"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceLinePrecedingInvoiceReferenceEditor issueDate(LocalDate value) {
        Editors.set(builder, TermPaths.value(path, "BT-218"), value, Writers.DATE);
        return this;
    }

    @Override
    public InvoiceLinePrecedingInvoiceReferenceEditor typeCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-219"), value, Writers.CODE);
        return this;
    }

    @Override
    public InvoiceLinePrecedingInvoiceReferenceEditor lineReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-220"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public String toString() {
        return "InvoiceLinePrecedingInvoiceReferenceEditor[" + path + "]";
    }
}
