// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetTime;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link Invoice} from a semantic document. */
final class InvoiceView implements Invoice {

    private final SemanticDocument document;
    private final SemanticPath path;

    InvoiceView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public Identifier invoiceNumber() {
        return Views.required(document, TermPaths.value(path, "BT-1"), Values.IDENTIFIER);
    }

    @Override
    public LocalDate issueDate() {
        return Views.required(document, TermPaths.value(path, "BT-2"), Values.DATE);
    }

    @Override
    public Optional<OffsetTime> issueTime() {
        return Views.optional(document, TermPaths.value(path, "BT-166"), Values.TIME);
    }

    @Override
    public String typeCode() {
        return Views.required(document, TermPaths.value(path, "BT-3"), Values.CODE);
    }

    @Override
    public String currencyCode() {
        return Views.required(document, TermPaths.value(path, "BT-5"), Values.CODE);
    }

    @Override
    public Optional<String> vatAccountingCurrencyCode() {
        return Views.optional(document, TermPaths.value(path, "BT-6"), Values.CODE);
    }

    @Override
    public Optional<BigDecimal> vatAccountingCurrencyExchangeRate() {
        return Views.optional(document, TermPaths.value(path, "BT-167"), Values.AMOUNT);
    }

    @Override
    public Optional<LocalDate> taxPointDate() {
        return Views.optional(document, TermPaths.value(path, "BT-7"), Values.DATE);
    }

    @Override
    public Optional<String> taxPointDateCode() {
        return Views.optional(document, TermPaths.value(path, "BT-8"), Values.CODE);
    }

    @Override
    public Optional<LocalDate> paymentDueDate() {
        return Views.optional(document, TermPaths.value(path, "BT-9"), Values.DATE);
    }

    @Override
    public List<Identifier> buyerReference() {
        return Views.repeated(document, path, "BT-10", Values.IDENTIFIER);
    }

    @Override
    public Optional<String> projectReference() {
        return Views.optional(document, TermPaths.value(path, "BT-11"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public Optional<String> contractReference() {
        return Views.optional(document, TermPaths.value(path, "BT-12"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public Optional<String> purchaseOrderReference() {
        return Views.optional(document, TermPaths.value(path, "BT-13"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public Optional<String> salesOrderReference() {
        return Views.optional(document, TermPaths.value(path, "BT-14"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public Optional<String> receivingAdviceReference() {
        return Views.optional(document, TermPaths.value(path, "BT-15"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public Optional<String> despatchAdviceReference() {
        return Views.optional(document, TermPaths.value(path, "BT-16"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public Optional<String> deliveryNoteReference() {
        return Views.optional(document, TermPaths.value(path, "BT-197"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public Optional<String> tenderOrLotReference() {
        return Views.optional(document, TermPaths.value(path, "BT-17"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public Optional<Identifier> invoicedObjectIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-18"), Values.IDENTIFIER);
    }

    @Override
    public Optional<String> buyerAccountingReference() {
        return Views.optional(document, TermPaths.value(path, "BT-19"), Values.TEXT);
    }

    @Override
    public List<PaymentTerm> paymentTerms() {
        return Views.groups(document, path, "BG-33", PaymentTermView::new);
    }

    @Override
    public List<Note> notes() {
        return Views.groups(document, path, "BG-1", NoteView::new);
    }

    @Override
    public ProcessControl processControl() {
        return new ProcessControlView(document, TermPaths.group(path, "BG-2"));
    }

    @Override
    public List<PrecedingInvoiceReference> precedingInvoiceReferences() {
        return Views.groups(document, path, "BG-3", PrecedingInvoiceReferenceView::new);
    }

    @Override
    public Seller seller() {
        return new SellerView(document, TermPaths.group(path, "BG-4"));
    }

    @Override
    public Buyer buyer() {
        return new BuyerView(document, TermPaths.group(path, "BG-7"));
    }

    @Override
    public Optional<Payee> payee() {
        return Views.optionalGroup(document, path, "BG-10", PayeeView::new);
    }

    @Override
    public Optional<SellerTaxRepresentative> sellerTaxRepresentative() {
        return Views.optionalGroup(document, path, "BG-11", SellerTaxRepresentativeView::new);
    }

    @Override
    public Optional<Delivery> delivery() {
        return Views.optionalGroup(document, path, "BG-13", DeliveryView::new);
    }

    @Override
    public Optional<PaymentInstructions> paymentInstructions() {
        return Views.optionalGroup(document, path, "BG-16", PaymentInstructionsView::new);
    }

    @Override
    public List<DocumentLevelAllowance> documentLevelAllowances() {
        return Views.groups(document, path, "BG-20", DocumentLevelAllowanceView::new);
    }

    @Override
    public List<DocumentLevelCharge> documentLevelCharges() {
        return Views.groups(document, path, "BG-21", DocumentLevelChargeView::new);
    }

    @Override
    public DocumentTotals documentTotals() {
        return new DocumentTotalsView(document, TermPaths.group(path, "BG-22"));
    }

    @Override
    public List<VatBreakdown> vatBreakdowns() {
        return Views.groups(document, path, "BG-23", VatBreakdownView::new);
    }

    @Override
    public List<AdditionalSupportingDocument> additionalSupportingDocuments() {
        return Views.groups(document, path, "BG-24", AdditionalSupportingDocumentView::new);
    }

    @Override
    public List<InvoiceLine> invoiceLines() {
        return Views.groups(document, path, "BG-25", InvoiceLineView::new);
    }

    @Override
    public String toString() {
        return "Invoice[" + path + "]";
    }
}
