// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.MissingValueException;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.util.List;
import java.util.Optional;

/**
 * BG-31 ITEM INFORMATION. Group describing the goods or services invoiced on this line.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface Item {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-153 Item name. Name of the invoiced item.
     *
     * <p>Declared cardinality 1..1, semantic data type Text.
     *
     * @return the value of BT-153 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String name();

    /**
     * BT-154 Item description. Textual description of the invoiced item.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-154 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> description();

    /**
     * BT-155 Item Seller's identifier. Identifier the seller uses for the invoiced item.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier.
     *
     * @return the value of BT-155 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<Identifier> sellerIdentifier();

    /**
     * BT-156 Item Buyer's identifier. Identifier the buyer uses for the invoiced item.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier.
     *
     * @return the value of BT-156 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<Identifier> buyerIdentifier();

    /**
     * BT-157 Item standard identifier. Item identifier from a registered standard scheme, with a
     * mandatory scheme identifier.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the UNTDID 7143
     * list.
     *
     * @return the value of BT-157 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<Identifier> standardIdentifier();

    /**
     * BT-196 Goods/services code. Code stating whether the invoiced item concerns goods, services
     * or both.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-196 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> goodsServicesCode();

    /**
     * BT-158 Item classification identifier. Item classification code from a classification scheme,
     * with a mandatory scheme identifier and optional scheme version.
     *
     * <p>Declared cardinality 0..n, semantic data type Identifier, scheme from the UNTDID 7143
     * list.
     *
     * @return the values of BT-158 in this group instance, in the order of their occurrence
     *     indices, empty where the document carries none
     * @throws ValueTypeException if a value there is no value of that semantic data type
     */
    List<Identifier> classificationIdentifiers();

    /**
     * BT-159 Item country of origin. Country the item originates from, as an ISO 3166-1 alpha-2
     * code.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-159 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> countryOfOrigin();

    /**
     * BG-32 ITEM ATTRIBUTE. Group carrying one attribute of the invoiced item.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return one view per instance of BG-32 in this group instance, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<ItemAttribute> itemAttributes();
}
