// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.MissingValueException;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.util.Optional;

/**
 * BG-32 ITEM ATTRIBUTE. Group carrying one attribute of the invoiced item.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface ItemAttribute {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-211 Item attribute code. Code identifying the item attribute.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-211 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> code();

    /**
     * BT-160 Item attribute name. Name of the item attribute.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-160 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> name();

    /**
     * BT-161 Item attribute value. Value of the item attribute.
     *
     * <p>Declared cardinality 1..1, semantic data type Text.
     *
     * @return the value of BT-161 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String value();

    /**
     * BT-212 Item attribute value unit of measure code. Unit of measure of the item attribute
     * value.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-212 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> valueUnitCode();
}
