// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;

/**
 * BG-1 INVOICE NOTE. Group carrying free-text notes about the invoice as a whole, with an optional
 * subject code.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code NoteEditor} checks a value against the grammar of its semantic data type
 * and nothing else.
 */
public interface NoteEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-21 Invoice note subject code. Code identifying the subject of the accompanying invoice
     * note, from UNTDID 4451.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    NoteEditor subjectCode(String value);

    /**
     * BT-22 Invoice note. A free text remark about the whole document rather than about one line of
     * it.
     *
     * <p>Declared cardinality 1..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    NoteEditor note(String value);
}
