// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.util.List;
import java.util.Optional;

/**
 * BG-33 PAYMENT TERMS. Group under which the payment conditions of the invoice stand.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface PaymentTerm {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-20 Payment term text. Payment terms of the invoice as free text.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-20 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> paymentTerms();

    /**
     * BG-35 EARLY PAYMENT DISCOUNT. Group describing a discount granted for payment before the due
     * date.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return one view per instance of BG-35 in this group instance, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<EarlyPaymentDiscount> earlyPaymentDiscounts();

    /**
     * BG-36 LATE PAYMENT PENALTY. Group describing a penalty charged when payment is late.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return one view per instance of BG-36 in this group instance, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<LatePaymentPenalty> latePaymentPenalties();
}
