// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link PaymentInstructions} from a semantic document. */
final class PaymentInstructionsView implements PaymentInstructions {

    private final SemanticDocument document;
    private final SemanticPath path;

    PaymentInstructionsView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public String paymentMeansTypeCode() {
        return Views.required(document, TermPaths.value(path, "BT-81"), Values.CODE);
    }

    @Override
    public Optional<String> paymentMeansText() {
        return Views.optional(document, TermPaths.value(path, "BT-82"), Values.TEXT);
    }

    @Override
    public Optional<String> remittanceInformation() {
        return Views.optional(document, TermPaths.value(path, "BT-83"), Values.TEXT);
    }

    @Override
    public List<CreditTransfer> creditTransfers() {
        return Views.groups(document, path, "BG-17", CreditTransferView::new);
    }

    @Override
    public Optional<Card> card() {
        return Views.optionalGroup(document, path, "BG-18", CardView::new);
    }

    @Override
    public Optional<DirectDebit> directDebit() {
        return Views.optionalGroup(document, path, "BG-19", DirectDebitView::new);
    }

    @Override
    public String toString() {
        return "PaymentInstructions[" + path + "]";
    }
}
