// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link PaymentTerm} from a semantic document. */
final class PaymentTermView implements PaymentTerm {

    private final SemanticDocument document;
    private final SemanticPath path;

    PaymentTermView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public Optional<String> paymentTerms() {
        return Views.optional(document, TermPaths.value(path, "BT-20"), Values.TEXT);
    }

    @Override
    public List<EarlyPaymentDiscount> earlyPaymentDiscounts() {
        return Views.groups(document, path, "BG-35", EarlyPaymentDiscountView::new);
    }

    @Override
    public List<LatePaymentPenalty> latePaymentPenalties() {
        return Views.groups(document, path, "BG-36", LatePaymentPenaltyView::new);
    }

    @Override
    public String toString() {
        return "PaymentTerm[" + path + "]";
    }
}
