// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.EditorList;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.function.Consumer;

/**
 * BG-33 PAYMENT TERMS. Group under which the payment conditions of the invoice stand.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code PaymentTermEditor} checks a value against the grammar of its semantic data
 * type and nothing else.
 */
public interface PaymentTermEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-20 Payment term text. Payment terms of the invoice as free text.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    PaymentTermEditor paymentTerms(String value);

    /**
     * BG-35 EARLY PAYMENT DISCOUNT. Group describing a discount granted for payment before the due
     * date.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-35 in this group instance, which appends, reads,
     *     removes and empties them
     */
    EditorList<EarlyPaymentDiscountEditor> earlyPaymentDiscounts();

    /**
     * BG-35 EARLY PAYMENT DISCOUNT. Group describing a discount granted for payment before the due
     * date.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-35
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    PaymentTermEditor earlyPaymentDiscount(Consumer<EarlyPaymentDiscountEditor> block);

    /**
     * BG-36 LATE PAYMENT PENALTY. Group describing a penalty charged when payment is late.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-36 in this group instance, which appends, reads,
     *     removes and empties them
     */
    EditorList<LatePaymentPenaltyEditor> latePaymentPenalties();

    /**
     * BG-36 LATE PAYMENT PENALTY. Group describing a penalty charged when payment is late.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-36
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    PaymentTermEditor latePaymentPenalty(Consumer<LatePaymentPenaltyEditor> block);
}
