// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.EditorList;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.Objects;
import java.util.function.Consumer;

/** Writes {@link PaymentInstructionsEditor} into a document builder. */
final class PaymentInstructionsEdit implements PaymentInstructionsEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    PaymentInstructionsEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public PaymentInstructionsEditor paymentMeansTypeCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-81"), value, Writers.CODE);
        return this;
    }

    @Override
    public PaymentInstructionsEditor paymentMeansText(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-82"), value, Writers.TEXT);
        return this;
    }

    @Override
    public PaymentInstructionsEditor remittanceInformation(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-83"), value, Writers.TEXT);
        return this;
    }

    @Override
    public EditorList<CreditTransferEditor> creditTransfers() {
        return Editors.groups(builder, path, "BG-17", CreditTransferEdit::new);
    }

    @Override
    public PaymentInstructionsEditor creditTransfer(Consumer<CreditTransferEditor> block) {
        creditTransfers().add(block);
        return this;
    }

    @Override
    public CardEditor card() {
        return new CardEdit(builder, TermPaths.group(path, "BG-18"));
    }

    @Override
    public PaymentInstructionsEditor card(Consumer<CardEditor> block) {
        Objects.requireNonNull(block, "block").accept(card());
        return this;
    }

    @Override
    public DirectDebitEditor directDebit() {
        return new DirectDebitEdit(builder, TermPaths.group(path, "BG-19"));
    }

    @Override
    public PaymentInstructionsEditor directDebit(Consumer<DirectDebitEditor> block) {
        Objects.requireNonNull(block, "block").accept(directDebit());
        return this;
    }

    @Override
    public String toString() {
        return "PaymentInstructionsEditor[" + path + "]";
    }
}
