// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;

/**
 * BG-29 PRICE DETAILS. Group carrying the price information for the item on this invoice line.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code PriceEditor} checks a value against the grammar of its semantic data type
 * and nothing else.
 */
public interface PriceEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-146 Item net price. Price of one item unit excluding VAT, after subtracting the item price
     * discount.
     *
     * <p>Declared cardinality 1..1, semantic data type UnitPriceAmount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    PriceEditor netPrice(BigDecimal value);

    /**
     * BT-147 Item price discount. Discount subtracted from the item gross price to arrive at the
     * item net price.
     *
     * <p>Declared cardinality 0..1, semantic data type UnitPriceAmount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    PriceEditor discount(BigDecimal value);

    /**
     * BT-148 Item gross price. Unit price excluding VAT before the item price discount is
     * subtracted.
     *
     * <p>Declared cardinality 0..1, semantic data type UnitPriceAmount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    PriceEditor grossPrice(BigDecimal value);

    /**
     * BT-149 Item price base quantity. Number of item units the item price applies to.
     *
     * <p>Declared cardinality 0..1, semantic data type Quantity.
     *
     * @param value the quantity, or {@code null} to remove it
     * @param unitCode the unit of measure of that quantity, written to BT-150, or {@code null} or
     *     the empty string to remove it
     * @return this editor
     */
    PriceEditor baseQuantity(BigDecimal value, String unitCode);

    /**
     * BT-149 Item price base quantity. Number of item units the item price applies to.
     *
     * <p>Declared cardinality 0..1, semantic data type Quantity.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    PriceEditor baseQuantity(BigDecimal value);

    /**
     * BT-150 Item price base quantity unit of measure code. Unit of measure code for the item price
     * base quantity; must match the invoiced quantity unit.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    PriceEditor baseQuantityUnitCode(String value);
}
