// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.MissingValueException;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.math.BigDecimal;
import java.util.Optional;

/**
 * BG-29 PRICE DETAILS. Group carrying the price information for the item on this invoice line.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface Price {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-146 Item net price. Price of one item unit excluding VAT, after subtracting the item price
     * discount.
     *
     * <p>Declared cardinality 1..1, semantic data type UnitPriceAmount.
     *
     * @return the value of BT-146 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal netPrice();

    /**
     * BT-147 Item price discount. Discount subtracted from the item gross price to arrive at the
     * item net price.
     *
     * <p>Declared cardinality 0..1, semantic data type UnitPriceAmount.
     *
     * @return the value of BT-147 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> discount();

    /**
     * BT-148 Item gross price. Unit price excluding VAT before the item price discount is
     * subtracted.
     *
     * <p>Declared cardinality 0..1, semantic data type UnitPriceAmount.
     *
     * @return the value of BT-148 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> grossPrice();

    /**
     * BT-149 Item price base quantity. Number of item units the item price applies to.
     *
     * <p>Declared cardinality 0..1, semantic data type Quantity.
     *
     * @return the value of BT-149 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> baseQuantity();

    /**
     * BT-150 Item price base quantity unit of measure code. Unit of measure code for the item price
     * base quantity; must match the invoiced quantity unit.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-150 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> baseQuantityUnitCode();
}
