// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link Seller} from a semantic document. */
final class SellerView implements Seller {

    private final SemanticDocument document;
    private final SemanticPath path;

    SellerView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public String name() {
        return Views.required(document, TermPaths.value(path, "BT-27"), Values.TEXT);
    }

    @Override
    public Optional<String> tradingName() {
        return Views.optional(document, TermPaths.value(path, "BT-28"), Values.TEXT);
    }

    @Override
    public List<Identifier> identifiers() {
        return Views.repeated(document, path, "BT-29", Values.IDENTIFIER);
    }

    @Override
    public Optional<Identifier> legalRegistrationIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-30"), Values.IDENTIFIER);
    }

    @Override
    public Optional<Identifier> vatIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-31"), Values.IDENTIFIER);
    }

    @Override
    public Optional<Identifier> taxRegistrationIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-32"), Values.IDENTIFIER);
    }

    @Override
    public Optional<String> additionalLegalInformation() {
        return Views.optional(document, TermPaths.value(path, "BT-33"), Values.TEXT);
    }

    @Override
    public Optional<Identifier> electronicAddress() {
        return Views.optional(document, TermPaths.value(path, "BT-34"), Values.IDENTIFIER);
    }

    @Override
    public SellerPostalAddress postalAddress() {
        return new SellerPostalAddressView(document, TermPaths.group(path, "BG-5"));
    }

    @Override
    public Optional<SellerContact> contact() {
        return Views.optionalGroup(document, path, "BG-6", SellerContactView::new);
    }

    @Override
    public String toString() {
        return "Seller[" + path + "]";
    }
}
