// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.Objects;

/** Writes {@link SellerTaxRepresentativePostalAddressEditor} into a document builder. */
final class SellerTaxRepresentativePostalAddressEdit implements SellerTaxRepresentativePostalAddressEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    SellerTaxRepresentativePostalAddressEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public SellerTaxRepresentativePostalAddressEditor addressLine1(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-64"), value, Writers.TEXT);
        return this;
    }

    @Override
    public SellerTaxRepresentativePostalAddressEditor addressLine2(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-65"), value, Writers.TEXT);
        return this;
    }

    @Override
    public SellerTaxRepresentativePostalAddressEditor addressLine3(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-164"), value, Writers.TEXT);
        return this;
    }

    @Override
    public SellerTaxRepresentativePostalAddressEditor city(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-66"), value, Writers.TEXT);
        return this;
    }

    @Override
    public SellerTaxRepresentativePostalAddressEditor postCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-67"), value, Writers.TEXT);
        return this;
    }

    @Override
    public SellerTaxRepresentativePostalAddressEditor countrySubdivision(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-68"), value, Writers.TEXT);
        return this;
    }

    @Override
    public SellerTaxRepresentativePostalAddressEditor countryCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-69"), value, Writers.CODE);
        return this;
    }

    @Override
    public String toString() {
        return "SellerTaxRepresentativePostalAddressEditor[" + path + "]";
    }
}
