// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.Identifier;
import de.bsnsoft.esj.typed.SchemedIdentifierList;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.function.Consumer;

/**
 * BG-4 SELLER. Group carrying the information about the seller.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code SellerEditor} checks a value against the grammar of its semantic data type
 * and nothing else.
 */
public interface SellerEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-27 Seller name. Full name of the seller as registered in the national register of legal
     * entities.
     *
     * <p>Declared cardinality 1..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    SellerEditor name(String value);

    /**
     * BT-28 Seller trading name. Name the seller is known by, where different from the registered
     * seller name.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    SellerEditor tradingName(String value);

    /**
     * BT-29 Seller identifier. Identification of the seller, with an identification scheme
     * identifier.
     *
     * <p>Declared cardinality 0..n, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @return the handle of the occurrences of BT-29 in this group instance, which appends, reads,
     *     removes and empties them
     */
    SchemedIdentifierList identifiers();

    /**
     * BT-30 Seller legal registration identifier. Identifier issued to the seller by an official
     * registrar of legal entities.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value
     * @param scheme the identification scheme, a code of the ISO 6523 ICD list
     * @return this editor
     */
    SellerEditor legalRegistrationIdentifier(String value, String scheme);

    /**
     * BT-30 Seller legal registration identifier. Identifier issued to the seller by an official
     * registrar of legal entities.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value. The registry declares the
     *     scheme of BT-30 mandatory, and this overload writes the identifier as it stands: one that
     *     carries no scheme is written and reported at validation layer L2, not refused here
     * @return this editor
     */
    SellerEditor legalRegistrationIdentifier(Identifier value);

    /**
     * BT-31 Seller VAT identifier. VAT identifier assigned to the seller.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value; where
     *     the argument is the literal {@code null}, Java cannot choose between this overload and
     *     the one taking an {@code Identifier}, so write {@code (String) null} or the empty string
     *     instead
     * @return this editor
     */
    SellerEditor vatIdentifier(String value);

    /**
     * BT-31 Seller VAT identifier. VAT identifier assigned to the seller.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value; where the argument is the
     *     literal {@code null}, Java cannot choose between this overload and the one taking a
     *     string, so write {@code (Identifier) null} or the empty string instead
     * @return this editor
     */
    SellerEditor vatIdentifier(Identifier value);

    /**
     * BT-32 Seller tax registration identifier. Local identification of the seller assigned by its
     * tax authority or a certifier, other than the VAT identifier.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value; where
     *     the argument is the literal {@code null}, Java cannot choose between this overload and
     *     the one taking an {@code Identifier}, so write {@code (String) null} or the empty string
     *     instead
     * @return this editor
     */
    SellerEditor taxRegistrationIdentifier(String value);

    /**
     * BT-32 Seller tax registration identifier. Local identification of the seller assigned by its
     * tax authority or a certifier, other than the VAT identifier.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value
     * @param scheme the identification scheme, a code of the ISO 6523 ICD list
     * @return this editor
     */
    SellerEditor taxRegistrationIdentifier(String value, String scheme);

    /**
     * BT-32 Seller tax registration identifier. Local identification of the seller assigned by its
     * tax authority or a certifier, other than the VAT identifier.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value; where the argument is the
     *     literal {@code null}, Java cannot choose between this overload and the one taking a
     *     string, so write {@code (Identifier) null} or the empty string instead
     * @return this editor
     */
    SellerEditor taxRegistrationIdentifier(Identifier value);

    /**
     * BT-33 Seller additional legal information. Additional legal information about the seller that
     * is relevant for the buyer.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    SellerEditor additionalLegalInformation(String value);

    /**
     * BT-34 Seller electronic address. Electronic address of the seller, with a mandatory scheme
     * identifier saying which address scheme is used.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the CEF EAS list.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value
     * @param scheme the identification scheme, a code of the CEF EAS list
     * @return this editor
     */
    SellerEditor electronicAddress(String value, String scheme);

    /**
     * BT-34 Seller electronic address. Electronic address of the seller, with a mandatory scheme
     * identifier saying which address scheme is used.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the CEF EAS list.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value. The registry declares the
     *     scheme of BT-34 mandatory, and this overload writes the identifier as it stands: one that
     *     carries no scheme is written and reported at validation layer L2, not refused here
     * @return this editor
     */
    SellerEditor electronicAddress(Identifier value);

    /**
     * BG-5 SELLER POSTAL ADDRESS. Group carrying the seller's postal address.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the editor of the instance of BG-5 in this group instance; the group comes into being
     *     when a value is written into it, so an editor that is not written into leaves nothing
     *     behind
     */
    SellerPostalAddressEditor postalAddress();

    /**
     * BG-5 SELLER POSTAL ADDRESS. Group carrying the seller's postal address.
     *
     * <p>Declared cardinality 1..1.
     *
     * @param block what to write into the instance of BG-5
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    SellerEditor postalAddress(Consumer<SellerPostalAddressEditor> block);

    /**
     * BG-6 SELLER CONTACT. Group carrying the seller's contact details.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the editor of the instance of BG-6 in this group instance; the group comes into being
     *     when a value is written into it, so an editor that is not written into leaves nothing
     *     behind
     */
    SellerContactEditor contact();

    /**
     * BG-6 SELLER CONTACT. Group carrying the seller's contact details.
     *
     * <p>Declared cardinality 0..1.
     *
     * @param block what to write into the instance of BG-6
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    SellerEditor contact(Consumer<SellerContactEditor> block);
}
