// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.MissingValueException;
import de.bsnsoft.esj.typed.ValueTypeException;
import java.math.BigDecimal;

/**
 * BG-34 CHARGES ON BEHALF OF A THIRD PARTY. Group for charges that the seller collects on behalf of
 * a third party.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface ThirdPartyCharge {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-179 Charge amount collected on behalf of a third party. What BG-34 collects for somebody
     * else, VAT included.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @return the value of BT-179 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal amount();

    /**
     * BT-180 Charges specification. Free text saying what the charge of BG-34 is for.
     *
     * <p>Declared cardinality 1..1, semantic data type Text.
     *
     * @return the value of BT-180 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String specification();
}
