// Generated by esj-generator from EN16931 registry
// EN 16931-1:2026, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed.v2026;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;

/**
 * BG-30 LINE VAT INFORMATION. Group carrying the VAT information that applies to the item on this
 * invoice line.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code VatEditor} checks a value against the grammar of its semantic data type
 * and nothing else.
 */
public interface VatEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-151 Invoiced item VAT category code. VAT category code that applies to the invoiced item,
     * from UNTDID 5305.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    VatEditor vatCategoryCode(String value);

    /**
     * BT-152 Invoiced item VAT rate. VAT rate that applies to the invoiced item, as a percentage.
     *
     * <p>Declared cardinality 0..1, semantic data type Percentage.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    VatEditor vatRate(BigDecimal value);

    /**
     * BT-194 Invoiced item exemption reason text. Reason, as text, why the invoiced item carries no
     * VAT.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    VatEditor exemptionReasonText(String value);

    /**
     * BT-195 Invoiced item VAT exemption reason and specification code. Coded reason why the
     * invoiced item carries no VAT.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    VatEditor exemptionReasonCode(String value);
}
