// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link AdditionalSupportingDocument} from a semantic document. */
final class AdditionalSupportingDocumentView implements AdditionalSupportingDocument {

    private final SemanticDocument document;
    private final SemanticPath path;

    AdditionalSupportingDocumentView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public String reference() {
        return Views.required(document, TermPaths.value(path, "BT-122"), Values.DOCUMENT_REFERENCE);
    }

    @Override
    public Optional<String> description() {
        return Views.optional(document, TermPaths.value(path, "BT-123"), Values.TEXT);
    }

    @Override
    public Optional<String> externalLocation() {
        return Views.optional(document, TermPaths.value(path, "BT-124"), Values.TEXT);
    }

    @Override
    public Optional<BinaryObject> attachment() {
        return Views.optional(document, TermPaths.value(path, "BT-125"), Values.BINARY_OBJECT);
    }

    @Override
    public String toString() {
        return "AdditionalSupportingDocument[" + path + "]";
    }
}
