// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;

/**
 * BG-24 ADDITIONAL SUPPORTING DOCUMENTS. Group referencing a supporting document that backs the
 * claims made in the invoice.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code AdditionalSupportingDocumentEditor} checks a value against the grammar of
 * its semantic data type and nothing else.
 */
public interface AdditionalSupportingDocumentEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-122 Supporting document reference. Reference that identifies the supporting document.
     *
     * <p>Declared cardinality 1..1, semantic data type DocumentReference.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    AdditionalSupportingDocumentEditor reference(String value);

    /**
     * BT-123 Supporting document description. Textual description of the supporting document.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    AdditionalSupportingDocumentEditor description(String value);

    /**
     * BT-124 External document location. Internet address where the external supporting document
     * can be retrieved.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    AdditionalSupportingDocumentEditor externalLocation(String value);

    /**
     * BT-125 Attached document. Supporting document embedded in the invoice as a binary object,
     * with mime code and file name.
     *
     * <p>Declared cardinality 0..1, semantic data type BinaryObject.
     *
     * @param bytes the content of the file, or {@code null} or an empty array to remove the value
     * @param mimeCode the media type of the file
     * @param filename the file name of the file
     * @return this editor
     */
    AdditionalSupportingDocumentEditor attachment(byte[] bytes, String mimeCode, String filename);

    /**
     * BT-125 Attached document. Supporting document embedded in the invoice as a binary object,
     * with mime code and file name.
     *
     * <p>Declared cardinality 0..1, semantic data type BinaryObject.
     *
     * @param value the file as the view of another document hands it over, or {@code null} or an
     *     empty file to remove the value
     * @return this editor
     */
    AdditionalSupportingDocumentEditor attachment(BinaryObject value);
}
