// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.Objects;

/** Writes {@link AddressEditor} into a document builder. */
final class AddressEdit implements AddressEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    AddressEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public AddressEditor addressLine1(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-75"), value, Writers.TEXT);
        return this;
    }

    @Override
    public AddressEditor addressLine2(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-76"), value, Writers.TEXT);
        return this;
    }

    @Override
    public AddressEditor addressLine3(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-165"), value, Writers.TEXT);
        return this;
    }

    @Override
    public AddressEditor city(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-77"), value, Writers.TEXT);
        return this;
    }

    @Override
    public AddressEditor postCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-78"), value, Writers.TEXT);
        return this;
    }

    @Override
    public AddressEditor countrySubdivision(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-79"), value, Writers.TEXT);
        return this;
    }

    @Override
    public AddressEditor countryCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-80"), value, Writers.CODE);
        return this;
    }

    @Override
    public String toString() {
        return "AddressEditor[" + path + "]";
    }
}
