// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link Address} from a semantic document. */
final class AddressView implements Address {

    private final SemanticDocument document;
    private final SemanticPath path;

    AddressView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public Optional<String> addressLine1() {
        return Views.optional(document, TermPaths.value(path, "BT-75"), Values.TEXT);
    }

    @Override
    public Optional<String> addressLine2() {
        return Views.optional(document, TermPaths.value(path, "BT-76"), Values.TEXT);
    }

    @Override
    public Optional<String> addressLine3() {
        return Views.optional(document, TermPaths.value(path, "BT-165"), Values.TEXT);
    }

    @Override
    public Optional<String> city() {
        return Views.optional(document, TermPaths.value(path, "BT-77"), Values.TEXT);
    }

    @Override
    public Optional<String> postCode() {
        return Views.optional(document, TermPaths.value(path, "BT-78"), Values.TEXT);
    }

    @Override
    public Optional<String> countrySubdivision() {
        return Views.optional(document, TermPaths.value(path, "BT-79"), Values.TEXT);
    }

    @Override
    public String countryCode() {
        return Views.required(document, TermPaths.value(path, "BT-80"), Values.CODE);
    }

    @Override
    public String toString() {
        return "Address[" + path + "]";
    }
}
