// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import java.math.BigDecimal;
import java.util.Optional;

/**
 * BG-27 INVOICE LINE ALLOWANCES. Group carrying an allowance that applies to this invoice line.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface Allowance {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-136 Invoice line allowance amount. Amount of the invoice line allowance, without VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @return the value of BT-136 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal amount();

    /**
     * BT-137 Invoice line allowance base amount. Base amount the invoice line allowance percentage
     * is applied to.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @return the value of BT-137 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> baseAmount();

    /**
     * BT-138 Invoice line allowance percentage. Percentage applied to the base amount to derive the
     * invoice line allowance amount.
     *
     * <p>Declared cardinality 0..1, semantic data type Percentage.
     *
     * @return the value of BT-138 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> percentage();

    /**
     * BT-139 Invoice line allowance reason. Textual reason for the invoice line allowance.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-139 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> reason();

    /**
     * BT-140 Invoice line allowance reason code. Coded reason for the invoice line allowance, from
     * UNTDID 5189.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-140 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> reasonCode();
}
