// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.Objects;
import java.util.function.Consumer;

/** Writes {@link BuyerEditor} into a document builder. */
final class BuyerEdit implements BuyerEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    BuyerEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public BuyerEditor name(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-44"), value, Writers.TEXT);
        return this;
    }

    @Override
    public BuyerEditor tradingName(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-45"), value, Writers.TEXT);
        return this;
    }

    @Override
    public BuyerEditor identifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-46"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public BuyerEditor identifier(String value, String scheme) {
        Editors.set(builder, TermPaths.value(path, "BT-46"), Editors.identifier(value, scheme, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public BuyerEditor identifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-46"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public BuyerEditor legalRegistrationIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-47"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public BuyerEditor legalRegistrationIdentifier(String value, String scheme) {
        Editors.set(builder, TermPaths.value(path, "BT-47"), Editors.identifier(value, scheme, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public BuyerEditor legalRegistrationIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-47"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public BuyerEditor vatIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-48"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public BuyerEditor vatIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-48"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public BuyerEditor electronicAddress(String value, String scheme) {
        Editors.set(builder, TermPaths.value(path, "BT-49"), Editors.identifier(value, scheme, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public BuyerEditor electronicAddress(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-49"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public BuyerPostalAddressEditor postalAddress() {
        return new BuyerPostalAddressEdit(builder, TermPaths.group(path, "BG-8"));
    }

    @Override
    public BuyerEditor postalAddress(Consumer<BuyerPostalAddressEditor> block) {
        Objects.requireNonNull(block, "block").accept(postalAddress());
        return this;
    }

    @Override
    public BuyerContactEditor contact() {
        return new BuyerContactEdit(builder, TermPaths.group(path, "BG-9"));
    }

    @Override
    public BuyerEditor contact(Consumer<BuyerContactEditor> block) {
        Objects.requireNonNull(block, "block").accept(contact());
        return this;
    }

    @Override
    public String toString() {
        return "BuyerEditor[" + path + "]";
    }
}
