// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link Buyer} from a semantic document. */
final class BuyerView implements Buyer {

    private final SemanticDocument document;
    private final SemanticPath path;

    BuyerView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public String name() {
        return Views.required(document, TermPaths.value(path, "BT-44"), Values.TEXT);
    }

    @Override
    public Optional<String> tradingName() {
        return Views.optional(document, TermPaths.value(path, "BT-45"), Values.TEXT);
    }

    @Override
    public Optional<Identifier> identifier() {
        return Views.optional(document, TermPaths.value(path, "BT-46"), Values.IDENTIFIER);
    }

    @Override
    public Optional<Identifier> legalRegistrationIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-47"), Values.IDENTIFIER);
    }

    @Override
    public Optional<Identifier> vatIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-48"), Values.IDENTIFIER);
    }

    @Override
    public Optional<Identifier> electronicAddress() {
        return Views.optional(document, TermPaths.value(path, "BT-49"), Values.IDENTIFIER);
    }

    @Override
    public BuyerPostalAddress postalAddress() {
        return new BuyerPostalAddressView(document, TermPaths.group(path, "BG-8"));
    }

    @Override
    public Optional<BuyerContact> contact() {
        return Views.optionalGroup(document, path, "BG-9", BuyerContactView::new);
    }

    @Override
    public String toString() {
        return "Buyer[" + path + "]";
    }
}
