// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link Card} from a semantic document. */
final class CardView implements Card {

    private final SemanticDocument document;
    private final SemanticPath path;

    CardView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public String primaryAccountNumber() {
        return Views.required(document, TermPaths.value(path, "BT-87"), Values.TEXT);
    }

    @Override
    public Optional<String> holderName() {
        return Views.optional(document, TermPaths.value(path, "BT-88"), Values.TEXT);
    }

    @Override
    public String toString() {
        return "Card[" + path + "]";
    }
}
