// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.math.BigDecimal;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link Charge} from a semantic document. */
final class ChargeView implements Charge {

    private final SemanticDocument document;
    private final SemanticPath path;

    ChargeView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public BigDecimal amount() {
        return Views.required(document, TermPaths.value(path, "BT-141"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> baseAmount() {
        return Views.optional(document, TermPaths.value(path, "BT-142"), Values.AMOUNT);
    }

    @Override
    public Optional<BigDecimal> percentage() {
        return Views.optional(document, TermPaths.value(path, "BT-143"), Values.PERCENTAGE);
    }

    @Override
    public Optional<String> reason() {
        return Views.optional(document, TermPaths.value(path, "BT-144"), Values.TEXT);
    }

    @Override
    public Optional<String> reasonCode() {
        return Views.optional(document, TermPaths.value(path, "BT-145"), Values.CODE);
    }

    @Override
    public String toString() {
        return "Charge[" + path + "]";
    }
}
