// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link CreditTransfer} from a semantic document. */
final class CreditTransferView implements CreditTransfer {

    private final SemanticDocument document;
    private final SemanticPath path;

    CreditTransferView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public Identifier accountIdentifier() {
        return Views.required(document, TermPaths.value(path, "BT-84"), Values.IDENTIFIER);
    }

    @Override
    public Optional<String> accountName() {
        return Views.optional(document, TermPaths.value(path, "BT-85"), Values.TEXT);
    }

    @Override
    public Optional<Identifier> serviceProviderIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-86"), Values.IDENTIFIER);
    }

    @Override
    public String toString() {
        return "CreditTransfer[" + path + "]";
    }
}
