// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.time.LocalDate;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link Delivery} from a semantic document. */
final class DeliveryView implements Delivery {

    private final SemanticDocument document;
    private final SemanticPath path;

    DeliveryView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public Optional<String> partyName() {
        return Views.optional(document, TermPaths.value(path, "BT-70"), Values.TEXT);
    }

    @Override
    public Optional<Identifier> locationIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-71"), Values.IDENTIFIER);
    }

    @Override
    public Optional<LocalDate> actualDeliveryDate() {
        return Views.optional(document, TermPaths.value(path, "BT-72"), Values.DATE);
    }

    @Override
    public Optional<InvoicingPeriod> invoicingPeriod() {
        return Views.optionalGroup(document, path, "BG-14", InvoicingPeriodView::new);
    }

    @Override
    public Optional<Address> address() {
        return Views.optionalGroup(document, path, "BG-15", AddressView::new);
    }

    @Override
    public String toString() {
        return "Delivery[" + path + "]";
    }
}
