// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import java.math.BigDecimal;
import java.util.Optional;

/**
 * BG-22 DOCUMENT TOTALS. Group carrying the monetary totals of the invoice.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface DocumentTotals {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-106 Sum of Invoice line net amount. Total of the net amounts of all invoice lines.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @return the value of BT-106 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal sumOfLineNetAmounts();

    /**
     * BT-107 Sum of allowances on document level. Sum of all document level allowance amounts.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @return the value of BT-107 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> sumOfAllowances();

    /**
     * BT-108 Sum of charges on document level. Sum of all document level charge amounts.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @return the value of BT-108 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> sumOfCharges();

    /**
     * BT-109 Invoice total amount without VAT. Total invoice amount excluding VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @return the value of BT-109 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal totalWithoutVat();

    /**
     * BT-110 Invoice total VAT amount. Total VAT amount of the invoice.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @return the value of BT-110 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> totalVatAmount();

    /**
     * BT-111 Invoice total VAT amount in accounting currency. Total VAT amount expressed in the VAT
     * accounting currency.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @return the value of BT-111 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> totalVatAmountInAccountingCurrency();

    /**
     * BT-112 Invoice total amount with VAT. Total invoice amount including VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @return the value of BT-112 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal totalWithVat();

    /**
     * BT-113 Paid amount. Amount already paid in advance for this invoice.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @return the value of BT-113 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> paidAmount();

    /**
     * BT-114 Rounding amount. Amount added to round the amount due for payment.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @return the value of BT-114 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> roundingAmount();

    /**
     * BT-115 Amount due for payment. Outstanding amount still to be paid.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @return the value of BT-115 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal amountDueForPayment();
}
