// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.util.Objects;

/** Writes {@link DocumentTotalsEditor} into a document builder. */
final class DocumentTotalsEdit implements DocumentTotalsEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    DocumentTotalsEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public DocumentTotalsEditor sumOfLineNetAmounts(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-106"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentTotalsEditor sumOfAllowances(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-107"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentTotalsEditor sumOfCharges(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-108"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentTotalsEditor totalWithoutVat(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-109"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentTotalsEditor totalVatAmount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-110"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentTotalsEditor totalVatAmountInAccountingCurrency(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-111"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentTotalsEditor totalWithVat(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-112"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentTotalsEditor paidAmount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-113"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentTotalsEditor roundingAmount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-114"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public DocumentTotalsEditor amountDueForPayment(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-115"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public String toString() {
        return "DocumentTotalsEditor[" + path + "]";
    }
}
