// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;

/**
 * BG-22 DOCUMENT TOTALS. Group carrying the monetary totals of the invoice.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code DocumentTotalsEditor} checks a value against the grammar of its semantic
 * data type and nothing else.
 */
public interface DocumentTotalsEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-106 Sum of Invoice line net amount. Total of the net amounts of all invoice lines.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentTotalsEditor sumOfLineNetAmounts(BigDecimal value);

    /**
     * BT-107 Sum of allowances on document level. Sum of all document level allowance amounts.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentTotalsEditor sumOfAllowances(BigDecimal value);

    /**
     * BT-108 Sum of charges on document level. Sum of all document level charge amounts.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentTotalsEditor sumOfCharges(BigDecimal value);

    /**
     * BT-109 Invoice total amount without VAT. Total invoice amount excluding VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentTotalsEditor totalWithoutVat(BigDecimal value);

    /**
     * BT-110 Invoice total VAT amount. Total VAT amount of the invoice.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentTotalsEditor totalVatAmount(BigDecimal value);

    /**
     * BT-111 Invoice total VAT amount in accounting currency. Total VAT amount expressed in the VAT
     * accounting currency.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentTotalsEditor totalVatAmountInAccountingCurrency(BigDecimal value);

    /**
     * BT-112 Invoice total amount with VAT. Total invoice amount including VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentTotalsEditor totalWithVat(BigDecimal value);

    /**
     * BT-113 Paid amount. Amount already paid in advance for this invoice.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentTotalsEditor paidAmount(BigDecimal value);

    /**
     * BT-114 Rounding amount. Amount added to round the amount due for payment.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentTotalsEditor roundingAmount(BigDecimal value);

    /**
     * BT-115 Amount due for payment. Outstanding amount still to be paid.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @param value the value to write, or {@code null} to remove the value
     * @return this editor
     */
    DocumentTotalsEditor amountDueForPayment(BigDecimal value);
}
