// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import java.math.BigDecimal;
import java.util.Optional;

/**
 * BG-21 DOCUMENT LEVEL CHARGES. Group carrying a charge (cost or non-VAT tax) that applies to the
 * invoice as a whole.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface DocumentLevelCharge {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-99 Document level charge amount. Amount of the document level charge, without VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @return the value of BT-99 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal amount();

    /**
     * BT-100 Document level charge base amount. Base amount the document level charge percentage is
     * applied to.
     *
     * <p>Declared cardinality 0..1, semantic data type Amount.
     *
     * @return the value of BT-100 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> baseAmount();

    /**
     * BT-101 Document level charge percentage. Percentage applied to the base amount to derive the
     * document level charge amount.
     *
     * <p>Declared cardinality 0..1, semantic data type Percentage.
     *
     * @return the value of BT-101 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> percentage();

    /**
     * BT-102 Document level charge VAT category code. VAT category code that applies to the
     * document level charge.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @return the value of BT-102 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String vatCategoryCode();

    /**
     * BT-103 Document level charge VAT rate. VAT rate that applies to the document level charge, as
     * a percentage.
     *
     * <p>Declared cardinality 0..1, semantic data type Percentage.
     *
     * @return the value of BT-103 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> vatRate();

    /**
     * BT-104 Document level charge reason. Textual reason for the document level charge.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-104 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> reason();

    /**
     * BT-105 Document level charge reason code. Coded reason for the document level charge, from
     * UNTDID 7161.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-105 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> reasonCode();
}
