// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import java.util.Objects;

/**
 * The entry point of the typed view of EN 16931-1:2017+A1:2019/AC:2020: it turns a semantic
 * document of that edition into an {@link Invoice} for reading, and opens an {@link InvoiceEditor}
 * for writing.
 *
 * <p>A view of one edition reads a document of that edition. A path is an address relative to an
 * edition (specification, section 10), so the same path may be two different terms under two
 * editions, and a document whose {@code semanticModel} names another one is read through the entry
 * point of that edition's package instead. Nothing here looks at {@code semanticModel}: this view
 * is what a caller reaches for once they know which edition they are holding.
 *
 * <p>The view reads the document; it neither copies nor validates it. A document that fails
 * validation layer L2 or L3 can still be viewed, and the view reports what it finds: a mandatory
 * term that is absent throws {@link MissingValueException} when it is asked for, and a content that
 * is no value of the semantic data type the registry records for its term throws {@link
 * ValueTypeException}. Use {@code de.bsnsoft.esj.validate.StructuralValidator} to learn about those
 * defects before reading.
 */
public final class En16931 {

    /**
     * The {@code semanticModel} a document of this edition carries (specification, section 10): the
     * edition of the registry this view was generated from, with the spaces taken out.
     */
    public static final String SEMANTIC_MODEL = "EN16931-1:2017+A1:2019/AC:2020";

    private En16931() {
    }

    /**
     * Returns a typed view over a document.
     *
     * <p>A view is a reader, and a reader is blind to the edition by construction: it hands out
     * what the document carries at the paths this edition gives its terms, and it looks at {@code
     * semanticModel} no more than a canonicalizer does. Handing it a document of another edition is
     * therefore not refused here and not sensible either — the terms that moved between the two
     * editions are read as absent — so the edition is the caller's to know, and {@link
     * #SEMANTIC_MODEL} is what they compare against.
     *
     * @param document the document to read
     * @return a view over the root of the document
     * @throws NullPointerException if {@code document} is {@code null}
     */
    public static Invoice view(SemanticDocument document) {
        return new InvoiceView(Objects.requireNonNull(document, "document"), SemanticPath.root());
    }

    /**
     * Opens an editor over an empty invoice of EN 16931-1:2017+A1:2019/AC:2020. The document it
     * builds names that edition, because the paths this editor writes are that edition's paths.
     *
     * <p>Nothing exists until something is written: a business group comes into being the moment a
     * value is written into it (specification, section 4.5), so an editor that is only looked at
     * produces an empty document. {@link InvoiceEditor#document()} returns what has been written so
     * far, in canonical path order.
     *
     * @return an editor over a new document
     */
    public static InvoiceEditor newInvoice() {
        return new InvoiceEdit(SemanticDocument.builder().semanticModel(SEMANTIC_MODEL),
                SemanticPath.root());
    }

    /**
     * Opens an editor over a copy of an existing document. The document itself is immutable and is
     * not touched; the editor writes into a builder seeded with its content, and {@link
     * InvoiceEditor#document()} returns the changed copy.
     *
     * <p>An editor is a writer, and a writer knows its edition: a document naming another one is
     * refused rather than written into, because every setter here writes a path of this edition,
     * and a document whose paths and whose {@code semanticModel} disagree is one no validator can
     * make sense of. Use {@code esj upgrade} or the entry point of the document's own edition.
     *
     * @param document the document to change
     * @return an editor over a copy of it
     * @throws IllegalArgumentException if the document names another edition than {@link
     *     #SEMANTIC_MODEL}
     * @throws NullPointerException if {@code document} is {@code null}
     */
    public static InvoiceEditor edit(SemanticDocument document) {
        Objects.requireNonNull(document, "document");
        if (!SEMANTIC_MODEL.equals(document.semanticModel())) {
            throw new IllegalArgumentException("this editor writes "
                    + SEMANTIC_MODEL + " and the document names "
                    + document.semanticModel());
        }
        return new InvoiceEdit(document.toBuilder(), SemanticPath.root());
    }
}
