// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.time.LocalDate;
import java.util.Objects;
import java.util.function.Consumer;

/** Writes {@link InvoiceEditor} into a document builder. */
final class InvoiceEdit implements InvoiceEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    InvoiceEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public InvoiceEditor invoiceNumber(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-1"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceEditor invoiceNumber(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-1"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceEditor issueDate(LocalDate value) {
        Editors.set(builder, TermPaths.value(path, "BT-2"), value, Writers.DATE);
        return this;
    }

    @Override
    public InvoiceEditor typeCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-3"), value, Writers.CODE);
        return this;
    }

    @Override
    public InvoiceEditor currencyCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-5"), value, Writers.CODE);
        return this;
    }

    @Override
    public InvoiceEditor vatAccountingCurrencyCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-6"), value, Writers.CODE);
        return this;
    }

    @Override
    public InvoiceEditor taxPointDate(LocalDate value) {
        Editors.set(builder, TermPaths.value(path, "BT-7"), value, Writers.DATE);
        return this;
    }

    @Override
    public InvoiceEditor taxPointDateCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-8"), value, Writers.CODE);
        return this;
    }

    @Override
    public InvoiceEditor paymentDueDate(LocalDate value) {
        Editors.set(builder, TermPaths.value(path, "BT-9"), value, Writers.DATE);
        return this;
    }

    @Override
    public InvoiceEditor buyerReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-10"), value, Writers.TEXT);
        return this;
    }

    @Override
    public InvoiceEditor projectReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-11"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceEditor contractReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-12"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceEditor purchaseOrderReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-13"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceEditor salesOrderReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-14"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceEditor receivingAdviceReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-15"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceEditor despatchAdviceReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-16"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceEditor tenderOrLotReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-17"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public InvoiceEditor invoicedObjectIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-18"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceEditor invoicedObjectIdentifier(String value, String scheme) {
        Editors.set(builder, TermPaths.value(path, "BT-18"), Editors.identifier(value, scheme, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceEditor invoicedObjectIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-18"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public InvoiceEditor buyerAccountingReference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-19"), value, Writers.TEXT);
        return this;
    }

    @Override
    public InvoiceEditor paymentTerms(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-20"), value, Writers.TEXT);
        return this;
    }

    @Override
    public EditorList<NoteEditor> notes() {
        return Editors.groups(builder, path, "BG-1", NoteEdit::new);
    }

    @Override
    public InvoiceEditor note(Consumer<NoteEditor> block) {
        notes().add(block);
        return this;
    }

    @Override
    public ProcessControlEditor processControl() {
        return new ProcessControlEdit(builder, TermPaths.group(path, "BG-2"));
    }

    @Override
    public InvoiceEditor processControl(Consumer<ProcessControlEditor> block) {
        Objects.requireNonNull(block, "block").accept(processControl());
        return this;
    }

    @Override
    public EditorList<PrecedingInvoiceReferenceEditor> precedingInvoiceReferences() {
        return Editors.groups(builder, path, "BG-3", PrecedingInvoiceReferenceEdit::new);
    }

    @Override
    public InvoiceEditor precedingInvoiceReference(Consumer<PrecedingInvoiceReferenceEditor> block) {
        precedingInvoiceReferences().add(block);
        return this;
    }

    @Override
    public SellerEditor seller() {
        return new SellerEdit(builder, TermPaths.group(path, "BG-4"));
    }

    @Override
    public InvoiceEditor seller(Consumer<SellerEditor> block) {
        Objects.requireNonNull(block, "block").accept(seller());
        return this;
    }

    @Override
    public BuyerEditor buyer() {
        return new BuyerEdit(builder, TermPaths.group(path, "BG-7"));
    }

    @Override
    public InvoiceEditor buyer(Consumer<BuyerEditor> block) {
        Objects.requireNonNull(block, "block").accept(buyer());
        return this;
    }

    @Override
    public PayeeEditor payee() {
        return new PayeeEdit(builder, TermPaths.group(path, "BG-10"));
    }

    @Override
    public InvoiceEditor payee(Consumer<PayeeEditor> block) {
        Objects.requireNonNull(block, "block").accept(payee());
        return this;
    }

    @Override
    public SellerTaxRepresentativeEditor sellerTaxRepresentative() {
        return new SellerTaxRepresentativeEdit(builder, TermPaths.group(path, "BG-11"));
    }

    @Override
    public InvoiceEditor sellerTaxRepresentative(Consumer<SellerTaxRepresentativeEditor> block) {
        Objects.requireNonNull(block, "block").accept(sellerTaxRepresentative());
        return this;
    }

    @Override
    public DeliveryEditor delivery() {
        return new DeliveryEdit(builder, TermPaths.group(path, "BG-13"));
    }

    @Override
    public InvoiceEditor delivery(Consumer<DeliveryEditor> block) {
        Objects.requireNonNull(block, "block").accept(delivery());
        return this;
    }

    @Override
    public PaymentInstructionsEditor paymentInstructions() {
        return new PaymentInstructionsEdit(builder, TermPaths.group(path, "BG-16"));
    }

    @Override
    public InvoiceEditor paymentInstructions(Consumer<PaymentInstructionsEditor> block) {
        Objects.requireNonNull(block, "block").accept(paymentInstructions());
        return this;
    }

    @Override
    public EditorList<DocumentLevelAllowanceEditor> documentLevelAllowances() {
        return Editors.groups(builder, path, "BG-20", DocumentLevelAllowanceEdit::new);
    }

    @Override
    public InvoiceEditor documentLevelAllowance(Consumer<DocumentLevelAllowanceEditor> block) {
        documentLevelAllowances().add(block);
        return this;
    }

    @Override
    public EditorList<DocumentLevelChargeEditor> documentLevelCharges() {
        return Editors.groups(builder, path, "BG-21", DocumentLevelChargeEdit::new);
    }

    @Override
    public InvoiceEditor documentLevelCharge(Consumer<DocumentLevelChargeEditor> block) {
        documentLevelCharges().add(block);
        return this;
    }

    @Override
    public DocumentTotalsEditor documentTotals() {
        return new DocumentTotalsEdit(builder, TermPaths.group(path, "BG-22"));
    }

    @Override
    public InvoiceEditor documentTotals(Consumer<DocumentTotalsEditor> block) {
        Objects.requireNonNull(block, "block").accept(documentTotals());
        return this;
    }

    @Override
    public EditorList<VatBreakdownEditor> vatBreakdowns() {
        return Editors.groups(builder, path, "BG-23", VatBreakdownEdit::new);
    }

    @Override
    public InvoiceEditor vatBreakdown(Consumer<VatBreakdownEditor> block) {
        vatBreakdowns().add(block);
        return this;
    }

    @Override
    public EditorList<AdditionalSupportingDocumentEditor> additionalSupportingDocuments() {
        return Editors.groups(builder, path, "BG-24", AdditionalSupportingDocumentEdit::new);
    }

    @Override
    public InvoiceEditor additionalSupportingDocument(Consumer<AdditionalSupportingDocumentEditor> block) {
        additionalSupportingDocuments().add(block);
        return this;
    }

    @Override
    public EditorList<InvoiceLineEditor> invoiceLines() {
        return Editors.groups(builder, path, "BG-25", InvoiceLineEdit::new);
    }

    @Override
    public InvoiceEditor invoiceLine(Consumer<InvoiceLineEditor> block) {
        invoiceLines().add(block);
        return this;
    }

    @Override
    public String toString() {
        return "InvoiceEditor[" + path + "]";
    }
}
