// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

/**
 * The invoice as a whole: the business terms and business groups the semantic model places at the
 * root of a document.
 *
 * <p>A view over a semantic document. Nothing is copied and nothing is resolved before it is asked
 * for: every accessor reads the document the view was built over.
 */
public interface Invoice {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the root of the document, which has no segments.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-1 Invoice number. Unique identification of the invoice in the seller's systems; no
     * identification scheme is used.
     *
     * <p>Declared cardinality 1..1, semantic data type Identifier.
     *
     * @return the value of BT-1 at the root of the document
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Identifier invoiceNumber();

    /**
     * BT-2 Invoice issue date. Date on which the invoice was issued.
     *
     * <p>Declared cardinality 1..1, semantic data type Date.
     *
     * @return the value of BT-2 at the root of the document
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    LocalDate issueDate();

    /**
     * BT-3 Invoice type code. Code for the functional type of the invoice, taken from UNTDID 1001.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @return the value of BT-3 at the root of the document
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String typeCode();

    /**
     * BT-5 Invoice currency code. The currency of every amount in this invoice; BT-111 is the one
     * amount written in the accounting currency instead.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @return the value of BT-5 at the root of the document
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String currencyCode();

    /**
     * BT-6 VAT accounting currency code. Currency used for VAT accounting and reporting in the
     * seller's country.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-6 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> vatAccountingCurrencyCode();

    /**
     * BT-7 Value added tax point date. Date on which VAT becomes chargeable for seller and buyer
     * (tax point date).
     *
     * <p>Declared cardinality 0..1, semantic data type Date.
     *
     * @return the value of BT-7 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<LocalDate> taxPointDate();

    /**
     * BT-8 Value added tax point date code. Code saying which event fixes the VAT tax point date.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @return the value of BT-8 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> taxPointDateCode();

    /**
     * BT-9 Payment due date. Date by which payment is due.
     *
     * <p>Declared cardinality 0..1, semantic data type Date.
     *
     * @return the value of BT-9 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<LocalDate> paymentDueDate();

    /**
     * BT-10 Buyer reference. Reference supplied by the buyer that lets the buyer route the invoice
     * internally.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-10 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> buyerReference();

    /**
     * BT-11 Project reference. Reference to the project the invoice relates to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @return the value of BT-11 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> projectReference();

    /**
     * BT-12 Contract reference. Reference to the contract the invoice relates to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @return the value of BT-12 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> contractReference();

    /**
     * BT-13 Purchase order reference. Reference to the buyer's purchase order.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @return the value of BT-13 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> purchaseOrderReference();

    /**
     * BT-14 Sales order reference. Reference to the seller's sales order.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @return the value of BT-14 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> salesOrderReference();

    /**
     * BT-15 Receiving advice reference. Reference to the receiving advice for the delivered goods
     * or services.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @return the value of BT-15 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> receivingAdviceReference();

    /**
     * BT-16 Despatch advice reference. Reference to the despatch advice for the delivered goods or
     * services.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @return the value of BT-16 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> despatchAdviceReference();

    /**
     * BT-17 Tender or lot reference. Names the tender, or the lot within it, that the contract
     * behind this invoice goes back to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @return the value of BT-17 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> tenderOrLotReference();

    /**
     * BT-18 Invoiced object identifier. Identifier of an object the invoice is based on, assigned
     * by the seller (e.g. a subscription, meter point or vehicle).
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the UNTDID 1153
     * list.
     *
     * @return the value of BT-18 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<Identifier> invoicedObjectIdentifier();

    /**
     * BT-19 Buyer accounting reference. Textual reference telling the buyer which ledger account to
     * book the invoice to.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-19 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> buyerAccountingReference();

    /**
     * BT-20 Payment terms. Textual description of the payment terms, such as an early-payment
     * discount or a penalty.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-20 at the root of the document, or an empty optional where the
     *     document carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> paymentTerms();

    /**
     * BG-1 INVOICE NOTE. Group carrying free-text notes about the invoice as a whole, with an
     * optional subject code.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return one view per instance of BG-1 at the root of the document, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<Note> notes();

    /**
     * BG-2 PROCESS CONTROL. Group carrying the identifiers that control how the invoice is
     * processed.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the view over the instance of BG-2 at the root of the document; the model declares it
     *     mandatory, so the view is returned even where the document carries no value under it
     */
    ProcessControl processControl();

    /**
     * BG-3 PRECEDING INVOICE REFERENCE. Group referencing an invoice that precedes this one, used
     * mainly in corrections and credit notes.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return one view per instance of BG-3 at the root of the document, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<PrecedingInvoiceReference> precedingInvoiceReferences();

    /**
     * BG-4 SELLER. Group carrying the information about the seller.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the view over the instance of BG-4 at the root of the document; the model declares it
     *     mandatory, so the view is returned even where the document carries no value under it
     */
    Seller seller();

    /**
     * BG-7 BUYER. Group carrying the information about the buyer.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the view over the instance of BG-7 at the root of the document; the model declares it
     *     mandatory, so the view is returned even where the document carries no value under it
     */
    Buyer buyer();

    /**
     * BG-10 PAYEE. Group carrying the payee, used when the party receiving payment is not the
     * seller.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the view over the instance of BG-10 at the root of the document, or an empty optional
     *     where the document carries no value under it
     */
    Optional<Payee> payee();

    /**
     * BG-11 SELLER TAX REPRESENTATIVE PARTY. Group carrying the seller's tax representative, used
     * when the seller has one.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the view over the instance of BG-11 at the root of the document, or an empty optional
     *     where the document carries no value under it
     */
    Optional<SellerTaxRepresentative> sellerTaxRepresentative();

    /**
     * BG-13 DELIVERY INFORMATION. Group saying where and when the invoiced goods or services were
     * delivered.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the view over the instance of BG-13 at the root of the document, or an empty optional
     *     where the document carries no value under it
     */
    Optional<Delivery> delivery();

    /**
     * BG-16 PAYMENT INSTRUCTIONS. Group saying how the payment is expected to be made.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the view over the instance of BG-16 at the root of the document, or an empty optional
     *     where the document carries no value under it
     */
    Optional<PaymentInstructions> paymentInstructions();

    /**
     * BG-20 DOCUMENT LEVEL ALLOWANCES. Group carrying an allowance that applies to the invoice as a
     * whole.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return one view per instance of BG-20 at the root of the document, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<DocumentLevelAllowance> documentLevelAllowances();

    /**
     * BG-21 DOCUMENT LEVEL CHARGES. Group carrying a charge (cost or non-VAT tax) that applies to
     * the invoice as a whole.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return one view per instance of BG-21 at the root of the document, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<DocumentLevelCharge> documentLevelCharges();

    /**
     * BG-22 DOCUMENT TOTALS. Group carrying the monetary totals of the invoice.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the view over the instance of BG-22 at the root of the document; the model declares
     *     it mandatory, so the view is returned even where the document carries no value under it
     */
    DocumentTotals documentTotals();

    /**
     * BG-23 VAT BREAKDOWN. Group breaking the invoice down by VAT category, rate and exemption
     * reason.
     *
     * <p>Declared cardinality 1..n.
     *
     * @return one view per instance of BG-23 at the root of the document, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<VatBreakdown> vatBreakdowns();

    /**
     * BG-24 ADDITIONAL SUPPORTING DOCUMENTS. Group referencing a supporting document that backs the
     * claims made in the invoice.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return one view per instance of BG-24 at the root of the document, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<AdditionalSupportingDocument> additionalSupportingDocuments();

    /**
     * BG-25 INVOICE LINE. Group carrying one invoice line.
     *
     * <p>Declared cardinality 1..n.
     *
     * @return one view per instance of BG-25 at the root of the document, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<InvoiceLine> invoiceLines();
}
