// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

/**
 * BG-25 INVOICE LINE. Group carrying one invoice line.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface InvoiceLine {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-126 Invoice line identifier. Identifier of the invoice line, unique within the invoice.
     *
     * <p>Declared cardinality 1..1, semantic data type Identifier.
     *
     * @return the value of BT-126 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Identifier identifier();

    /**
     * BT-127 Invoice line note. Free-text note about the invoice line.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-127 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> note();

    /**
     * BT-128 Invoice line object identifier. Identifier of an object the invoice line is based on,
     * given by the seller.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the UNTDID 1153
     * list.
     *
     * @return the value of BT-128 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<Identifier> objectIdentifier();

    /**
     * BT-129 Invoiced quantity. Quantity of items invoiced on this line.
     *
     * <p>Declared cardinality 1..1, semantic data type Quantity.
     *
     * @return the value of BT-129 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal quantity();

    /**
     * BT-130 Invoiced quantity unit of measure code. Unit of measure code for the invoiced
     * quantity, from UN/ECE Recommendation 20 with the Recommendation 21 extension.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @return the value of BT-130 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String quantityUnitCode();

    /**
     * BT-131 Invoice line net amount. Net amount of the invoice line, after line allowances and
     * charges and excluding VAT.
     *
     * <p>Declared cardinality 1..1, semantic data type Amount.
     *
     * @return the value of BT-131 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    BigDecimal netAmount();

    /**
     * BT-132 Referenced purchase order line reference. Identifier of the purchase order line this
     * invoice line refers to.
     *
     * <p>Declared cardinality 0..1, semantic data type DocumentReference.
     *
     * @return the value of BT-132 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> purchaseOrderLineReference();

    /**
     * BT-133 Invoice line Buyer accounting reference. Textual reference telling the buyer which
     * ledger account to book this invoice line to.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-133 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> buyerAccountingReference();

    /**
     * BG-26 INVOICE LINE PERIOD. Group giving the period this invoice line relates to.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the view over the instance of BG-26 in this group instance, or an empty optional
     *     where the document carries no value under it
     */
    Optional<Period> period();

    /**
     * BG-27 INVOICE LINE ALLOWANCES. Group carrying an allowance that applies to this invoice line.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return one view per instance of BG-27 in this group instance, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<Allowance> allowances();

    /**
     * BG-28 INVOICE LINE CHARGES. Group carrying a charge that applies to this invoice line.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return one view per instance of BG-28 in this group instance, in the order of their
     *     occurrence indices, empty where the document has none
     */
    List<Charge> charges();

    /**
     * BG-29 PRICE DETAILS. Group carrying the price information for the item on this invoice line.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the view over the instance of BG-29 in this group instance; the model declares it
     *     mandatory, so the view is returned even where the document carries no value under it
     */
    Price price();

    /**
     * BG-30 LINE VAT INFORMATION. Group carrying the VAT information that applies to the item on
     * this invoice line.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the view over the instance of BG-30 in this group instance; the model declares it
     *     mandatory, so the view is returned even where the document carries no value under it
     */
    Vat vat();

    /**
     * BG-31 ITEM INFORMATION. Group describing the goods or services invoiced on this line.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the view over the instance of BG-31 in this group instance; the model declares it
     *     mandatory, so the view is returned even where the document carries no value under it
     */
    Item item();
}
