// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.function.Consumer;

/**
 * BG-31 ITEM INFORMATION. Group describing the goods or services invoiced on this line.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code ItemEditor} checks a value against the grammar of its semantic data type
 * and nothing else.
 */
public interface ItemEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-153 Item name. Name of the invoiced item.
     *
     * <p>Declared cardinality 1..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    ItemEditor name(String value);

    /**
     * BT-154 Item description. Textual description of the invoiced item.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    ItemEditor description(String value);

    /**
     * BT-155 Item Seller's identifier. Identifier the seller uses for the invoiced item.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value; where
     *     the argument is the literal {@code null}, Java cannot choose between this overload and
     *     the one taking an {@code Identifier}, so write {@code (String) null} or the empty string
     *     instead
     * @return this editor
     */
    ItemEditor sellerIdentifier(String value);

    /**
     * BT-155 Item Seller's identifier. Identifier the seller uses for the invoiced item.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value; where the argument is the
     *     literal {@code null}, Java cannot choose between this overload and the one taking a
     *     string, so write {@code (Identifier) null} or the empty string instead
     * @return this editor
     */
    ItemEditor sellerIdentifier(Identifier value);

    /**
     * BT-156 Item Buyer's identifier. Identifier the buyer uses for the invoiced item.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value; where
     *     the argument is the literal {@code null}, Java cannot choose between this overload and
     *     the one taking an {@code Identifier}, so write {@code (String) null} or the empty string
     *     instead
     * @return this editor
     */
    ItemEditor buyerIdentifier(String value);

    /**
     * BT-156 Item Buyer's identifier. Identifier the buyer uses for the invoiced item.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value; where the argument is the
     *     literal {@code null}, Java cannot choose between this overload and the one taking a
     *     string, so write {@code (Identifier) null} or the empty string instead
     * @return this editor
     */
    ItemEditor buyerIdentifier(Identifier value);

    /**
     * BT-157 Item standard identifier. Item identifier from a registered standard scheme, with a
     * mandatory scheme identifier.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value
     * @param scheme the identification scheme, a code of the ISO 6523 ICD list
     * @return this editor
     */
    ItemEditor standardIdentifier(String value, String scheme);

    /**
     * BT-157 Item standard identifier. Item identifier from a registered standard scheme, with a
     * mandatory scheme identifier.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value. The registry declares the
     *     scheme of BT-157 mandatory, and this overload writes the identifier as it stands: one
     *     that carries no scheme is written and reported at validation layer L2, not refused here
     * @return this editor
     */
    ItemEditor standardIdentifier(Identifier value);

    /**
     * BT-158 Item classification identifier. Item classification code from a classification scheme,
     * with a mandatory scheme identifier and optional scheme version.
     *
     * <p>Declared cardinality 0..n, semantic data type Identifier, scheme from the UNTDID 7143
     * list.
     *
     * @return the handle of the occurrences of BT-158 in this group instance, which appends, reads,
     *     removes and empties them
     */
    SchemedIdentifierList classificationIdentifiers();

    /**
     * BT-159 Item country of origin. Country the item originates from, as an ISO 3166-1 alpha-2
     * code.
     *
     * <p>Declared cardinality 0..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    ItemEditor countryOfOrigin(String value);

    /**
     * BG-32 ITEM ATTRIBUTES. Group carrying one additional attribute of the invoiced item.
     *
     * <p>Declared cardinality 0..n.
     *
     * @return the handle of the instances of BG-32 in this group instance, which appends, reads,
     *     removes and empties them
     */
    EditorList<ItemAttributeEditor> itemAttributes();

    /**
     * BG-32 ITEM ATTRIBUTES. Group carrying one additional attribute of the invoiced item.
     *
     * <p>Declared cardinality 0..n.
     *
     * @param block what to write into the appended instance of BG-32
     * @return this editor
     * @throws NullPointerException if {@code block} is {@code null}
     */
    ItemEditor itemAttribute(Consumer<ItemAttributeEditor> block);
}
