// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link Item} from a semantic document. */
final class ItemView implements Item {

    private final SemanticDocument document;
    private final SemanticPath path;

    ItemView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public String name() {
        return Views.required(document, TermPaths.value(path, "BT-153"), Values.TEXT);
    }

    @Override
    public Optional<String> description() {
        return Views.optional(document, TermPaths.value(path, "BT-154"), Values.TEXT);
    }

    @Override
    public Optional<Identifier> sellerIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-155"), Values.IDENTIFIER);
    }

    @Override
    public Optional<Identifier> buyerIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-156"), Values.IDENTIFIER);
    }

    @Override
    public Optional<Identifier> standardIdentifier() {
        return Views.optional(document, TermPaths.value(path, "BT-157"), Values.IDENTIFIER);
    }

    @Override
    public List<Identifier> classificationIdentifiers() {
        return Views.repeated(document, path, "BT-158", Values.IDENTIFIER);
    }

    @Override
    public Optional<String> countryOfOrigin() {
        return Views.optional(document, TermPaths.value(path, "BT-159"), Values.CODE);
    }

    @Override
    public List<ItemAttribute> itemAttributes() {
        return Views.groups(document, path, "BG-32", ItemAttributeView::new);
    }

    @Override
    public String toString() {
        return "Item[" + path + "]";
    }
}
