// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.Objects;
import java.util.function.Consumer;

/** Writes {@link ItemEditor} into a document builder. */
final class ItemEdit implements ItemEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    ItemEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public ItemEditor name(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-153"), value, Writers.TEXT);
        return this;
    }

    @Override
    public ItemEditor description(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-154"), value, Writers.TEXT);
        return this;
    }

    @Override
    public ItemEditor sellerIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-155"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public ItemEditor sellerIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-155"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public ItemEditor buyerIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-156"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public ItemEditor buyerIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-156"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public ItemEditor standardIdentifier(String value, String scheme) {
        Editors.set(builder, TermPaths.value(path, "BT-157"),
                Editors.identifier(value, scheme, null), Writers.IDENTIFIER);
        return this;
    }

    @Override
    public ItemEditor standardIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-157"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public SchemedIdentifierList classificationIdentifiers() {
        return Editors.schemedIdentifiers(builder, path, "BT-158");
    }

    @Override
    public ItemEditor countryOfOrigin(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-159"), value, Writers.CODE);
        return this;
    }

    @Override
    public EditorList<ItemAttributeEditor> itemAttributes() {
        return Editors.groups(builder, path, "BG-32", ItemAttributeEdit::new);
    }

    @Override
    public ItemEditor itemAttribute(Consumer<ItemAttributeEditor> block) {
        itemAttributes().add(block);
        return this;
    }

    @Override
    public String toString() {
        return "ItemEditor[" + path + "]";
    }
}
