// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.Objects;

/** Reads {@link ItemAttribute} from a semantic document. */
final class ItemAttributeView implements ItemAttribute {

    private final SemanticDocument document;
    private final SemanticPath path;

    ItemAttributeView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public String name() {
        return Views.required(document, TermPaths.value(path, "BT-160"), Values.TEXT);
    }

    @Override
    public String value() {
        return Views.required(document, TermPaths.value(path, "BT-161"), Values.TEXT);
    }

    @Override
    public String toString() {
        return "ItemAttribute[" + path + "]";
    }
}
