/**
 * A typed view over a semantic document and a typed editor that writes one: per business
 * group of EN 16931-1 an interface with an accessor per business term, and beside it an
 * editor interface with a setter per business term, both generated from the term registry.
 *
 * <p>The view is a reading convenience, not a second document model. It holds no data:
 * {@link de.bsnsoft.esj.typed.En16931#view} wraps a
 * {@link de.bsnsoft.esj.SemanticDocument}, every accessor reads that document
 * when it is called, and nothing is copied or resolved in advance. A view is therefore as
 * immutable as the document it reads, and building one costs nothing.
 *
 * <p>The accessors hand over the Java value of the semantic data type the registry
 * records for the term, not a wrapper: {@code String} for Text, Code and Document
 * Reference, {@code BigDecimal} for the four decimal types, {@code LocalDate} for a date,
 * and the two records {@link de.bsnsoft.esj.typed.Identifier} and
 * {@link de.bsnsoft.esj.typed.BinaryObject} for the types that carry
 * supplementary components. A document itself carries no type; the registry is where the
 * type of a term is written down, once.
 *
 * <p>The shape of an accessor follows the declared cardinality of its term: a mandatory
 * term is returned directly, an optional one in an {@link java.util.Optional}, and a
 * repeatable one in a {@link java.util.List}. Whether a mandatory term is actually there
 * is a question for validation layer L3; a view that is asked for one the document does
 * not carry throws {@link de.bsnsoft.esj.typed.MissingValueException}.
 *
 * <p>{@link de.bsnsoft.esj.typed.En16931#newInvoice} and
 * {@link de.bsnsoft.esj.typed.En16931#edit} open the writing side. An editor
 * writes into one {@link de.bsnsoft.esj.SemanticDocument.Builder}, its
 * setters take the natural Java type of the term and return the editor, and a group is
 * reached through a handle typed by its cardinality: an editor for a group that occurs at
 * most once, an {@link de.bsnsoft.esj.typed.EditorList} for one that repeats,
 * and a {@link de.bsnsoft.esj.typed.ValueList} for a repeatable term. A
 * business group comes into being when a value is written into it, so there is no create
 * step and no empty group. Setting {@code null} or an empty string removes a value.
 * Cardinality and mandatory terms remain the validator's business, here as in the view.
 *
 * <p>{@link de.bsnsoft.esj.typed.Totals} is the one thing here that computes.
 * It derives the invoice line net amounts, the VAT breakdown and the document totals from
 * the prices, quantities, allowances and charges an invoice already carries, following the
 * arithmetic of EN 16931-1 and rounding once per amount. It is a policy and not part of
 * the format: it runs where
 * {@link de.bsnsoft.esj.typed.InvoiceEditor#derive} is called and never inside
 * {@code document()}, it hands back a
 * {@link de.bsnsoft.esj.typed.DerivationReport} of what it wrote, and where
 * the invoice does not state what it needs it throws
 * {@link de.bsnsoft.esj.typed.DerivationException} instead of guessing.
 *
 * <p>The interfaces, their implementations and
 * {@link de.bsnsoft.esj.typed.En16931} are generated by {@code esj-generator}
 * from {@code model/en16931/2017.json} and are checked in. One view belongs to one
 * edition of the semantic model: the view of EN 16931-1:2026 is generated from
 * {@code model/en16931/2026.json} into
 * {@code de.bsnsoft.esj.typed.v2026}, with an entry point of its own, and a
 * build may leave that edition out — which is why the package is named here and not
 * linked: a link to it would not resolve in a distribution assembled without it. What the two share is not generated and lies here and
 * in {@link de.bsnsoft.esj.typed.runtime}: the derivation policy with its
 * options, report and exception, the two value records, the two exceptions of the view,
 * the three handle interfaces, and the resolvers a generated view calls.
 *
 * <p>ESJ 0.1 generates the core model only. A document may carry extension terms; the
 * typed view does not show them and the typed editor has no setter for them, which is
 * what {@link de.bsnsoft.esj.typed.InvoiceEditor#builder()} is for.
 * {@link de.bsnsoft.esj.SemanticDocument#values()} remains the complete
 * content of the document.
 */
package de.bsnsoft.esj.typed;
