// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import java.time.LocalDate;
import java.util.Optional;

/**
 * BG-26 INVOICE LINE PERIOD. Group giving the period this invoice line relates to.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface Period {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-134 Invoice line period start date. First day of the invoice line period.
     *
     * <p>Declared cardinality 0..1, semantic data type Date.
     *
     * @return the value of BT-134 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<LocalDate> startDate();

    /**
     * BT-135 Invoice line period end date. Last day of the invoice line period.
     *
     * <p>Declared cardinality 0..1, semantic data type Date.
     *
     * @return the value of BT-135 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<LocalDate> endDate();
}
