// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.time.LocalDate;
import java.util.Objects;

/** Writes {@link PrecedingInvoiceReferenceEditor} into a document builder. */
final class PrecedingInvoiceReferenceEdit implements PrecedingInvoiceReferenceEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    PrecedingInvoiceReferenceEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public PrecedingInvoiceReferenceEditor reference(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-25"), value, Writers.DOCUMENT_REFERENCE);
        return this;
    }

    @Override
    public PrecedingInvoiceReferenceEditor issueDate(LocalDate value) {
        Editors.set(builder, TermPaths.value(path, "BT-26"), value, Writers.DATE);
        return this;
    }

    @Override
    public String toString() {
        return "PrecedingInvoiceReferenceEditor[" + path + "]";
    }
}
