// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.util.Objects;

/** Writes {@link PriceEditor} into a document builder. */
final class PriceEdit implements PriceEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    PriceEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public PriceEditor netPrice(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-146"), value, Writers.UNIT_PRICE_AMOUNT);
        return this;
    }

    @Override
    public PriceEditor discount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-147"), value, Writers.UNIT_PRICE_AMOUNT);
        return this;
    }

    @Override
    public PriceEditor grossPrice(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-148"), value, Writers.UNIT_PRICE_AMOUNT);
        return this;
    }

    @Override
    public PriceEditor baseQuantity(BigDecimal value, String unitCode) {
        Editors.set(builder, TermPaths.value(path, "BT-149"), value, Writers.QUANTITY);
        Editors.set(builder, TermPaths.value(path, "BT-150"), unitCode, Writers.CODE);
        return this;
    }

    @Override
    public PriceEditor baseQuantity(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-149"), value, Writers.QUANTITY);
        return this;
    }

    @Override
    public PriceEditor baseQuantityUnitCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-150"), value, Writers.CODE);
        return this;
    }

    @Override
    public String toString() {
        return "PriceEditor[" + path + "]";
    }
}
