// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;

/**
 * BG-2 PROCESS CONTROL. Group carrying the identifiers that control how the invoice is processed.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code ProcessControlEditor} checks a value against the grammar of its semantic
 * data type and nothing else.
 */
public interface ProcessControlEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-23 Business process type. Names the business process this invoice takes part in.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    ProcessControlEditor businessProcessType(String value);

    /**
     * BT-24 Specification identifier. Identifier of the specification (and its rule set) that the
     * invoice instance conforms to.
     *
     * <p>Declared cardinality 1..1, semantic data type Identifier.
     *
     * @param value the identifier, or {@code null} or the empty string to remove the value; where
     *     the argument is the literal {@code null}, Java cannot choose between this overload and
     *     the one taking an {@code Identifier}, so write {@code (String) null} or the empty string
     *     instead
     * @return this editor
     */
    ProcessControlEditor specificationIdentifier(String value);

    /**
     * BT-24 Specification identifier. Identifier of the specification (and its rule set) that the
     * invoice instance conforms to.
     *
     * <p>Declared cardinality 1..1, semantic data type Identifier.
     *
     * @param value the identifier as the view of another document hands it over, with whatever
     *     components it carries, or {@code null} to remove the value; where the argument is the
     *     literal {@code null}, Java cannot choose between this overload and the one taking a
     *     string, so write {@code (Identifier) null} or the empty string instead
     * @return this editor
     */
    ProcessControlEditor specificationIdentifier(Identifier value);
}
