// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import java.util.Optional;

/**
 * BG-6 SELLER CONTACT. Group carrying the seller's contact details.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface SellerContact {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-41 Seller contact point. Name of the contact point or department at the seller.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-41 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> name();

    /**
     * BT-42 Seller contact telephone number. Telephone number of the seller's contact point.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-42 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> telephone();

    /**
     * BT-43 Seller contact email address. Email address of the seller's contact point.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-43 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> email();
}
