// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;

/**
 * BG-5 SELLER POSTAL ADDRESS. Group carrying the seller's postal address.
 *
 * <p>An editor over one instance of this group inside a document builder. The group comes into
 * being when a value is written into it (specification, section 4.5), so an editor that is not
 * written into leaves nothing behind.
 *
 * <p>Setting {@code null}, an empty string or an empty file removes the value. Whether the values a
 * document ends up with are complete and consistent is the question of the validation layers, not
 * of this editor: {@code SellerPostalAddressEditor} checks a value against the grammar of its
 * semantic data type and nothing else.
 */
public interface SellerPostalAddressEditor {

    /**
     * Returns the builder every editor of this document writes into. It is the way to an extension
     * term, which the typed editor of the core model has no setter for.
     *
     * @return the builder the editor was opened over
     */
    SemanticDocument.Builder builder();

    /**
     * Returns the path of the group instance this editor writes into.
     *
     * @return the path every value of this editor lies under
     */
    SemanticPath path();

    /**
     * Returns the document as it has been written so far.
     *
     * @return an immutable document holding what was written into this editor and every other
     *     editor of the same document, in canonical path order
     */
    SemanticDocument document();

    /**
     * BT-35 Seller address line 1. First line of the seller's address, usually street name and
     * number or post office box.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    SellerPostalAddressEditor addressLine1(String value);

    /**
     * BT-36 Seller address line 2. Second line of the seller's address, carrying further address
     * detail.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    SellerPostalAddressEditor addressLine2(String value);

    /**
     * BT-162 Seller address line 3. Third line of the seller's address, carrying further address
     * detail.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    SellerPostalAddressEditor addressLine3(String value);

    /**
     * BT-37 Seller city. Town or city of the seller's address.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    SellerPostalAddressEditor city(String value);

    /**
     * BT-38 Seller post code. Postal code of the seller's address.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    SellerPostalAddressEditor postCode(String value);

    /**
     * BT-39 Seller country subdivision. Country subdivision (region, state, province) of the
     * seller's address.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    SellerPostalAddressEditor countrySubdivision(String value);

    /**
     * BT-40 Seller country code. Country code of the seller's address, from ISO 3166-1 alpha-2.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @param value the value to write, or {@code null} or the empty string to remove the value
     * @return this editor
     */
    SellerPostalAddressEditor countryCode(String value);
}
