// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link SellerPostalAddress} from a semantic document. */
final class SellerPostalAddressView implements SellerPostalAddress {

    private final SemanticDocument document;
    private final SemanticPath path;

    SellerPostalAddressView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public Optional<String> addressLine1() {
        return Views.optional(document, TermPaths.value(path, "BT-35"), Values.TEXT);
    }

    @Override
    public Optional<String> addressLine2() {
        return Views.optional(document, TermPaths.value(path, "BT-36"), Values.TEXT);
    }

    @Override
    public Optional<String> addressLine3() {
        return Views.optional(document, TermPaths.value(path, "BT-162"), Values.TEXT);
    }

    @Override
    public Optional<String> city() {
        return Views.optional(document, TermPaths.value(path, "BT-37"), Values.TEXT);
    }

    @Override
    public Optional<String> postCode() {
        return Views.optional(document, TermPaths.value(path, "BT-38"), Values.TEXT);
    }

    @Override
    public Optional<String> countrySubdivision() {
        return Views.optional(document, TermPaths.value(path, "BT-39"), Values.TEXT);
    }

    @Override
    public String countryCode() {
        return Views.required(document, TermPaths.value(path, "BT-40"), Values.CODE);
    }

    @Override
    public String toString() {
        return "SellerPostalAddress[" + path + "]";
    }
}
