// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import java.util.List;
import java.util.Optional;

/**
 * BG-4 SELLER. Group carrying the information about the seller.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface Seller {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-27 Seller name. Full name of the seller as registered in the national register of legal
     * entities.
     *
     * <p>Declared cardinality 1..1, semantic data type Text.
     *
     * @return the value of BT-27 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String name();

    /**
     * BT-28 Seller trading name. Name the seller is known by, where different from the registered
     * seller name.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-28 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> tradingName();

    /**
     * BT-29 Seller identifier. Identification of the seller; may carry an identification scheme
     * identifier.
     *
     * <p>Declared cardinality 0..n, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @return the values of BT-29 in this group instance, in the order of their occurrence indices,
     *     empty where the document carries none
     * @throws ValueTypeException if a value there is no value of that semantic data type
     */
    List<Identifier> identifiers();

    /**
     * BT-30 Seller legal registration identifier. Identifier issued to the seller by an official
     * registrar of legal entities.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the ISO 6523 ICD
     * list.
     *
     * @return the value of BT-30 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<Identifier> legalRegistrationIdentifier();

    /**
     * BT-31 Seller VAT identifier. VAT identifier assigned to the seller.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier.
     *
     * @return the value of BT-31 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<Identifier> vatIdentifier();

    /**
     * BT-32 Seller tax registration identifier. Local identification of the seller assigned by its
     * tax authority or a certifier, other than the VAT identifier.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier.
     *
     * @return the value of BT-32 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<Identifier> taxRegistrationIdentifier();

    /**
     * BT-33 Seller additional legal information. Additional legal information about the seller that
     * is relevant for the buyer.
     *
     * <p>Declared cardinality 0..1, semantic data type Text.
     *
     * @return the value of BT-33 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<String> additionalLegalInformation();

    /**
     * BT-34 Seller electronic address. Electronic address of the seller, with a mandatory scheme
     * identifier saying which address scheme is used.
     *
     * <p>Declared cardinality 0..1, semantic data type Identifier, scheme from the CEF EAS list.
     *
     * @return the value of BT-34 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<Identifier> electronicAddress();

    /**
     * BG-5 SELLER POSTAL ADDRESS. Group carrying the seller's postal address.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the view over the instance of BG-5 in this group instance; the model declares it
     *     mandatory, so the view is returned even where the document carries no value under it
     */
    SellerPostalAddress postalAddress();

    /**
     * BG-6 SELLER CONTACT. Group carrying the seller's contact details.
     *
     * <p>Declared cardinality 0..1.
     *
     * @return the view over the instance of BG-6 in this group instance, or an empty optional where
     *     the document carries no value under it
     */
    Optional<SellerContact> contact();
}
