// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;

/**
 * BG-11 SELLER TAX REPRESENTATIVE PARTY. Group carrying the seller's tax representative, used when
 * the seller has one.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface SellerTaxRepresentative {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-62 Seller tax representative name. Name of the seller's tax representative.
     *
     * <p>Declared cardinality 1..1, semantic data type Text.
     *
     * @return the value of BT-62 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String name();

    /**
     * BT-63 Seller tax representative VAT identifier. The VAT identifier of the representative that
     * BG-11 names for the seller.
     *
     * <p>Declared cardinality 1..1, semantic data type Identifier.
     *
     * @return the value of BT-63 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Identifier vatIdentifier();

    /**
     * BG-12 SELLER TAX REPRESENTATIVE POSTAL ADDRESS. Group carrying the postal address of the
     * seller's tax representative.
     *
     * <p>Declared cardinality 1..1.
     *
     * @return the view over the instance of BG-12 in this group instance; the model declares it
     *     mandatory, so the view is returned even where the document carries no value under it
     */
    SellerTaxRepresentativePostalAddress postalAddress();
}
