// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.util.Objects;
import java.util.function.Consumer;

/** Writes {@link SellerTaxRepresentativeEditor} into a document builder. */
final class SellerTaxRepresentativeEdit implements SellerTaxRepresentativeEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    SellerTaxRepresentativeEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public SellerTaxRepresentativeEditor name(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-62"), value, Writers.TEXT);
        return this;
    }

    @Override
    public SellerTaxRepresentativeEditor vatIdentifier(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-63"), Editors.identifier(value, null, null),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public SellerTaxRepresentativeEditor vatIdentifier(Identifier value) {
        Editors.set(builder, TermPaths.value(path, "BT-63"), Editors.identifier(value),
                Writers.IDENTIFIER);
        return this;
    }

    @Override
    public SellerTaxRepresentativePostalAddressEditor postalAddress() {
        return new SellerTaxRepresentativePostalAddressEdit(builder, TermPaths.group(path, "BG-12"));
    }

    @Override
    public SellerTaxRepresentativeEditor postalAddress(Consumer<SellerTaxRepresentativePostalAddressEditor> block) {
        Objects.requireNonNull(block, "block").accept(postalAddress());
        return this;
    }

    @Override
    public String toString() {
        return "SellerTaxRepresentativeEditor[" + path + "]";
    }
}
