// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import java.math.BigDecimal;
import java.util.Optional;

/**
 * BG-30 LINE VAT INFORMATION. Group carrying the VAT information that applies to the item on this
 * invoice line.
 *
 * <p>A view over one instance of this group inside a semantic document. Nothing is copied and
 * nothing is resolved before it is asked for: every accessor reads the document the view was built
 * over.
 */
public interface Vat {

    /**
     * Returns the document this view reads.
     *
     * @return the document the view was built over
     */
    SemanticDocument document();

    /**
     * Returns the path of the group instance this view reads.
     *
     * @return the path every value of this view lies under
     */
    SemanticPath path();

    /**
     * BT-151 Invoiced item VAT category code. VAT category code that applies to the invoiced item,
     * from UNTDID 5305.
     *
     * <p>Declared cardinality 1..1, semantic data type Code.
     *
     * @return the value of BT-151 in this group instance
     * @throws MissingValueException if the document carries no value there; the model declares the
     *     term mandatory, which validation layer L3 checks and this view does not
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    String vatCategoryCode();

    /**
     * BT-152 Invoiced item VAT rate. VAT rate that applies to the invoiced item, as a percentage.
     *
     * <p>Declared cardinality 0..1, semantic data type Percentage.
     *
     * @return the value of BT-152 in this group instance, or an empty optional where the document
     *     carries none
     * @throws ValueTypeException if the value there is no value of that semantic data type
     */
    Optional<BigDecimal> vatRate();
}
