// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.util.Objects;

/** Writes {@link VatBreakdownEditor} into a document builder. */
final class VatBreakdownEdit implements VatBreakdownEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    VatBreakdownEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public VatBreakdownEditor taxableAmount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-116"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public VatBreakdownEditor taxAmount(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-117"), value, Writers.AMOUNT);
        return this;
    }

    @Override
    public VatBreakdownEditor vatCategoryCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-118"), value, Writers.CODE);
        return this;
    }

    @Override
    public VatBreakdownEditor vatRate(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-119"), value, Writers.PERCENTAGE);
        return this;
    }

    @Override
    public VatBreakdownEditor exemptionReasonText(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-120"), value, Writers.TEXT);
        return this;
    }

    @Override
    public VatBreakdownEditor exemptionReasonCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-121"), value, Writers.CODE);
        return this;
    }

    @Override
    public String toString() {
        return "VatBreakdownEditor[" + path + "]";
    }
}
