// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.Editors;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Writers;
import java.math.BigDecimal;
import java.util.Objects;

/** Writes {@link VatEditor} into a document builder. */
final class VatEdit implements VatEditor {

    private final SemanticDocument.Builder builder;
    private final SemanticPath path;

    VatEdit(SemanticDocument.Builder builder, SemanticPath path) {
        this.builder = Objects.requireNonNull(builder, "builder");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument.Builder builder() {
        return builder;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public SemanticDocument document() {
        return builder.build();
    }

    @Override
    public VatEditor vatCategoryCode(String value) {
        Editors.set(builder, TermPaths.value(path, "BT-151"), value, Writers.CODE);
        return this;
    }

    @Override
    public VatEditor vatRate(BigDecimal value) {
        Editors.set(builder, TermPaths.value(path, "BT-152"), value, Writers.PERCENTAGE);
        return this;
    }

    @Override
    public String toString() {
        return "VatEditor[" + path + "]";
    }
}
