// Generated by esj-generator from EN16931 registry
// EN 16931-1:2017+A1:2019/AC:2020, registry version 0.1.
// Do not edit.

package de.bsnsoft.esj.typed;

import de.bsnsoft.esj.SemanticDocument;
import de.bsnsoft.esj.SemanticPath;
import de.bsnsoft.esj.typed.runtime.TermPaths;
import de.bsnsoft.esj.typed.runtime.Values;
import de.bsnsoft.esj.typed.runtime.Views;
import java.math.BigDecimal;
import java.util.Objects;
import java.util.Optional;

/** Reads {@link Vat} from a semantic document. */
final class VatView implements Vat {

    private final SemanticDocument document;
    private final SemanticPath path;

    VatView(SemanticDocument document, SemanticPath path) {
        this.document = Objects.requireNonNull(document, "document");
        this.path = Objects.requireNonNull(path, "path");
    }

    @Override
    public SemanticDocument document() {
        return document;
    }

    @Override
    public SemanticPath path() {
        return path;
    }

    @Override
    public String vatCategoryCode() {
        return Views.required(document, TermPaths.value(path, "BT-151"), Values.CODE);
    }

    @Override
    public Optional<BigDecimal> vatRate() {
        return Views.optional(document, TermPaths.value(path, "BT-152"), Values.PERCENTAGE);
    }

    @Override
    public String toString() {
        return "Vat[" + path + "]";
    }
}
